### ISSUE TITLE
Is it possible to sync channel mute state? 

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#105]
Hi, 

Assuming I have a prominent "mute channel" control somewhere on the message list view, is it possible for the control to stay synchronised across multiple devices and platforms? E.g. if I mute the channel on one device, all other app instances update the control accordingly. The state of the control provided in the demo seems to be handled locally only. I've seen mentions of `channelChangePublisher` in the docs but not quite sure if it is the way to go re mute sync.

**Comment by martinmitrevski** [comment]
Hey @zrxq,

The "mute channel" feature is synced across devices, you would just need to update the channel in the place where your control is. 

As you've suggested, you can use `channelChangePublisher`, or the other option is to use the delegate API:
```swift
func channelController(
        _ channelController: ChatChannelController,
        didUpdateChannel channel: EntityChange<ChatChannel>
    )
```

When you update the channel, the mute details will update accordingly on all devices.

Hope this helps,
Martin

**Comment by zrxq** [comment]
Hey Martin,

Thanks for the response. I'm looking at `ChatChannelInfoViewModel` and it seems that currently it is not tracking any updates to the channel state, hence the confusion. 

So, to confirm, something along the following lines:
```
        @State var isMuted: Bool = false
        channelController.channelChangePublisher.sink { [weak self] _ in
            self.isMuted = self?.channelController.channel?.isMuted ?? false
        }
        .store(in: &cancellables)
```
...should work as expected, right?

**Comment by martinmitrevski** [comment]
@zrxq yes, exactly, that should do the trick. 

We are not tracking this in the channel info at the moment (only in our channel list), but we will enable it soon there too, thanks for the hint 👍

**Comment by zrxq** [comment]
Thank you for the clarification!
