### ISSUE TITLE
Entering "/" followed by new line and sending crashes the chat

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#108]
## What did you do?

![RocketSim_Recording_iPhone_13_mini_2022-06-18_23 03 40](https://user-images.githubusercontent.com/820120/174455540-315eb0f6-7f35-40f3-ba70-6ba9e861c8fd.gif)

## What did you expect to happen?

A weird message sent.

## What happened instead?

App crashed.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @zrxq,

Thanks for reporting this. We will analyse it and provide a fix soon.

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @zrxq,

The issue is now resolved and available on `main`. We are showing a system message when an invalid command is sent.

Regards,
Martin
