### ISSUE TITLE
Can't use ComposerInputView in custom viewFactory

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#112]
## What did you do?
- I need to add a view just beside `ComposerInputView` in the rounded circle.
- For that, I use `makeComposerInputView` in the custom view factory and try to use the default ComposerInputView in HStack.

## What did you expect to happen?
- can't use `ComposerInputView` outside of SDK because its initialiser is internal.
- The `ComposerInputView` initialiser should be public. So that we can use it outside of SDK.
- Need customisation exactly what we have with `ChatChannelView`
- I attached a screenshot for your reference.

## GetStream Environment
**GetStream Chat version:** 4.17.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** Iphone-13

## Additional context
<img width="1147" alt="Screenshot 2022-06-28 at 6 41 51 PM" src="https://user-images.githubusercontent.com/47667077/176189532-df022d30-a53f-4b85-ad39-e5710e722257.png">

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

Does it help if you do `DefaultViewFactory.shared.makeComposerInputView`, instead of initializing `ComposerInputView` directly?

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,
Thanks for the quick response.

The ComposerInputView takes default 240 height.
Could you please help me on this?

<img width="508" alt="Screenshot 2022-06-28 at 7 29 10 PM" src="https://user-images.githubusercontent.com/47667077/176197601-99c4d642-ef66-4bff-8a9f-dbd144f9b943.png">
<img width="334" alt="Screenshot 2022-06-28 at 7 29 24 PM" src="https://user-images.githubusercontent.com/47667077/176197654-0cb2846c-c3b6-4063-9126-6677a3e41960.png">

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,
Thanks for the quick reply.

Yeah, that will work.
Thank you.
