### ISSUE TITLE
MessageComposerView height is not consistent

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#118]
## What did you do?
- open attachment picker view
- open the keyboard by clicking "send a message"

## What did you expect to happen?
- Height for both AttachmentPickerView/keyboard should be consistent

## What happened instead?
- AttachmentPickerView/keyboard height not consistent

## GetStream Environment
**GetStream Chat version:** 4.17.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:**

## Additional context

https://user-images.githubusercontent.com/47667077/177139179-fd787c61-4d63-4b89-ad6f-36a56b49f898.mp4

**Comment by martinmitrevski** [comment]
Hey @ajay-simform, 

We are aware of this issue - it happens only if you open the picker first and the keyboard second. The reason for this initial mis-alignment is that we can't know the size of the keyboard until it's first shown and we use some default value for the picker first.

Unfortunately, we can't do much about it with the APIs we have from the iOS SDK at the moment.

Best, 
Martin
