### ISSUE TITLE
Please expose textColor View extension to use outside of SDK

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#120]
## What are you trying to achieve?
- Need to use in-built textColor View extension outside of SDK.

## If possible, how can you achieve this currently?
- can't access it.

## What would be the better way?
- Please make the public extension function

## GetStream Environment
**GetStream Chat version:** 4.17.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

## Additional context
<img width="507" alt="Screenshot 2022-07-05 at 11 18 32 AM" src="https://user-images.githubusercontent.com/47667077/177258164-a2ac577c-0743-47d9-b981-1fa0f381bc6f.png">

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

This is now made public.

Best,
Martin
