### ISSUE TITLE
Can't create custom attachment payload

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#121]
## What did you do?
- I want to create a custom attachment view for custom messages.
- For that, I am confirming AttachmentPayload and creating a new payload
- Can not access Streamchat's `decodeExtraData` function due to internal protection level

## What did you expect to happen?
- Please make `decodeExtraData` function as public

## What happened instead?
- can't access `decodeExtraData` function

## GetStream Environment
**GetStream Chat version:** 4.17.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

## Additional context

<img width="669" alt="Screenshot 2022-07-05 at 3 08 44 PM" src="https://user-images.githubusercontent.com/47667077/177299183-7b3d8258-9486-4401-a403-7661743fe8e8.png">

**Comment by martinmitrevski** [comment]
Hey @ajay-simform, 

This is in our low-level client `StreamChat` and I've seen you've already created an issue there.

In any case, that method shouldn't be exposed public, you can check our guide on custom attachments for more info here: https://getstream.io/chat/docs/sdk/ios/swiftui/components/message-composer/#contact-payload.

Best, 
Martin
