### ISSUE TITLE
Getting booted out of channel after editing channel name

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#122]
## What did you do?
1. Navigate into a channel that you are a member in (not the owner, someone else had to create the channel)2. 
2. Rename the channel 

## What did you expect to happen?
To be in the channel, with the new name

## What happened instead?
The channel is successfully renamed, but the channel is immediately dismissed and you're returned to the inbox.
 
We get an error log:
"SwiftUI encountered an issue when pushing a NavigationLink. Please file a bug."

and based on my research, this might be a possible solution: https://stackoverflow.com/a/67626758
and an edit you'd make around https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannelList/ChatChannelList.swift#L142

## GetStream Environment
**GetStream Chat version:** 4.17.0
**GetStream Chat frameworks:** StreamChatSwiftUI `main`
**iOS version:** 15.4
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** simulators, and iPhone 12

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

Thanks for reporting the issue. We will analyse it and provide an update soon.

Best,
Martin

**Comment by adolfogarza** [comment]
Hi @AndrewSB, do you know if the simulator is the one that creates the channel, or is the device the user who creates the channel?

**Comment by AndrewSB** [comment]
within our project, doesn't seem to repro within the TestFlight of your demo app.
its possible that its coming from simulator created channels, i'll post back with more details once we have them
