### ISSUE TITLE
can't add custom spacing between bubbles

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#124]
## What are you trying to achieve?
- I want to set custom height between bubbles

## If possible, how can you achieve this currently?
- I can't do that.

## GetStream Environment
**GetStream Chat version:** 4.18.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

## Additional context
<img width="327" alt="Screenshot 2022-07-08 at 10 37 55 AM" src="https://user-images.githubusercontent.com/47667077/177922293-783d6c19-3387-4947-8b0a-d2670aaed197.png">

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

This is already possible with a custom message modifier. We have now also exposed a parameter, so you don't have to implement the whole modifier. Here's an example (check the comments for customization options):

```swift
    func makeMessageViewModifier(for messageModifierInfo: MessageModifierInfo) -> some ViewModifier {
        MessageBubbleModifier(
            message: messageModifierInfo.message,
            isFirst: messageModifierInfo.isFirst,
            injectedBackgroundColor: messageModifierInfo.injectedBackgroundColor,
            cornerRadius: messageModifierInfo.cornerRadius,
            forceLeftToRight: messageModifierInfo.forceLeftToRight,
            topPadding: 0, // adjust this if needed
            bottomPadding: messageModifierInfo.isFirst ? 0 : 4 // use the isFirst check if you want padding only for messages in a group
        )
    }
```
