### ISSUE TITLE
ChatChannelView not updating when moving to foreground

### ISSUE THREAD

**Issue by rlindsey2** [GetStream/stream-chat-swiftui#126]
## What did you do?
Another account sent my device a message whilst the app was in the background, the web socket was disconnected, and the view left active in the app was the ChatChannelView.

## What did you expect to happen?
When I unlocked my phone I expected to see the message showing in the ChatChannelView.

## What happened instead?
There was no message in the view, although any messages sent from that moment on would display. To be able to see any messages sent whilst the device was locked I have to close the view and reopen it. 
This does not happen whilst the websocket seems to be open, only after about 30 seconds or so.

Screen recording to show what happens:
https://user-images.githubusercontent.com/37937966/178183202-96f08c65-5ece-44de-bcb7-647a485e18ca.mov

Extra context:
I am directly presenting a ChatChannelView.

```
NavigationLink(isActive: $showChat) {
    ChatChannelView(viewFactory: CustomFactory.shared,
                        channelController: getChannelController(channelId: chatEventId))
} label: { }
```

When I say the web socket is disconnected I assume that's the case at least as it's when I get the below statement printed out to the Xcode console. 
![Screenshot 2022-07-11 at 1 22 40 pm](https://user-images.githubusercontent.com/37937966/178183887-7b2a0f74-e1ce-4941-8b94-9e40af751b40.png)

## GetStream Environment
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 4.15.0
**Device:** Happens on all devices. Tested from iPhone 7 to 13.

**Comment by martinmitrevski** [comment]
Hey @rlindsey2,

Thanks for reporting the issue and your analysis. 

My assumption here is that when you come back into the foreground, your `getChannelController` method creates a new channel controller and passes it to the `ChatChannelView`. Can you please check if that's the case?

If that's the issue, persisting the controller should solve the issue (you can use, for example, the `showChat` binding to clear the channel controller on pop).

I've tried reproducing this in our demo app, and it works correctly there (we keep the same instance of the channel controller while the chat screen is pushed).

Looking forward to your feedback,
Martin

**Comment by rlindsey2** [comment]
Hey Martin,
I've just had a look into this and it isn't creating a new channel controller when moving to the foreground. It works fine if I background the app and foreground it again within say the first 30 seconds. It's only after that, where it will not. Although for any messaging sent again whilst re-foregrounded will then come through - but missing any whilst it was backgrounded.

Can you link me to an example demo app where you're using a ChatChannelView directly without a ChatChannelListView? Every implementation I've come across always uses a ChatChannelListView which we don't want to use, and I'm wondering if there's something I'm missing there.

**Comment by martinmitrevski** [comment]
Hey @rlindsey2,

We were able to reproduce the issue on our end. It's not in our SwiftUI SDK, but in our low-level client.

We are fixing the issue now, you can check its status in this PR: https://github.com/GetStream/stream-chat-swift/pull/2163.

The fix will be available in the SwiftUI SDK, mid next week (release is usually Tuesday / Wednesday). 

Best, 
Martin

**Comment by rlindsey2** [comment]
Sorry for the slow reply on my side but great to hear it's a bug and something you guys are looking into. Thanks!

**Comment by martinmitrevski** [comment]
Hey @rlindsey2,

The fix is now deployed in the SwiftUI SDK, so you can use it either in the 4.19.0 release or on our `main` branch.

Thanks for your patience.

Best,
Martin

**Comment by rlindsey2** [comment]
perfect, thanks!
