### ISSUE TITLE
Scroll to top exposure - feature request

### ISSUE THREAD

**Issue by tr736-reclip** [GetStream/stream-chat-swiftui#127]
## What are you trying to achieve?
Ultimately I want to scroll to the top of the chat groups when i tap tab bar icon for chat.

## If possible, how can you achieve this currently?
You cant. I think the repo needs to expose a scrollToTop function

**Comment by martinmitrevski** [comment]
Moving this to discussions here: https://github.com/GetStream/stream-chat-swift/discussions/2185.
