### ISSUE TITLE
Sent messages don't show in MessageList if a backswipe is cancelled in the thread

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#128]
## What did you do?
Tried to send a message, after cancelling a back swipe

## What did you expect to happen?
The new message to show up inside the thread

## What happened instead?
The message doesn't show in the thread until dismissing and returning to the thread

https://user-images.githubusercontent.com/3814772/178351522-10260da1-27c3-4f1a-ad4a-df0d85c5b765.MP4

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, 

Thanks for spotting this. It's fixed now and available on `main`.

Best,
Martin

**Comment by martinmitrevski** [comment]
should be 4.19.0 from July last year: https://github.com/GetStream/stream-chat-swiftui/releases/tag/4.19.0. Are you having some issues?

**Comment by martinmitrevski** [comment]
there are no changes in this area between these releases, most likely it's the low-level client. If you are referring to https://github.com/GetStream/stream-chat-swift/issues/2431, we're tackling that from Monday.
