### ISSUE TITLE
can't edit channel subtitle in channelList

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#129]
## What are you trying to achieve?
- I want to update the channel subtitle for my custom messages in channel list view.

## If possible, how can you achieve this currently?
- I can't update the channel subtitle

## What would be the better way?
- There should be some factory function which helps to update subtitle

## GetStream Environment
**GetStream Chat version:** 4.18.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

## Additional context
![Untitled 2](https://user-images.githubusercontent.com/47667077/178455049-583f3955-0088-4ff9-a8ec-289e8b9fa84d.png)

**Comment by martinmitrevski** [comment]
Hey @ajay-simform, 

The way to customize this is to replace the whole channel list item, we don't plan to expose factory methods for the smaller parts of it.

In this case, you can reuse our swipeable list item, if you want to keep that functionality:

```swift
    public func makeChannelListItem(
        channel: ChatChannel,
        channelName: String,
        avatar: UIImage,
        onlineIndicatorShown: Bool,
        disabled: Bool,
        selectedChannel: Binding<ChannelSelectionInfo?>,
        swipedChannelId: Binding<String?>,
        channelDestination: @escaping (ChannelSelectionInfo) -> ChannelDestination,
        onItemTap: @escaping (ChatChannel) -> Void,
        trailingSwipeRightButtonTapped: @escaping (ChatChannel) -> Void,
        trailingSwipeLeftButtonTapped: @escaping (ChatChannel) -> Void,
        leadingSwipeButtonTapped: @escaping (ChatChannel) -> Void
    ) -> some View {
        let listItem = YourCustomListItem(
            channel: channel,
            channelName: channelName,
            avatar: avatar,
            onlineIndicatorShown: onlineIndicatorShown,
            disabled: disabled,
            selectedChannel: selectedChannel,
            channelDestination: channelDestination,
            onItemTap: onItemTap
        )
        return ChatChannelSwipeableListItem(
            factory: self,
            channelListItem: listItem,
            swipedChannelId: swipedChannelId,
            channel: channel,
            trailingRightButtonTapped: trailingSwipeRightButtonTapped,
            trailingLeftButtonTapped: trailingSwipeLeftButtonTapped,
            leadingSwipeButtonTapped: leadingSwipeButtonTapped
        )
    }
```

```swift
public struct YourCustomListItem<ChannelDestination: View>: View {
    private var channel: ChatChannel
    private var channelName: String
    private var avatar: UIImage
    private var disabled: Bool
    private var onlineIndicatorShown: Bool
    @Binding private var selectedChannel: ChannelSelectionInfo?
    private var channelDestination: (ChannelSelectionInfo) -> ChannelDestination
    private var onItemTap: (ChatChannel) -> Void
 
    public var body: some View {
        ZStack {
            CustomListItem(
                channel: channel,
                channelName: channelName,
                injectedChannelInfo: injectedChannelInfo,
                avatar: avatar,
                onlineIndicatorShown: onlineIndicatorShown,
                disabled: disabled,
                onItemTap: onItemTap
            )
                                    
            NavigationLink(
                tag: channel.channelSelectionInfo,
                selection: $selectedChannel
            ) {
                LazyView(channelDestination(channel.channelSelectionInfo))
            } label: {
                EmptyView()
            }
        }
        .id("\(channel.id)-navigatable")
    }
```

Hope this helps.
Best,
Martin

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,
Thanks for the response.

Could you please change access control to public for these views? `ChatTitleView` `MessageReadIndicatorView` `TypingIndicatorView` 

It is easier for us to re-use directly from stream chat.

Thank you.

**Comment by martinmitrevski** [comment]
Hi @ajay-simform,

Yes, they are exposed now as public, on `main`.

Best,
Martin

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,

Along with these, please help to expose the followings:
- ChatChannel extension variable `shouldShowTypingIndicator`
- Image extension `customizable` function
- ChatChannel extension variable `timestampText `

Thank you

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,

Can you expose `UnreadIndicatorView` initialiser as well?

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

Sure, that one is exposed as well now.

**Comment by zeeshansuleman** [comment]
@martinmitrevski I am trying the same to update the channel list view using custom factory. When pasting the function the channel list item is not accessible to me.

![WhatsApp Image 2022-08-13 at 8 01 02 AM](https://user-images.githubusercontent.com/12757747/184640817-cf03a51d-e789-46e2-8cd8-689ea4adaba6.jpeg)

**Comment by martinmitrevski** [comment]
@zeeshansuleman which part is not accessible? The views in this ticket are already exposed, please check if you are using an older version of the SDK.

**Comment by zeeshansuleman** [comment]
@martinmitrevski 
<img width="1284" alt="Screenshot 2022-08-15 at 8 18 36 PM" src="https://user-images.githubusercontent.com/12757747/184663975-03bcb08f-355a-4419-b80e-1413caf21129.png">

Look at the screenshot we are getting the error on "CustomListItem". 
**Stream SDK Version:** 4.16.0 we are using.

**Comment by martinmitrevski** [comment]
Hey @zeeshansuleman,

That `CustomListItem` is not in our SDK, but a view that you should create in your app to customize the channel.

**Comment by zeeshansuleman** [comment]
@martinmitrevski 
We need to change channel name & image. 
Could you please change access control to public for this view? `ChatChannelListItem`
We are using just "One to One" chat in our app. That's why needs to change the channel title & image to receiver's name & image. So. need this view `ChatChannelListItem` public.

**Comment by martinmitrevski** [comment]
@zeeshansuleman we've added a public init for the `ChatChannelListItem`. It's already available on our `main` branch, and it will be part of the upcoming 4.21.0 release next week.
