### ISSUE TITLE
 'internal' protection level error - showAvatars , utils.messageCachingUtils

### ISSUE THREAD

**Issue by jitendra-simform** [GetStream/stream-chat-swiftui#136]
## What did you do?
Customising Reaction overlay view using func  'makeReactionsOverlayView'
 

## What did you expect to happen?
Customised  Reaction overlay view

## What happened instead?

Getting below error's

- 'showAvatars' is inaccessible due to 'internal' protection level
- 'messageCachingUtils' is inaccessible due to 'internal' protection level

## GetStream Environment
**GetStream Chat version:*4.17*
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:*15.5*
**Swift version:*5*
**Xcode version:*13.4.1*
**Device:*Simulator*

## Additional context

Could you please remove protection level and make them public, so we can access them while customising Reaction overlay view

![Screenshot 2022-07-13 at 2 08 59 PM](https://user-images.githubusercontent.com/97155807/179178712-8b648832-da7f-41a2-beb5-5f30e532090a.png)

**Comment by martinmitrevski** [comment]
Hello @jitendra-simform,

The `showAvatars` property is already public, you just need to upgrade to the latest version of our SDK (4.18.0 or the `main` branch).

For the other property, please use this instead:
```swift
messageDisplayInfo.message.authorDisplayInfo
```

Best,
Martin

**Comment by jitendra-simform** [comment]
@martinmitrevski Thanks for quick response , let me check

**Comment by jitendra-simform** [comment]
> Hello @jitendra-simform,
> 
> The `showAvatars` property is already public, you just need to upgrade to the latest version of our SDK (4.18.0 or the `main` branch).
> 
> For the other property, please use this instead:
> 
> ```swift
> messageDisplayInfo.message.authorDisplayInfo
> ```
> 
> Best, Martin


Hello @martinmitrevski  , showAvatars still having internal protection error 
Used 4.18.0 https://github.com/GetStream/stream-chat-swiftui/commit/83f2e0aad5d121b9d3577facaab49dd67a276d9d

![Screenshot 2022-07-15 at 6 23 10 PM](https://user-images.githubusercontent.com/97155807/179227302-235b01de-77d3-44a2-8494-c443c0b3b3e9.png)

**Comment by martinmitrevski** [comment]
Hey @jitendra-simform, 

Yes, you are right, we fixed this in the past week. So for now, you can either switch to our `main` branch, or wait for the release 4.19.0 next week.

**Comment by jitendra-simform** [comment]
Thank you so much @martinmitrevski
