### ISSUE TITLE
Bug with channelController.hideChannel(hideMessages: true)

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#145]
The behavior of `channelController.hideChannel(hideMessages: true)` seems to be inconsistent. we've tested it in the 2 cases below:

## What did you do?

setup: Alice hides channel they have with Bob

case 1: Bob goes into that channel and messages Alice
case 2: Alice creates a new channel (using `createDirectMessageChannelWith: [Alice.userID, Bob.userID]`)

## What did you expect to happen?

in both cases, we expected Bob to see the message history of the channel, and for alice not to

## What happened instead?

Bob's experience is correct
Alice's is not.
in case 1, all of the message history came back
in case 2, Alice's history correctly doesn't re-appear in the channel

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

Thanks for reporting this. We will analyse this and report back when we have updates.

Best,
Martin

**Comment by AndrewSB** [comment]
thanks @martinmitrevski, do you have any idea on how you might fix this soon?

**Comment by martinmitrevski** [comment]
hey @AndrewSB,

We've already done some analysis here, and it's actually not in the SwiftUI SDK, but in our low-level client. 

The team is investigating the issue there. As soon as we have more info, we will let you know.

**Comment by AndrewSB** [comment]
@martinmitrevski sounds good, it looks like it got merged into streamchat, we'll QA this once this library is using the latest version of streamchat

**Comment by jfru** [comment]
@AndrewSB this is fixed in Alpha, you can close
