### ISSUE TITLE
iOS 16 compatibility

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swiftui#147]
## What did you do?
Tried to build the sdk using new xCode for iOS 16 BETA

## What did you expect to happen?
Build to succeed

## What happened instead?
Build Failed with the following compiler error (see attached screenshot)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
![Screen Shot 2022-07-21 at 5 50 39 PM](https://user-images.githubusercontent.com/17079221/180338951-ae3a0b52-c7f7-4a23-a205-b7d735779013.png)

**Comment by martinmitrevski** [comment]
Hey @jfru,

Yes, there are some issues with the `available` attributes in Xcode 14 betas. We have a branch for iOS 16 compatibility, which is called `ios16`, so you can use that one in the meantime.

Best,
Martin

**Comment by AndrewSB** [comment]
when do you plan on merging the branch into main?

**Comment by martinmitrevski** [comment]
I suggest tracking this PR: https://github.com/GetStream/stream-chat-swift/pull/2202. Should be soon, if all our tests are completed successfully.

**Comment by martinmitrevski** [comment]
The PR was merged in our main repo, it will be available on the SwiftUI repo on the next release (mid next week).

**Comment by martinmitrevski** [comment]
This is now released and available from 4.20.0 and our main branch.
