### ISSUE TITLE
More details on Encryption/Decryption E2E with CryptoKit

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swiftui#150]
## What did you do?
We need E2E encryption for one to one as well as group chats

## What did you expect to happen?
A proper documentation for integration of E2E with CryptoKit

## What happened instead?
Old documentation from which some of the methods are now not available 

## GetStream Environment
GetStream Chat version: 4.18.0
GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
iOS version: 15.5
Swift version: 5
Xcode version: 13.4.1
Device: iPhone-13

## Additional context
For using E2E encryption there are already documentation and samples available over here - 
- https://getstream.io/blog/ios-cryptokit-framework-chat/

But this seems old and some of the methods classes have been removed since and there'e no new updates on how we can use this with the latest updates. 
Can you please share some details for the same ? 
Like is it supported for one-one as well as in group chats and do we need to pass anything different in group chat then in one-one chats ?
Do we pass our own public key for encryption and uses receiver private key for decryption ? 

It'll be great if there's any lates documentation or example for the same. 
Thanks.

**Comment by martinmitrevski** [comment]
Hi @mdhanif-simformsolutions,

Thanks for reporting the issue. We've passed this request to our developer relations team, and they will start working on creating a tutorial for SwiftUI too (the example above is for our UIKit SDK).

In any case, SwiftUI's implementation is similar to the one in the link, the only place where it differs is the place where the encryption/decryption happens.

In our composer config, you can do the following (by reusing the code until `3. Encrypted Chat View Controller` in the tutorial - you don't need anything afterwards):
```swift
let composerConfig = ComposerConfig(adjustMessageOnSend: { message in
        encrypt(text: message, symmetricKey: symmetricKey)
}, adjustMessageOnRead: { message in
        decrypt(text: message, symmetricKey: symmetricKey)    
})

let utils = Utils(
      composerConfig: composerConfig
)
streamChat = StreamChat(chatClient: chatClient, utils: utils)
```
Note that it might be good idea to cache the encrypted / decrypted messages for better performance.

Hope this helps,
Martin

**Comment by mdhanif-simformsolutions** [comment]
Hi @martinmitrevski  Thanks for the update.
Just want to confirm, 
Does composer config automatically determines the users for which they need to decrypt the message ? Also it works for group chats as well correct ?

**Comment by martinmitrevski** [comment]
Hey @mdhanif-simformsolutions,

There's no distinction per users or type of chat - it works for all of them if you provide the logic in the config.

We don't have per-user configuration at the moment.

**Comment by martinmitrevski** [comment]
I'm closing this issue. In case of additional questions, feel free to reopen it or contact our support team.

**Comment by Developersimform** [comment]
Hey @martinmitrevski 
How can we decrypt messages on the channels list view?

I can see, we update symmetric key only when user goes to chat channel view,
So How decryption works on the channels list view?

And Do we have any example of channel list and chat channel view with encryption and decryption in swiftUI ?

**Comment by martinmitrevski** [comment]
Hey @Developersimform,

You can provide your own implementation for the channel list item, as described here: https://getstream.io/chat/docs/sdk/ios/swiftui/channel-list-components/helper-views/#changing-the-chat-channel-list-item. You will need to apply your decryption logic to the channel's `latestMessages` property, if you want to show a decrypted message from the channel list.

We don't have any examples for encryption and decryption, we only have the UIKit blog post linked above.
Best,
Martin

**Comment by Developersimform** [comment]
Hey @martinmitrevski 
Thank you for clarification.
So, 
How we know that to which user I am sending that message.

```
let composerConfig = ComposerConfig(adjustMessageOnSend: { message in
        encrypt(text: message, symmetricKey: symmetricKey)
}, adjustMessageOnRead: { message in
        decrypt(text: message, symmetricKey: symmetricKey)    
})

```

Here, I only get message as a string, So How can I know that for which user I need to decrypt message. ?
