### ISSUE TITLE
Can't access internal properties

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#151]
## What are you trying to achieve?
- I am redesigning the video attachment bubble view and transition animation for VideoPlayerView.
- For that, please help to expose these properties:
1. AttachmentTextView 
2. VideoPlayerView
3. MessageCachingUtils in Utils and its functions
4. VideoAttachmentsList
5. VideoAttachmentView
6. withUploadingStateIndicator View modifier

## GetStream Environment
**GetStream Chat version:** 4.19.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

We have now exposed all of the components on our `main` branch, except 3. MessageCachingUtils. This is our internal implementation that we would like to keep private. Just use `message.quotedMessage` instead.

Best, 
Martin
