### ISSUE TITLE
Kicked out of threads when channel has custom attachment

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#152]
You get repeatedly kicked out of threads in channels with messages containing custom attachments.

This is a follow-on issue to one I previously created: https://github.com/GetStream/stream-chat-swiftui/issues/144.

3 days ago, when I mentioned that ^ this issue was fixed for me, I was testing in the `DemoAppSwiftUI` target that comes in the Stream SwiftUI project. However, I found I was still getting kicked out of threads in our own app. I thought it must have been in our code (how we were using Stream), but then I had the idea to switch DemoAppSwiftUI to log into our team’s Stream app (loading our channels instead of the default Star Wars-themed sample app that the demo app logs into automatically), and I was then able to reproduce the issue in the DemoAppSwiftUI app! But only when pointing it to our organization’s Stream chat channel content.

The only notable difference I can think of between the chat content in the Star Wars test channels, and our team’s channels, is we have custom attachments. It looks like this navigation issue only occurs when you navigate into threads where the channel contains custom attachments. I cannot reproduce this issue in channels where there are zero custom attachments.

For reference, our Stream app ID is 1176001.

## What did you do?

I created a message that includes a custom attachment in a channel. Then I followed [the Stream SwiftUI tutorials](https://getstream.io/tutorials/swiftui-chat/) to create a simple app that uses `ChatChannelListView()` to show the messages.

## What did you expect to happen?

I expect to be able to navigate into threads without being kicked back out to the channel.

## What happened instead?

When I navigate into a thread, I get repeatedly kicked out of the thread, back to the channel.

In order to reproduce this issue, two things must be true:
1. The thread you navigate into should be in a channel that has a custom attachment.
2. You need to first navigate into the thread, then back into the channel, then into the thread again. It does not happen the 1st time you navigate into a thread, but happens every time after that/

## GetStream Environment
**GetStream Chat frameworks:** StreamChat (`4.19.0`), StreamChatSwiftUI (`main`)
**iOS version:** 15.5
**Swift version:** latest
**Xcode version:** Version 13.4.1 (13F100)
**Device:** iOS (reproduced on iPhone 13 Pro Simulator and physical iPhone 11 Pro)

## Additional context

Here’s a demo video showing the issue:

https://user-images.githubusercontent.com/144283/180888605-f884b68a-f0cc-4193-8d53-775af53b2fed.mov

I’ve invited @martinmitrevski to view the private project I’m demoing ^ here: https://github.com/earbudsdev/juststream. I would make it public, but I committed our Stream app’s API key to the project, to make it easier for you to quickly clone and run to reproduce the issue.

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks again for a very detailed analysis, we appreciate these reports a lot.

About the demo private project, I didn't get any invite, could you please check again? It shows "page not found" when I try to access the repo.

In any case, we will analyse this and get back to you when we have more info.

Best,
Martin

**Comment by moubry** [comment]
@martinmitrevski I’m so sorry — I neglected to actually send the invite once I created it. You should have access now.

**Comment by martinmitrevski** [comment]
thanks @moubry, I have access now and will look into this 👍

**Comment by martinmitrevski** [comment]
Hey @moubry,

I've looked at the sample project and the issue is fixed now on our `main` branch. Basically, it was another bug with SwiftUI's `NavigationLink`.

The only thing I've noticed is that for some songs in the "One word titles that 🤘" the scrolling offset is still not kept. In others, for example, in "Jazz Standard Essentials" the offset is always kept. 

Could this be a data issue with some songs' payload on your end? (couldn't notice anything strange in our SDK)

Looking forward to your feedback.

Best,
Martin

**Comment by moubry** [comment]
Thank you so much, @martinmitrevski. This issue is now fixed for us.

Re: the scrolling offset — I can see what you’re talking about, but I don’t know why it is behaving this way. As far as I can tell, all of the song attachments are structured the same — the only have a `song_id` attribute, which we’re rendering to the screen. I can’t figure out what is special about the “One word titles that 🤘” channel that would cause this issue. I’ll create a new issue if I ever figure that out.

Quick question: [In your solution](https://github.com/GetStream/stream-chat-swiftui/commit/1f00e5270f768d7f6b8e0f71b8b70ce94a10e195), you created `threadMessage` and `threadMessageShown`. I have noticed that when I subscribe to changes from these, they go from `nil` and `false` respectively → having values (like you would expect), but they do not return to their initial states when you tap "Back", returning to the channel. Would it be possible to update `threadMessageShown` so that it becomes `false` again when the user navigates back out of the thread? The reason I’m asking is we have code that needs to know whether someone is in a thread or not.

**Comment by martinmitrevski** [comment]
Hey @moubry,

Glad to hear that your issue was fixed. 

About your question: I've checked and these values are updated accordingly - the `threadMessageShown` is a boolean maintained by the `NavigationLink` and it updates to false when you go back to the channel. `threadMessage` follows along. 

However, listening to these values from the thread itself is not enough (they are both false for a thread, which can be true for a regular convo too). To check whether you are in a thread or the main convo, you can use `isMessageThread` from the view model.

Hope this helps for your checks.

**Comment by moubry** [comment]
Thanks for the feedback, @martinmitrevski. I greatly appreciate all your help.

I recorded another video — I hope these are helpful — at explaining what I’m seeing on my side in the JustStream sample app I created. I pushed [a commit](https://github.com/EarBudsDev/JustStream/commit/9f6f2f7f328bac0ec31b64ed8fcf8b9488015c63) for the code I’m demoing here:

https://user-images.githubusercontent.com/144283/181627509-115ad06c-97fb-4347-b9a0-4ec26484ea99.mov

I’m not sure if I’m using the chat view model correctly here. If I want to use `ChatChannelListView` is there any other way of observing changes to the chat channel view model’s thread-related properties?

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks for making the video. Your observations there are correct, the `make` methods are not reliable to do listening of events. 

The proper way would be to create your own wrapper around our channel view and listen to `onChange` callbacks. Here's a working example:

```swift
struct CustomChannelView<Factory: ViewFactory>: View {
    
    var viewFactory: Factory
    @StateObject var viewModel: ChatChannelViewModel
    @State var channelController: ChatChannelController
    var scrollToMessage: ChatMessage?
    
    var body: some View {
        ChatChannelView(
            viewFactory: viewFactory,
            viewModel: viewModel,
            channelController: channelController,
            messageController: nil
        )
        .onChange(of: viewModel.threadMessageShown) { newValue in
            print("==== messageThreadShown = \(newValue)")
        }
        .onChange(of: viewModel.threadMessage) { newValue in
            print("==== message thread = \(newValue)")
        }
    }
    
}

func makeChannelDestination() -> (ChannelSelectionInfo) -> CustomChannelView<CustomViewFactory> {
        { [unowned self] selectionInfo in
            let channelController = chatClient.channelController(
                for: selectionInfo.channel.cid,
                messageOrdering: .topToBottom
            )
            let channelViewModel = ViewModelsFactory.makeChannelViewModel(
                with: channelController,
                messageController: nil,
                scrollToMessage: nil
            )

            return CustomChannelView(
                viewFactory: self,
                viewModel: channelViewModel,
                channelController: channelController,
                scrollToMessage: selectionInfo.message
            )
        }
    }
``` 
I have this code locally, let me know if you want me to push it to your repo.

You only need to do this for the channel destination (not the thread), for this case. With this approach, you can listen to any publishers in our VM. Another approach would be to subclass our `ChatChannelViewModel` and directly listen to the changes there. 

Hope this helps. Let me know if you need additional support here. We probably need to document this better on our side.

Best,
Martin

**Comment by moubry** [comment]
Thank you so much, @martinmitrevski. I’ve given you write access to push to my repository. I’ve also committed your suggested change to the repo, and can confirm that everything works there. Additionally, I’ve applied this change to our main app, and everything seems to be working!

Thank you for the guidance. You are amazing.

**Comment by martinmitrevski** [comment]
Awesome, glad to hear that @moubry 🎉

**Comment by moubry** [comment]
I’m sorry for continuing to pile onto this one issue, @martinmitrevski — but I figured you would want to know:

There’s one code path I found where `threadMessage` and `threadMessageShown` are not set. When you long press on a message, then tap the “Thread Reply” action, then you navigate into thread, but `threadMessageShown` remains `false`, because it doesn’t follow the `NavigationLink` from the `ChatChannelView`.

**Comment by martinmitrevski** [comment]
@moubry, thanks for pointing this out. We've just fixed this too and it's available on our `main` branch.
