### ISSUE TITLE
Please expose GalleryView

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#154]
## What are you trying to achieve?
- I am giving custom UI support for a single attachment bubble.
- For preview, I need to open `GalleryView` from custom view.
- please help to expose `GalleryView`

## GetStream Environment
**GetStream Chat version:** 4.19.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

The `GalleryView` is now exposed on our `main` branch.

Best,
Martin
