### ISSUE TITLE
Unable to access internal properties

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#155]
## What are you trying to achieve?
- I am redesigning the whole message bubble. For that, please help to expose these properties:
1. GalleryView
2. horizontal in MessagePaddings
3. TopLeftView
4. MessagePinDetailsView
5. MessageRepliesView

**Comment by martinmitrevski** [comment]
Hello @ajay-simform, 

The views are exposed as public now.

Best,
Martin
