### ISSUE TITLE
Include fix from core SDK in latest release

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#157]
hey, we also noticed issues around messages failing to show from a push notification, looks like there was a fix merged a couple hours ago https://github.com/GetStream/stream-chat-swift/pull/2200

can you do a new release of the SwiftUI SDK so we can include that fix?

**Comment by martinmitrevski** [comment]
hey @AndrewSB,

Yes, that's already planned for tomorrow (or latest Wednesday, depending on how our regression testing goes).

Will update you on this issue.

**Comment by AndrewSB** [comment]
this looks like it was released. thanks! we'll test with it
