### ISSUE TITLE
Thumbnailed images display in low resolution

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swiftui#161]
## What did you do?
Share 5 images at once into chat

## What did you expect to happen?
Images should display in full resolution when being viewed in full screen

## What happened instead?
The 4 images that appear in the thumbnail preview in chat display in low res/are blurry when viewed full screen. The 5th image, that is not previewed in the thumbnail displays in full res

## GetStream Environment
**GetStream Chat version:** 4.19.0 (19)
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** ios 15.5
**Swift version:**
**Xcode version:**
**Device:** iPhone 11

**Comment by martinmitrevski** [comment]
Thanks for reporting this @jfru. We will look into it, and get back to you when we have an update.

**Comment by martinmitrevski** [comment]
@jfru this is now fixed and available on `main`.
