### ISSUE TITLE
Width of message composer changes on move to second line of text

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swiftui#162]
## What did you do?
See vid. The width of the composer changes when the cursor moves to the second line following on from a space on the first line.

## GetStream Environment
**GetStream Chat version:**

https://user-images.githubusercontent.com/17079221/182698822-fc2419e4-132a-4675-9e5f-b19a75019b46.MP4

**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by AndrewSB** [comment]
this has been fixed in the latest stream-chat-swiftui release
