### ISSUE TITLE
Make showing avatars configurable between DMs or groups

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#164]
hey! we're still maintaining this feature for ourselves, we'd like to make this configurable some how so we can remove this patch from our own fork

https://github.com/GetStream/stream-chat-swiftui/pull/142

**Comment by martinmitrevski** [comment]
Thanks @AndrewSB, we will see if we can make this without a breaking change.

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

This is now updated without a breaking change. You can pass an optional `showAvatarsInGroups` to control the visibility of the avatars:
```swift
let messageDisplayOptions = MessageDisplayOptions(
        showAvatars: false,
        showAvatarsInGroups: true
 )
```
Best,
Martin
