### ISSUE TITLE
Booted out from chat, intermittently when coming in from a notification

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#166]
we're not sure how to debug this, but often when entering the app through a notification, we enter the channel and are immediately removed from this

could you share some steps on how we can get better logging from this to try to isolate why we're getting pushed out of the thread? like where we should be putting a breakpoint, or anything of that sort

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

The zendesk ticket about this issue arrived to me, so let's proceed the discussion there: https://getstream.zendesk.com/agent/tickets/26093.

Best,
Martin
