### ISSUE TITLE
Turn off updates when app is in the background

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#170]
## What are you trying to achieve?

We're seeing some memory pressure where after backgrounding the app, it' still connected to stream, and re-drawing views. is it possible to pause those updates when the app is in the background?

## If possible, how can you achieve this currently?

doesn't seem possible. iirc, i was told a while ago that after 10s of being in the background, stream should stop receiving updates

## What would be the better way?

turning off updates (whether automatically, or through a manual call that we handle in our app delegate)

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, 

We actually have support for this. When you initialize the chat client, with a `ChatClientConfig`, there's a possibility to set `staysConnectedInBackground` to false. This is by default true, and tries to keep the connection alive up to 5 minutes.

I'm pasting here the code docs for further clarification:
```swift
/// If set to `true`, the `ChatClient` will try to stay connected while app is backgrounded.
    /// If set to `false`, websocket disconnects immediately when app is backgrounded.
    ///
    /// This flag aims to reduce unnecessary reconnections while quick app switches,
    /// like when a user just checks a notification or another app.
    /// `ChatClient` starts a background task to keep the connection alive,
    /// and disconnects when background task expires.
    /// `ChatClient` tries to stay connected while in background up to 5 minutes.
    /// Usually, disconnection occurs around 2-3 minutes.
    ///
    /// - Important: If you're using manual connection flow (`shouldConnectAutomatically` set to `false`), this flag is ineffective.
    /// You should handle connection manually when sending app to background
    /// or opening app from background.
    ///
    /// Default value is `true`
    public var staysConnectedInBackground = true
```
Hope this helps.

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

Any news about this one? Do you need additional support about it or we can close it?

Thanks, 
Martin

**Comment by AndrewSB** [comment]
nope! your explanation worked, thanks Martin!
