### ISSUE TITLE
Leading alignment for all messages

### ISSUE THREAD

**Issue by rpachecoaimonkey** [GetStream/stream-chat-swiftui#172]
## What are you trying to achieve?

Hello! I want to set alignment for leading to all messages in the chat UI (including messages of the current user). In UIKit I see how to do it, but not in SwiftUI, could you help me? Thanks a lot!

![image](https://user-images.githubusercontent.com/102691121/183940041-b7ac7cac-9a44-482c-9f59-77ed44281449.png)

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

You can do this by providing your own implementation of the message container view, by implementing the `makeMessageContainerView` in your custom `ViewFactory`. 

Here's an example how to do this:
```swift
func makeMessageContainerView(
        channel: ChatChannel,
        message: ChatMessage,
        width: CGFloat?,
        showsAllInfo: Bool,
        isInThread: Bool,
        scrolledId: Binding<String?>,
        quotedMessage: Binding<ChatMessage?>,
        onLongPress: @escaping (MessageDisplayInfo) -> Void,
        isLast: Bool
    ) -> some View {
        CustomMessageView(
            channel: channel,
            message: message,
            scrolledId: scrolledId
        )
    }
```

`CustomMessageView` would be your own implementation, with the UI you've shown above.

Hope this helps and let me know if you have additional questions.

Best,
Martin

**Comment by rpachecoaimonkey** [comment]
Thank you so much for your help!
