### ISSUE TITLE
Custom MessageRepliesView

### ISSUE THREAD

**Issue by wlopezvai** [GetStream/stream-chat-swiftui#177]
## What are you trying to achieve?

Hi, I'm trying change the design for MessageRepliesView, but I can implement it on the ViewFactory.

I'll appreciate your help regarding this case.

**Comment by martinmitrevski** [comment]
Hey @wlopezvai,

We have just exposed a possibility to customize the `MessageRepliesView` via the `ViewFactory`. This is already available on our `main` branch, so you can check it there. It will be released next week as part of our 4.21.0 release.
Here's an example usage:
```swift
    public func makeMessageRepliesView(
        channel: ChatChannel,
        message: ChatMessage,
        replyCount: Int
    ) -> some View {
        MessageRepliesView(
            factory: self,
            channel: channel,
            message: message,
            replyCount: replyCount
        )
    }
``` 
Best,
Martin
