### ISSUE TITLE
Occasional crash when scrolling in a thread

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#178]
Hey @martinmitrevski, i've noticed this crash that occasionally comes up when navigating into, and scrolling through a channel. i wasn't sure how to best share a crash log, since i caught it in the debugger so i've just navigated through the stack trace in a screen recording for you

https://user-images.githubusercontent.com/3814772/185594266-1b266132-7c79-406a-8da5-ac0c42a8ab57.mov

this is using stream-chat-swiftui @ https://github.com/GetStream/stream-chat-swiftui/commit/fd0f4ffb55d20110f8931fa9a330e017debc730a

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

Thanks for reporting this. We will analyse it and get back to you when we have more info.

Best, 
Martin

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

This is fixed and already available on our `main` branch. It will be included in our next release.

Best,
Martin
