### ISSUE TITLE
bug: scrolling jank on message input bar becoming first responder

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#18]
this video demonstrates: 

https://user-images.githubusercontent.com/3814772/152922782-35ee654c-91c8-41b9-bfe6-e5a09cf11873.mp4

i'm running `master` of this library on Version 13.2.1 (13C100) of Xcode

i'd love to get this fixed, currently evaluating stream vs some other options, this SwiftUI library is super expressive, but might just be missing some tiny bits of polish

**Comment by martinmitrevski** [comment]
Hi @AndrewSB, thanks for reporting the issue. 
We will have a look at this and provide a fix as soon as possible.

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, the bug is fixed now, and available on the `main` branch.
