### ISSUE TITLE
iMessage style drag to show date indicators

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#180]
## What are you trying to achieve?

Hey! we were wondering if it would be straightforward to add an iMessage style drag left to show date indicator gesture, and have the bubbles on the right side move over to show those indicators.

If it seems straightforward, we'd like to try it out in the iMessage demo inside StreamChatSwiftUITestsApp

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, 

Thanks for the suggestion. However, this is not part of our product roadmap, so we don't have plans to support it in our SDK. 

In any case, here's a possible approach how you can do it in your app:
- Create your custom `ChatChannelView`, with the `makeChannelDestination` method.
- Add a swipe gesture on the `MessageListView` and change the x-offset of this view  based on the gesture state. You can see an example of this in our `ChatChannelSwipeableListItem`. Also, you will need to update the state of your shared object that the message list is in this mode.
- Add your own implementation of the `MessageContainerView`, using the `makeMessageContainerView`, where you can extend the default view, by conditionally adding the time from the shared object's state that you've updated from the message list view. 

Let me know if this will work for you. Also, if you need something additionally exposed (that doesn't trigger a breaking change in our SDK), let us know.

Best,
Martin
