### ISSUE TITLE
Question about properties of composer view in Replies view

### ISSUE THREAD

**Issue by rpachecoaimonkey** [GetStream/stream-chat-swiftui#188]
## What are you trying to achieve?

Changed properties like background color, height, buttons, fonts, etc, of the composer view in the ReplyView

## If possible, how can you achieve this currently?

Explain what I need to configure properties of that composer similar of the ChatChannelView composer.

![image](https://user-images.githubusercontent.com/102691121/187935819-347d8ba8-66ab-460f-919f-7894e478caba.png)

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

Can you please provide more details what do you want to customize? 

Here are some customization options for the composer: https://getstream.io/chat/docs/sdk/ios/swiftui/chat-channel-components/message-composer/. It's the same one used both in the regular chat view and the threads. With the `makeComposerViewModifier` you can accomplish most of the customizations.

Additionally, you can customize the "Also send in channel" view with the `makeSendInChannelView`. 

If you need anything else, let us know and we'll see if it's possible exposing it.

Best,
Martin

**Comment by rpachecoaimonkey** [comment]
This answer was really helpful. Thank you much!
