### ISSUE TITLE
How to customize chat channel header back button?

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#19]
saw these docs: https://getstream.io/chat/docs/sdk/ios/swiftui/components/channel-header/

how do i change the leading navigation bar item, the "< Back" button?

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, 

Yes, that link shows how to customize the channel header. In general, the steps are:
- You need to create your custom `ToolbarContent`.
- In there, you need to define your own trailing `ToolbarItem`:

```swift
@Environment(\.presentationMode) var presentationMode

ToolbarItem(placement: .navigationBarLeading) {
            Button {
                presentationMode.wrappedValue.dismiss()
            } label: {
               Text("Custom back button")
            }
        }
```
- create your own view modifier returning the newly created custom `ToolbarContent`
- you need to implement the `makeChannelHeaderViewModifier` and return the view modifier in your custom `ViewFactory`.

Hope this helps. If you have some issues or you want additional help / support, we would be glad to help.

**Comment by AndrewSB** [comment]
that's actually what i tried earlier, looks like doing that doesn't actually replace the back chevron, it does show content on the left side of the navigation bar, but doesn't replace the button

<img width="1440" alt="Screen Shot 2022-02-09 at 11 35 57 PM" src="https://user-images.githubusercontent.com/3814772/153359446-54bb2525-7794-4bd4-b753-ac2de5f39874.png">

for reference, this is the spec i'm trying to match

<img width="580" alt="Screen Shot 2022-02-09 at 11 38 38 PM" src="https://user-images.githubusercontent.com/3814772/153359828-9feac5f1-dc30-45d4-9614-8bc9a79f655c.png">

**Comment by martinmitrevski** [comment]
@AndrewSB, the back button needs to be explicitly hidden (it always goes with the `Toolbar` for pushed views). Here's an example with your demo project:

```swift
struct CustomChannelModifier: ChatChannelHeaderViewModifier {

    var channel: ChatChannel

    @State var editShown = false
    
    @Environment(\.presentationMode) var presentationMode

    func body(content: Content) -> some View {
        content.toolbar {
            CustomChatChannelHeader(channel: channel) {
                editShown = true
            } onTapLeading: {
                presentationMode.wrappedValue.dismiss()
            }
        }
        .sheet(isPresented: $editShown) {
            Text("Edit View")
        }
        .navigationBarBackButtonHidden(true)
    }

}
```

**Comment by AndrewSB** [comment]
works like a charm -- it does disable the left edge swipe gesture for dismissals though. this is more of a general SwiftUI question, but how do i bring that back?

**Comment by martinmitrevski** [comment]
Bringing it back is possible with a workaround: https://stackoverflow.com/questions/59921239/hide-navigation-bar-without-losing-swipe-back-gesture-in-swiftui.
