### ISSUE TITLE
Option to start message list from top instead of bottom.

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swiftui#190]
## What are you trying to achieve?
Is it possible to start the list of messages from the top instead of from bottom. Currently if you send your first message it will show on the bottom of the screen but i want it to start from the top of the list and other messages should be added normally. 
Attached images for current and expected behaviour.

Current :- 
![currentmessage ](https://user-images.githubusercontent.com/63775307/188138010-3ca7bef1-93a8-43d9-a23d-96dcc9a60103.png)

Expected :- 
![message ui](https://user-images.githubusercontent.com/63775307/188138106-5d4bff75-9a48-4782-b43f-aa082dae9f2d.png)

## GetStream Environment
GetStream Chat version: 4.20.0
GetStream Chat frameworks:  StreamChat, StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hey @mdhanif-simformsolutions, 

We don't support starting message lists from the top in our product. Also, it's not something planned in our roadmap.

You can do this by yourself, by implementing your own version of the channel view, with the `makeChannelDestination` in the `ViewFactory`. 

In there, you will need to provide your own version of the `MessageList`. You can use the one from the SDK as a starting point, and modify it to suit your needs (e.g. the `flippedUpsideDown()` needs to be removed and potentially some other changes).

Hope this helps.
Martin

**Comment by mdhanif-simformsolutions** [comment]
Hi @martinmitrevski 
I already tried removing `flippedUpsideDown()` and it did what was expected by making the list starting from the top position instead of from bottom. But now what I am searching for is when I send a new message/receive a message it's get added on top of the list instead of adding next to the already added items. 
Any 

https://user-images.githubusercontent.com/63775307/188197123-3e3f666c-0caf-478a-af02-4ca3bbae7b85.mp4

suggestions what change should I do to make it perfect. 
Refer attached video for reference.

Thanks.

**Comment by mdhanif-simformsolutions** [comment]
Hello @martinmitrevski 
I got few solutions for this I can remove `.flippedUpsideDown()` and reverse my `messagesList` which is used in `MessageListView` which will have some changes for `scrollToBottomButton` and other views so eventually if i see the level of customisation it feels like I'll be needing to move a lot of files from here to there. Is there any other solution you can suggest/guide me with ?
