### ISSUE TITLE
Typing view is not custom

### ISSUE THREAD

**Issue by negna1** [GetStream/stream-chat-swiftui#191]
## What are you trying to achieve?
Typing view should become customized, Create function in DefaultViewFactory to become customized.

## If possible, how can you achieve this currently?
 Create function in DefaultViewFactory and add current view for that.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @negna1,

Thanks for creating the ticket. Just to confirm, are you referring to the `TypingIndicatorBottomView` that's displayed at the bottom of the message list when someone is typing?

Best,
Martin

**Comment by negna1** [comment]
Hello again , 
Yes , I am referring that view. 
Thanks

**Comment by martinmitrevski** [comment]
Hello @negna1, 

The possibility to customize the bottom typing indicator view is now available on our `main` branch.
Example usage:
```swift
    func makeTypingIndicatorBottomView(
        channel: ChatChannel,
        currentUserId: UserId?
    ) -> some View {
        let typingIndicatorString = channel.typingIndicatorString(currentUserId: currentUserId)
        return TypingIndicatorBottomView(typingIndicatorString: typingIndicatorString)
    }
```

Best,
Martin
