### ISSUE TITLE
Message list dates animation.

### ISSUE THREAD

**Issue by saidReclip** [GetStream/stream-chat-swiftui#192]
## What did you do?
I switched `dateIndicatorPlacement` to `.messageList`

## What did you expect to happen?
Scroll huge chat threads smoothly 

## What happened instead?
The animation is jerky when you get next page of messages with same date. 

The video recording attached.
https://user-images.githubusercontent.com/102264702/188494115-dfb7257a-a392-4d9c-8a54-1db06b3ce51a.mp4

**Comment by martinmitrevski** [comment]
Hey @saidReclip,

Thanks for reporting this. We will try to improve the animation and get back to you when we have an update.

Best,
Martin

**Comment by jfru** [comment]
Hi Martin, 
Just wanted to check in on the status here. It's not super high priority, but it does significantly improve the chat experience in Reclip.
Cheers,
Josh

**Comment by martinmitrevski** [comment]
Hey Josh, 

Yes, this is already planned internally. I can't provide exact timeframe, but hopefully it will be soon.

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @saidReclip, 

We have done some updates on the message list dates animation. This is already available on our `main` branch.

Looking forward to your feedback.
Best,
Martin

**Comment by martinmitrevski** [comment]
This is now available in 4.22.0.
