### ISSUE TITLE
Override LeadingComposerView but question about how use the default implementation of the default LeadingComposerView

### ISSUE THREAD

**Issue by rpachecoaimonkey** [GetStream/stream-chat-swiftui#195]
## What are you trying to achieve?

Override leading button in composer component that could call instant commands default view and present it.

My new implementation is this
```
    func makeLeadingComposerView(
        state: Binding<PickerTypeState>,
        channelConfig: ChannelConfig?
    ) -> some View {
        Button {
            print("tap on bolt button and is necessary call a method to show instantCommands default view")
        } label: {
            Image("bolt")
                .frame(width: 20, height: 20, alignment: .top)
                .foregroundColor(Color("gray500"))
        }
        .padding(.trailing, 3)
        .padding(.leading, 10)
        .padding(.bottom, 8)
    }

```

I want to show/present this instant commands view when user tapped in my custom leading composer view
![image](https://user-images.githubusercontent.com/102691121/188935405-f23ac17b-612f-4f7d-9aaa-f8ea1e1ca911.png)

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

You can do this by changing the `state` binding that's passed as a parameter in the `makeLeadingComposerView` method.

For your particular case, for the commands to be shown, the `state` needs to be changed to `.expanded(.instantCommands)`, so your implementation can toggle the state between `.expanded(.none)` and `.expanded(.instantCommands)`.

You can find an example on how we do this in our default implementation, in `PickerTypeButton`: https://github.com/GetStream/stream-chat-swiftui/blob/873fc1af8bffc9d5ee6f7dee973ae926380f97cb/Sources/StreamChatSwiftUI/ChatChannel/Composer/AttachmentPickerTypeView.swift#L120.

Hope this helps,
Martin

**Comment by rpachecoaimonkey** [comment]
Works perfect! Thank you so much for your help.
