### ISSUE TITLE
Differents presentations for same MessageListView between iPhone and iPad devices

### ISSUE THREAD

**Issue by rpachecoaimonkey** [GetStream/stream-chat-swiftui#197]
## What did you do?

We embed MessageListView inside a NavigationView to show on specific container in order to handle chat and replies.

## What did you expect to happen?

Located in chat view, we try to switch to reply view, and we expect to see the same view design of the messages view, and the capability to return to the chat view, all in the same container.

## What happened instead?

In iPhone, we are getting the expected behavior, but in an iPad device we are getting a split view, breaking our logic and expected presentation of MessageListView like iPhone devices. 

We found how to replicate the same view design of iPhone devices adding to NavigationView the viewModifier `.navigationViewStyle(.stack)`, but when we added it, messages are not been updated in realtime. For example, if we write a new message after click the send button, always is necessary refresh the MessageListView component to update view with the latest messages.

Reference images

- WIthout the `.navigationViewStyle(.stack)` modifier
![image](https://user-images.githubusercontent.com/102691121/189139044-b83c16c8-6e0b-4c74-b0b4-cfb7fa9f4ee7.png)

- With the `.navigationViewStyle(.stack)` modifier, but with messagesListView auto update broken
![image](https://user-images.githubusercontent.com/102691121/189139323-fb5c0b75-7cb7-43d6-90ca-306e071bfa4b.png)

## Our question
What will be the best way to implement MessageListView with replies in an iPad device to see the same presentation of iPhone devices?

## GetStream Environment
**GetStream Chat version: *4.21.0*
**GetStream Chat frameworks: *StreamChat, StreamChatSwiftUI*
**iOS version: *15.6.1*
**Swift version: *5*
**Xcode version: *13.4.1*
**Device: *iPhone 11 64GB*

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

We will expose a config in our SDK to allow `.stack` support for iPads as well. We will let you know when this is available on our `main` branch.

Let's see if that will solve your issues. About the two cases and their issues, it depends on how are you integrating the `ChatChannelView`. In the first case, you probably need to set the maxWidth to `.infinity` for the view to stretch. In the second, maybe some unexpected view redrawing is causing some stale state?

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

We have exposed a configuration for this, which is now available on our `main` branch. Basically, you can disable the split mode on iPads, with the following code:
```swift
let utils = Utils(
    messageListConfig: MessageListConfig(iPadSplitViewEnabled: false)
)
let streamChat = StreamChat(chatClient: chatClient, utils: utils)
```
This should solve your issues, unless you are doing some custom implementation for the layout of the `ChatChannelView`.

Looking forward to your feedback.

Best,
Martin
