### ISSUE TITLE
Unable to override makePhotoAttachmentPickerView

### ISSUE THREAD

**Issue by Dzondzula** [GetStream/stream-chat-swiftui#199]
AttachmentTypeContainer is redundant in my app so I have tried to copy internal elements in my CustomViewFactory file and override  `makePhotoAttachmentPickerView` . Overriding `makeAttachmentSourcePickerView` and `makeCustomAttachmentPreviewView` passed normally.

```
func makePhotoAttachmentPickerView(
        assets: PHFetchResultCollection,
        onAssetTap: @escaping (AddedAsset) -> Void,
        isAssetSelected: @escaping (String) -> Bool
    ) -> some View {
        
            PhotoAttachmentPickerVieww(
                assets: assets,
                onImageTap: onAssetTap,
                imageSelected: isAssetSelected
            )
        
    }
```
To make this PhotoAttachmentPickerVieww (2w) I copied all neccessery internal structs. I have also tried to place EmptyView() but that did not override `makePhotoAttachmentPickerView` either. 

Xcode 13.4
iOS 15

**Comment by martinmitrevski** [comment]
Hey @Dzondzula,

I've tried this, and it's working correctly. For example, I've added this code in a custom factory:
```swift
func makePhotoAttachmentPickerView(
        assets: PHFetchResultCollection,
        onAssetTap: @escaping (AddedAsset) -> Void,
        isAssetSelected: @escaping (String) -> Bool
) -> some View {
        Text("This is a where the view should be displayed")
            .frame(maxHeight: .infinity)
}
```
And the result is this:
![Simulator Screen Shot - iPhone 12 - 2022-09-13 at 15 46 02](https://user-images.githubusercontent.com/2971717/189918230-72f62c1c-4e5e-4cd0-9043-72786b8f5a98.png)

Maybe try deleting derived data/cleaning the project and make sure the method is declared inside your view factory.

Hope this helps,
Martin

**Comment by martinmitrevski** [comment]
@Dzondzula, yes, that makes sense. It's now exposed on our `main` branch, just update your package.

**Comment by Dzondzula** [comment]
I have just figured that `PHFetchResultCollection` also needs to be accessible to make `PhotoAttachmentPickerView` work now.
