### ISSUE TITLE
Leaved channel still show up in the thread list

### ISSUE THREAD

**Issue by saidReclip** [GetStream/stream-chat-swiftui#200]
## What did you do?
Left a channel

## What did you expect to happen?
Not to see it in the inbox

## What happened instead?
Still showing up in some cases. Hard to say what is the reason.

We are filtering channels with no membership but no result.
```
        let channelListController = chatClient.channelListController(
            query: ChannelListQuery(
                filter: .containMembers(userIds: [userId.rawValue]),
                pageSize: ChatMaxRecentsCount
            )) { channel in
                channel.membership != nil
            }

```

**Comment by martinmitrevski** [comment]
Hey @saidReclip, 

The query itself seems correct, so the issue is most likely somewhere in the UI layer. 

Can you please check your channel identifier (as far as I remember you're using a custom one)? Also, you can try logging the received channels in `ChatChannelListViewModel` to see if the data is correct. We would need some more details in order to analyse this. 

Have you tried reproducing this in our demo app? 

Looking forward to your feedback.

**Comment by martinmitrevski** [comment]
Additionally, you can try updating the filter to: 
```swift
channel.members.contains(userId)
```

**Comment by saidReclip** [comment]
Hi @martinmitrevski 
I noticed that in ChatChannelListViewModel.swift:219 on didChangeChannels delegate we receive controller with channels without membership. How can I filter out this channels there? Or should you do it on your side? 
I could not repro it on stream demo app but it is reproducing in our app when user leave a channel.

**Comment by martinmitrevski** [comment]
Hey @saidReclip,

This sounds like an issue when creating the filter for the controller. Can you try with the default one from the SDK in your app, if you still have the same behaviour? It will help troubleshooting this.

**Comment by saidReclip** [comment]
We are using the default one from ViewModelsFactory.makeChannelListViewModel()

**Comment by martinmitrevski** [comment]
I meant the default `ChatChannelListController`, the view model doesn't do much, just observes the values from the channel list controller.

**Comment by saidReclip** [comment]
When we create this view model we do not pass `ChatChannelListController` there and it creates default `ChatChannelListController` inside view model.

**Comment by saidReclip** [comment]
Even if I pass `ChatChannelListController` with a membership filtration I still receive wrong value from `didChangeChannels` delegate.

**Comment by martinmitrevski** [comment]
@saidReclip, can you please try your configuration in our demo app? Basically, you need to change the `apiKeyString` in the `DemoUser`, as well as one `id` / `token` pair for a user that reproduces the issue in your app.
This will help us figure out if some specific configuration triggers the bug (which will be sth on our side), or certain interaction in your app is causing this.

**Comment by saidReclip** [comment]
Hi @martinmitrevski. 
Seems like adding "RemoveOwnChannelMembership" right to "user" role fixed the issue.
