### ISSUE TITLE
Externally delivered notifications don't persist if device is locked on ChatThreadView

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#204]
We've had this issue for a while: if a device is locked while a `ChatThreadView` is in the foreground, all the notifications show up for just a moment before being cleared.
It only happens if the active view is the `ChatThreadView`. we haven't reproduced this issue when the device is locked with any other screen - in those cases, the notifications persist

If you think this isn't caused by the SDK, could you link me to anything that might be dealing with notifications while the ChatThreadView is active? maybe this is caused by the lower level SDK?

## GetStream Environment
**GetStream Chat version:** many, goes back pretty far and still repros on `main`
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** tested on 15

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

We can't reproduce this in our default `ChatChannelView` inside the SDK. To help troubleshooting, can you put a breakpoint in our `ChatChannelViewModel` at line 293 and check if `channelController.markRead()` is called? Might be interesting to see if/who calls this method. Also, does this happen only immediately after you lock the phone or always when you lock it from that screen?

Maybe you can also try with turning off background updates as discussed here: https://github.com/GetStream/stream-chat-swiftui/issues/170.

**Comment by AndrewSB** [comment]
with the default config (`staysConnectedInBackground` true), `channelController.markRead()` is not called on lock/background/anything, it only seems to get called when the first navigating into the thread

exact same behavior on that with that background updates flag set to false.

it doesn't even get called when the phone is unlocked, only when message index 0 is appearing/disappearing while scrolling does it get called a second time

are there any other functions you can think of that may be causing the notification clearing to happen? maybe i can put a breakpoint in the low level SDK, if there are any calls to clear notifications in there?

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, 

I've checked with the low-level client team and we're not doing anything regarding clearing notifications / reseting the badge count from our SDK - this is responsibility of the integrating apps.

I've seen some usages of `UIApplication.shared.applicationIconBadgeNumber` in your app, so you might want to put a breakpoint there and see what triggers this.

**Comment by AndrewSB** [comment]
was related to OneSignal, you were right. thanks @martinmitrevski
