### ISSUE TITLE
Access to modify InputTextView's maximumHeight parameter

### ISSUE THREAD

**Issue by rpachecoaimonkey** [GetStream/stream-chat-swiftui#209]
## What are you trying to achieve?

Change the _maximumHeight_ parameter of the class **InputTextView**

## If possible, how can you achieve this currently?

In the StreamChatSwiftUI, inside the **InputTextView** file, in the line 14 of the struct _TextSizeConstants_, change _maximumHeight_ constant for a variable, and allow initiliaze this using the composerConfig as _minThreshold_ and _minimumHeight_ parameters

## What would be the better way?

Change maximumHeight using the composer config

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
hey @rpachecoaimonkey,

Thanks for the suggestion, that makes sense. We've made this available on our `main` branch via the composer config, as you've suggested. 

The name of the property is `inputViewMaxHeight`.

Best,
Martin

**Comment by rpachecoaimonkey** [comment]
Perfect, thank you so much @martinmitrevski for you help
