### ISSUE TITLE
ChatChannelView doesn't scroll to selected message

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#210]
## What did you do?
- Create `ChatMessageSearchController`
- search old/previous message from the channel
- go to ChatChannelView by giving selected message to `scrollToMessage`

## What did you expect to happen?
- The messageList should scroll to particular message. No matter if it needs pagination or something.

## What happened instead?
- The message doesn't scroll to the selected message index

## GetStream Environment
**GetStream Chat version:** 4.22.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** Xcode-14
**Device:** iPhone 14

**Comment by davitykale** [comment]
Hey @martinmitrevski -- any updates here? Would it be possible to link to the specific issue where this is being tracked in the `stream-chat-swift` repo?

**Comment by martinmitrevski** [comment]
Hey @davitykale,

The team is currently working on this. It's a bigger effort, that we expect to be finished this quarter (if all goes well). 

We have this task internally in our ticketing system, and there's a discussion related here: https://github.com/GetStream/stream-chat-swift/discussions/1764.

As soon as we have info, we will update this ticket too.

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,

Could you please provide me with an update on the current status of this issue?
Thank you.

**Comment by martinmitrevski** [comment]
Hi @ajay-simform,

This is only available in the UIKit SDK for now. At the moment we have other higher priorities, so for SwiftUI it will come most likely in Q3.

Best, Martin

**Comment by martinmitrevski** [comment]
Hi,

This one is now available in our `main` branch and it will come in the next release, most likely later this week.
