### ISSUE TITLE
Nuke ui fetch failing

### ISSUE THREAD

**Issue by smquoori** [GetStream/stream-chat-swiftui#211]
## What did you do?
added "https://github.com/getstream/stream-chat-swiftui" via package manager

## What happened instead?
As this package has internal dependency on NukeUI, we are getting error:
Failed to fetch "https://github.com/kean/NukeUI"

`error project: Error while fetching remote repositoryhttps://github.com/kean/NukeUI.git: The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.
`
## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:*iOS 15.5*
**Swift version:*swift 5.3*
**Xcode version:*14.0.0*
**Device:*iPhone 11*

**Comment by smquoori** [comment]
Reached out author of NukeUI, for now he has brought it back live on git, but it would be nice if we remove the dependency in near future.

**Comment by martinmitrevski** [comment]
Hey @smquoori,

Thanks for notifying us, it must've been a recent change. NukeUI is now part of Nuke, starting from version 11. 

We already have a ticket to migrate to this version: https://github.com/GetStream/stream-chat-swiftui/issues/183.

We will bump the priority on that one to avoid issues like this, so please track it for status updates.

Best,
Martin
