### ISSUE TITLE
Would it be possible to expose the BubbleBackgroundShape?

### ISSUE THREAD

**Issue by cyrilzakka** [GetStream/stream-chat-swiftui#212]
## What are you trying to achieve?
Reshape the message bubble to make it more iMessage-like.

## GetStream Environment
**GetStream Chat version:** 4.22
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16
**Swift version:** 5.x
**Xcode version:** 14.x
**Device:** 14 Pro

## Additional context
Hello, I'm trying to reshape the `BubbleBackgroundShape` to make it more iMessage like, which means I have to implement: 
`MessageBubbleModifier` from scratch. Is there a better alternative?

**Comment by martinmitrevski** [comment]
Hey @cyrilzakka, 

At the moment, it's only possible to replace the whole modifier. The reason for this is that there are many variations of how the messages can look like, and we will end up with many generics if we try to support all cases.

However, we're exposing all the sub-components, so you don't have to build it from scratch. Additionally, we've moved some boilerplate methods (for background and rounded corners) as a chat message extension, so it's simpler now to focus only on your custom modifiers.

Hope this helps,
Martin
