### ISSUE TITLE
Erratic channel list filtering behavior

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#217]
I’m trying to navigate the user into a filtered channel list view, but I’m having a hard time getting it to work.

## What did you do?

I created several channels in Stream setting a custom extra data field `group_id`.

I used the query filter feature of Stream’s `ChannelListController` to filter the `ChatChannelListView` based on the user’s group selection.

## What did you expect to happen?

I expected it to reliably filter the group list.

## What happened instead?

The filtering seems to be erratic. I can’t tell if this is a [controller](https://github.com/GetStream/stream-chat-swift/issues/2329), view model, or view issue. Recreating view models seems to yield differently filtering results every time I do it, like there’s some global chat client state that affects filtering results.

## GetStream Environment
**GetStream Chat version:** `main`
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** latest
**Xcode version:** Version 14.0.1 (14A400)
**Device:** iPhone 11 Pro

## Additional context

[I created a sample project that demonstrates my problem.](https://github.com/EarBudsDev/JustStream/commit/b146d6bf0f5d4e446a1a2b93bdd57def25a3baab) The same project contains secrets, so it’s private. I’ve shared it with @martinmitrevski previously, but I can also share with whomever triages this issue.

Here is the core code from the sample project:

```swift
import SwiftUI
import StreamChat
import StreamChatSwiftUI

@main
struct JustStreamApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        WindowGroup {
            GroupsListView()
        }
    }
}

struct GroupsListView: View {
    @State var selectedGroup: UserGroup?
    var body: some View {
        NavigationView {
            List(UserGroup.examples) { group in
                ZStack {
                    NavigationLink(tag: group, selection: $selectedGroup) {
                        if let group = selectedGroup {
                            StreamView(group: group)
                        } else {
                            Text("Please select a group to view its channels.")
                        }

                    } label: {
                        Text(group.name)
                    }
                }
            }
        }
    }
}

struct StreamView: View {
    @Injected(\.chatClient) public var chatClient: ChatClient

    var group: UserGroup
    var channelListViewModel: ChatChannelListViewModel?

    init(group: UserGroup) {
        self.group = group
        let controller = chatClient.channelListController(
            query: .init(filter: .equal("group_id", to: group.id))
        )
        self.channelListViewModel = ChatChannelListViewModel(
            channelListController: controller,
            selectedChannelId: nil
        )
    }

    var body: some View {
        ChatChannelListView(
            viewFactory: CustomViewFactory.shared,
            viewModel: channelListViewModel
        )
    }
}

struct UserGroup: Codable, Identifiable, Hashable, Equatable {
    let id: Int
    let name: String

    static var examples: [UserGroup] {
        return [
            UserGroup(id: 1, name: "Group 1"),
            UserGroup(id: 2, name: "Group 2")
        ]
    }
}
```

Which is creating this query:

```
Query items:
- payload={
  "filter_conditions" : {
    "group_id" : {
      "$eq" : 1
    }
  },
  "message_limit" : 25,
  "watch" : true,
  "member_limit" : 30,
  "limit" : 20
}
```

I turned on `LogConfig.level = .debug` and based on the logs I’m seeing, it looks like the Stream API is returning the correct number of channels for this query, but more channels than expected are being shown in the view, which might be a local client database issue?

Here’s a video that demonstrates the issues I’m seeing when I run [this code](https://github.com/EarBudsDev/JustStream/commit/b146d6bf0f5d4e446a1a2b93bdd57def25a3baab) (sound on):

https://user-images.githubusercontent.com/144283/195209059-0b0b8c0d-ebc0-4823-818a-db04e9fcb496.mov

In this video you see the following channels in Stream:

- Group 1
  - [Sean Earbuds Channel](https://dashboard.getstream.io/app/1203633/chat/explorer?path=channels,channel~messaging:cl93acuh40001f24lusheylp3)
- Group 2
  - [Sean Test](https://dashboard.getstream.io/app/1203633/chat/explorer?path=channels,channel~messaging:cl936mbrx0000f24lv4d20lw5)
  - [Top Secret (You Should Not See This)](https://dashboard.getstream.io/app/1203633/chat/explorer?path=channels,channel~messaging:cl93askzy0002f24lqth4kud7) — Note: This one is a misnomer. I should expect to see it, since I created it, but it has zero members, so nobody else should be able to see it, except me.

Over the course of the video I present a filtered channel list multiple times, and I get a different filter result every time:

1. Group 1: Shows the 1 correct channel ✅ but then immediately disappears it ❌.
2. Group 2: Shows the 2 correct channels ✅ but then disappears ONE of them ❌.
3. Group 1: Shows the 1 correct channel ✅.
4. Group 2: Shows all three channels ❌. (Should only show 2 of these).
5. Group 1: Shows two channels: one of them is correct, one of them is wrong ❌.

Note: There are lots of channels (over 50) in this Stream app. Only the three channels I listed above have a `group_id` set on them, so it’s definitely filtering down to the three channels that have a `group_id` on it, but it doesn’t seem to be using the actual value of `group_id` (a number/integer) deterministically.

Here's an example of what one of these channels looks like in Stream dashboard:

<img width="1092" alt="Screen Shot 2022-10-11 at 5 28 35 PM" src="https://user-images.githubusercontent.com/144283/195210069-22668c8b-0c34-4930-8588-3ec238acf120.png">

Thank you for any help here!

**Comment by moubry** [comment]
### Minor Update

In our Stream app, I created a couple more channels for testing that have string values for `group_id` instead of integer values (so there’s a total of 5 channels that have the extra data attribute of `group_id`):
- Channel: [Tacos](https://dashboard.getstream.io/app/1203633/chat/explorer?path=channels,channel~messaging:cl94th5od0000494loa21yrh9) — `group_id: "tacos"`
- Channel: [Nachos](https://dashboard.getstream.io/app/1203633/chat/explorer?path=channels,channel~messaging:cl94yifdc0000z84lm3xfkvnn) — `group_id: "nachos"`

[I pushed a commit to the sample project](https://github.com/EarBudsDev/JustStream/commit/24bc13ae767eada7f256a927c2b0d1adc81dc9d5) that only includes these groups.

I wanted to see if filtering would perform better when filtering on extra data attributes with strings as values, but the results were the same — it would get confused and merge the results of the two groups:

![IMG_0268 2](https://user-images.githubusercontent.com/144283/195229112-ec11932e-c4af-4eff-80cc-598401556265.jpg)

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks again for this very detailed analysis and the sample project - it really makes our job a lot easier. 🥇 

As for the issue, the inconsistency happens because you're missing a filter that needs to match the query. So basically, if you add the following, the issue should be solved:
```
self.channelListViewModel = ChatChannelListViewModel(
            channelListController: chatClient.channelListController(
                query: .init(filter: .equal("group_id", to: group.id)),
                filter: { chatChannel in
                    chatChannel.extraData["group_id"]?.stringValue == group.id
                }
            ),
            selectedChannelId: nil
        )
```
We're aware that it's not ideal to specify both the query and filter (and they both need to be matching), but unifying them would be very complex and expensive operation. Please check the two notes in our docs for more details about this: https://getstream.io/chat/docs/sdk/ios/uikit/controllers/channels/#2-create-a-controller.

Hope this solves your issue.
Best,
Martin

**Comment by moubry** [comment]
Thank you so much, @martinmitrevski.

[I've applied this fix](https://github.com/EarBudsDev/JustStream/commit/dde64ec38fff3afc44387eb360efaf50754d6e0d) and my everything looks good on our end.

Note: I noticed that I did have to delete the app from my device before this fix worked. You can reproduce this yourself in the sample app by removing the fix, then running the app, navigating into both groups, then adding the fix back. You'll notice that even with the fix, it still shows all groups. Presumably, this is because something is cached in the local database?

I noticed the notes in the docs, but it was not obvious to me that you are required to set both the query filter and filter closure in order for it to work. Does this mean I should also be creating a controller delegate that conforms to `ChatChannelListControllerDelegate` (step 3)?

As always, your help is invaluable.

**Comment by martinmitrevski** [comment]
Hey @moubry, great, glad to hear that your issue was fixed. 

About the first point, yes, there's some caching going on in the local database - the channels were already linked with the old query and saved in the DB. Again, this is not ideal, but prevents us from some expensive operations with the db.

About the docs, we've already had similar reports, so it's obvious that we need to improve them here. We will pick that up internally with our dev rel team.

About the `ChatChannelListControllerDelegate`, no, you don't need to set it, since you're using our view model that already does that. If you want to create your own custom presentation layer and want to listen to channel list updates, then it makes sense to set the delegate.

Hope this helps.
Best,
Martin

**Comment by moubry** [comment]
Thank you!
