### ISSUE TITLE
Building time increased with view customizations using the ViewFactory

### ISSUE THREAD

**Issue by wlopezvai** [GetStream/stream-chat-swiftui#218]
## What did you do?
We currently have about 20 implementations of the ViewFactory and the build time has increased exponentially. In the documentation (https://getstream.io/chat/docs/sdk/ios/swiftui/view-customizations/) you specified that there is a way to improve those build times. Could you please update the docs with an example to create the type alias to an associatedType?

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @wlopezvai,

For example, let's have a look at one of the first methods in the `ViewFactory`, for creating the no channels view:
```swift
associatedtype NoChannels: View
/// Creates the view that is displayed when there are no channels available.
func makeNoChannelsView() -> NoChannels
``` 
Here, the associated type is `NoChannels`. Now, let's say your custom implementation looks like this:
```swift
public func makeNoChannelsView() -> CustomNoChannelsView {
    CustomNoChannelsView()
}
```
In order to improve the build time, you would need to specify the associated type with a typealias, like this:
```swift
typealias NoChannels = CustomNoChannelsView
```
This will help the compiler to figure out faster what's the type that you're going to provide for the `NoChannels` view.

Hope this helps. We will update the docs to be more clear, however the change would be visible live on the website with the next release.

Best,
Martin

**Comment by wlopezvai** [comment]
Thank you @martinmitrevski, the build time has improved.

I assumed that after we declare the Typealias, now that will be the return type for the function. Am I correct?

`typealias NoChannels = EmptyConversationList
    func makeNoChannelsView(
    ) -> NoChannels {
        NoChannels(action: {
            self.presentSearchForUserView()
        })
    }`

Thanks again,

Best,
William

**Comment by martinmitrevski** [comment]
Hey @wlopezvai, 

Cool, glad to hear that. 

I think it doesn't make any difference, it's important that the connection between them is done with the typealias.

In our examples, we use the custom type as a return type, but it should also improve the build time the other way..

Best,
Martin

**Comment by ylai-msrl** [comment]
For anyone who need an example, just change the custom viewFactory function like this

```
typealias ImageAttachmentViewType = CustomImageAttachmentContainer<ChatViewFactory>
    func makeImageAttachmentView(
        for message: ChatMessage,
        isFirst: Bool,
        availableWidth: CGFloat,
        scrolledId: Binding<String?>
    ) -> CustomImageAttachmentContainer < ChatViewFactory > {
        CustomImageAttachmentContainer(
            factory: self,
            message: message,
            width: availableWidth,
            isFirst: isFirst,
            scrolledId: scrolledId
        )
    }
```
