### ISSUE TITLE
CommandsContainerView should scroll if we have multiple commands.

### ISSUE THREAD

**Issue by parth-simformsolutions** [GetStream/stream-chat-swiftui#221]
## What did you do?
- Added multiple custom command using `CommandsConfig`.

## What did you expect to happen?
- it should scroll if we have multiple commands.
- expecting : - `instantCommands` foreach should be inside the `ScrollView` to see all the commands.

## What happened instead?
- The `CommandsContainerView` does not scroll.

## GetStream Environment
**GetStream Chat version: 4.22.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 16.0
**Swift version: 5
**Xcode version: Xcode-14
**Device: iPhone X

## Additional context
<img width="1112" alt="Screenshot 2022-10-18 at 12 00 05 PM" src="https://user-images.githubusercontent.com/74890630/196352824-50db1bba-06d2-4b3b-bf79-2270b5e192a3.png">

**Comment by martinmitrevski** [comment]
Hey @parth-simformsolutions,

Thanks for reporting the issue. This is now implemented and available on our `main` branch, and it will be included in the next release.

Best,
Martin

**Comment by parth-simformsolutions** [comment]
Thanks @martinmitrevski  
Any idea when we can expect next release? 
Thanks
