### ISSUE TITLE
Possibility to complete hidden of TabBar

### ISSUE THREAD

**Issue by rpachecoaimonkey** [GetStream/stream-chat-swiftui#222]
## What are you trying to achieve?

 Hide the TabBar of StreamChatSwiftUI permanently. Right now, I am using `makeChannelListStickyFooterView`, and this presents the default tabbar but I want to use my custom tabbar. In my case, it is not a tabbar, is a view.

## If possible, how can you achieve this currently?

Adding a variable in ChatChannelListView constructor to allow show or not the tabbar

## What would be the better way?

Add a method in the factory to hide it

**GetStream Chat version:4.22.0
**GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
**iOS version:16.0
**Swift version:5.7
**Xcode version:14.0
**Device:iPhone 14 Pro

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

The `makeChannelListStickyFooterView` is already a view, not a tabbar (it's part of a `VStack` in `ChatChannelListContentView`). 

The TabBar functionality is available only if your wrap the `ChatChannelListView` in a `TabView`.

Can you please provide more details about your issue (and maybe sample code)?

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @rpachecoaimonkey,

Thanks for providing the sample code. Now, I understand what's the issue. 

We've exposed an additional `handleTabBarVisibility` parameter when creating the `ChatChannelListView`. By default, this value is true and it will have the current behaviour. You can set it to false, and it should solve your issue.

This is available on our `main` branch and it will be included in our next release.

Looking forward to your feedback.

**Comment by rpachecoaimonkey** [comment]
Thank you so much for the help @martinmitrevski
