### ISSUE TITLE
DefaultChannelListHeaderModifier access level

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#228]
## What did you do?

I tried to create an instance of `DefaultChannelListHeaderModifier`.

## What did you expect to happen?

I expected it to be able to use this modifier, because it’s declared as `public` in StreamChatSwiftUI.

## What happened instead?

Xcode creates a compiler error saying:

```
'DefaultChannelListHeaderModifier' initializer is inaccessible due to 'internal' protection level`
```

I’m not familiar enough with the eccentricities of Swift’s access level behavior to know why the compiler thinks it's internal when it clearly is public in the version of StreamChatSwiftUI that I'm using. When I right-click to navigate to the definition of the struct, I can see it's public. It seems like maybe the memberwise init needs to be explicitly declared as public?

## GetStream Environment
**GetStream Chat version:** `main`
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** latest
**Xcode version:** Version 14.1 (14B47b)

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks for reporting. Yes, that's right - the init needs to be explicitly declared as public. I've fixed this and it's available now on our `main` branch.

Best,
Martin
