### ISSUE TITLE
Renaming channel clears custom metadata

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#232]
## What did you do?

Renamed a channel using the UI provided by `ChatChannelListView`.

1. Created a new channel.
2. Set custom metadata on it. Confirmed it's visible in Stream dashboard.
1. Swiped on a channel in the channel list view.
3. Tapped the ellipsis button.
4. Tapped on "View info".
5. Renamed the channel.
6. Tapped the checkmark in the name field to confirm the rename.
7. Went to the Stream dashboard. Custom metadata is missing.

For reference/completeness, this is the code I'm using on the backend to set the extra data that is being cleared:

```go
response, err := s.client.CreateChannel(ctx, cType, cID, userID, &stream.ChannelRequest{
	Members: users,
	ExtraData: map[string]interface{}{
		"name": name,
		"group_id": groupID,
	},
})
```

Specifically, it’s the `group_id` that is being cleared.

## What did you expect to happen?

I expect any extra data I set on the channel to be maintained if the user performs any kind of channel update through any of the Stream-provided UIs.

## What happened instead?

The custom metadata (extra data) field I’m setting `group_id` disappeared from the Stream Dashboard (Chat Messaging Explorer).

## GetStream Environment
**GetStream Chat version:** 4.24.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** latest
**Swift version:** latest
**Xcode version:** latest
**Device:** iPhone 14 Pro

## Additional context

Here’s a screenshot of a channel before renaming: 
<img width="1716" alt="Screen Shot 2022-11-17 at 12 39 12 PM" src="https://user-images.githubusercontent.com/144283/202530904-07212497-2d86-47a5-98b3-105d0e224d7c.png">

After renaming the group:

<img width="1719" alt="Screen Shot 2022-11-17 at 12 39 43 PM" src="https://user-images.githubusercontent.com/144283/202530914-a6702350-acd1-4bf2-ab29-0e86904bad73.png">

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks for reporting. This was indeed a bug in that screen. 

We've provided a fix and it's available on our `main` branch: https://github.com/GetStream/stream-chat-swiftui/commit/adf237a9a471e3af51a823a5cc034600e870401f.

Looking forward to your feedback.

Best,
Martin

**Comment by moubry** [comment]
I’ve tested the fix, and everything looks great.

Thank you for the extremely fast turn around!
