### ISSUE TITLE
Swipe actions view incorrectly appear navigating backwards

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#233]
## What did you do?

1. I embedded the `ChatChannelListView` in a `NavigationView`.
2. Navigated forwards into a channel list view.
3. Navigated backwards out of the channel list view by dragging on the leading edge of the screen. 

## What did you expect to happen?

I expected to navigate backwards without the LeadingSwipeActionsView appearing in the channel list item.

## What happened instead?

The LeadingSwipeActionsView incorrectly appears as I'm navigating backwards.

## GetStream Environment
**GetStream Chat version:** 4.24.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** latest
**Swift version:** latest
**Xcode version:** latest
**Device:** iPhone 11 Pro

## Additional context

Here’s a video that better demonstrates the issue:

https://user-images.githubusercontent.com/144283/202545660-dbe9518a-1f18-474e-86b4-f932107f0442.mov

Demonstrating this issue [on this commit](https://github.com/EarBudsDev/JustStream/commit/d50091b6f61dad9508b6d5c41a0ed83d153c2bd3) of the private project that @martinmitrevski has access to see.

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks for reporting this. It's now fixed and available on our `main` branch.

Best,
Martin

**Comment by moubry** [comment]
Everything looks good now! Thank you so much.
