### ISSUE TITLE
Disable channel actions based on permissions

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#234]
## What are you trying to achieve?

I would like to prevent users from seeing UI for modifying channels if they do not have permission to do so.

Currently, you can swipe on a channel in the channel list, and perform actions:
- Rename channel: This silently fails if the user is a member, but not an owner of the channel.
- Delete channel: This fails with an alert saying "Something went wrong."

## If possible, how can you achieve this currently?

As far as I know, the only way to achieve this would be to provide a custom swipe view and re-implement these features?

## What would be the better way?

Ideally, the UI framework knows whether the user can perform an action, and prevents the user from doing so if they cannot.

## GetStream Environment
**GetStream Chat version:** 4.24.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** latest
**Swift version:** latest
**Xcode version:** latest
**Device:** iPhone 11 Pro

**Comment by martinmitrevski** [comment]
Hey @moubry, 

This is now implemented and available on our `main` branch. 

It will also be available in our next release, most likely mid-next week.

Best,
Martin
