### ISSUE TITLE
ChatChannelView doesn't always allow scrolling back into history.

### ISSUE THREAD

**Issue by sgoodwin** [GetStream/stream-chat-swiftui#239]
## What did you do?

Hi! In our app we are showing chats and people, talk enough that you'll need to scroll back to read it all.

## What did you expect to happen?

I expected that I could scroll up and the ChatChannelView would show older messages.

## What happened instead?

Sometimes it works, other times it does not, with no info I can see in the console as to why. It's inconsistent as you navigate in and out of a channel.

## GetStream Environment
**GetStream Chat version:** main
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16
**Swift version:** 5
**Xcode version:** 14.1
**Device:** iPhone 13 Pro

**Comment by martinmitrevski** [comment]
Hey @moubry, thanks for providing the additional details.

Does the affected channel(s) contain pinned / quoted messages maybe? (since those can have an effect on the pagination). Also, does it happen on a particular channel, or all channels are affected when you apply your custom filtering?

**Comment by martinmitrevski** [comment]
Hey @moubry, @sgoodwin,

Most likely this is the same issue as reported here: https://github.com/GetStream/stream-chat-swift/issues/2423. Are you using `messagesLimit` in your channel list query?

**Comment by moubry** [comment]
@martinmitrevski We're not using `messagesLimit` in our channel list query. Here's the full query:

```swift
            controller = ChatClient.shared.channelListController(
                query: .init(filter: .and([
                    .equal("group_id", to: group.id),
                    .containMembers(userIds: [currentUserID])
                ])),
                filter: { channel in
                    guard let groupID = channel.extraData["group_id"]?.numberValue else { return false }
                    return group.id == Int(groupID)
                }
            )
```

**Comment by martinmitrevski** [comment]
hey @moubry, @sgoodwin

Can you please test with the latest release (or our latest `main` branch), that depends on StreamChat 4.26.0?

We made some improvements in our low-level client in terms of pagination, so hopefully this will fix the issue for you too.

Looking forward to your feedback.

**Comment by sgoodwin** [comment]
Thank you @martinmitrevski ! It looks like the problem is fixed. We'll test some more today to confirm.

**Comment by martinmitrevski** [comment]
hey @sgoodwin, 

Did you have a chance to test this further? Should we close the issue or are you still experiencing some issues?

Thanks

**Comment by sgoodwin** [comment]
Hi! Yes, sorry, forgot to get back. I think we're all set here. Thank you!
