### ISSUE TITLE
macOS Support (not catalyst or designed for iPad)

### ISSUE THREAD

**Issue by j-j-m** [GetStream/stream-chat-swiftui#241]
## What are you trying to achieve?

I have a Mac app that leverages features not possible with catalyst or designed for iPad. I have been using stream in the iOS app and would love to bring my experience to the desktop, but don't really want to lose some of the features available outside macCatalyst etc. I guess I am wondering if you have any future plans to support this use case or potential workarounds? also if there is any known prior art or resources you may be aware of... I would love to hear/see them

## If possible, how can you achieve this currently?

I worked for a bit on a fork to see if I could bridge NS/UIImage, Color, Pasteboard,  ViewControllerRepesentable etc. This seems a little bit crazy to be used in production. Since the core StreamChat repo works on plain old macOS I could also probably work on my own UI layer for macOS and fallback to this framework for iOS/iPad.

## What would be the better way?

To let the experts create a way better, holistic experience :)

**Comment by martinmitrevski** [comment]
Hey @j-j-m,

Thanks for raising this issue. Supporting macOS without catalyst or designed for iPad has been in the back of our minds for some time now, but we didn't have much interest from customers to push the priority on it - usually they use the other  options. 

Can you please share what types of limitations do you hit when using catalyst? Would be nice to get an idea of those when we determine the priority of such support. If there are any quick wins we could do, to overcome your limitations, we would certainly put some effort to it.

I can't promise anything in terms of timeline when/if we will add full support. If you need it very soon, then the best way would be what you've suggested - build on top of StreamChat your own UI for macOS.

Best,
Martin

**Comment by j-j-m** [comment]
The most basic thing is that the app has a MenuBarExtra, some audio stuff, probably more. Basically I want to be able to use cutting edge features as they come out so I made the app a proper Mac app. I think this will become a lot more common given apple added a cross platform option when creating a project in Xcode 14.

Thanks for your reply. I will go ahead with the custom UI build on top of the core library.
