### ISSUE TITLE
Crash showing ChatChannelListView

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#244]
## What did you do?

I created an app that uses the [StreamChatSwiftUI](https://github.com/GetStream/stream-chat-swiftui) project’s `ChatChannelListView`, the navigated into a filtered channel list.

## What did you expect to happen?

I expected it to load the channel list.

## What happened instead?

It crashes, intermittently.

## GetStream Environment
- **StreamChat:** 4.24.1
- **StreamChatSwiftUI:** main ([75d3a4f9c967277db9a08a0829aefd4578372157](https://github.com/GetStream/stream-chat-swiftui/commit/75d3a4f9c967277db9a08a0829aefd4578372157))
- **iOS version:** 16.1.2 (20B110)
- **Swift version:** latest
- **Xcode version:** Version 14.1 (14B47b)
- **Device:** iPhone 14 Pro

## Additional context

Screenshots from Xcode demonstrating the crash:

<img width="2055" alt="Screenshot 2022-12-07 at 9 07 57 PM" src="https://user-images.githubusercontent.com/144283/206347925-02d5b1db-6fae-4bc6-bcdf-11d2b8e1e50c.png">

<img width="2109" alt="Screenshot 2022-12-07 at 9 11 33 PM" src="https://user-images.githubusercontent.com/144283/206347902-72514394-8950-4885-a247-0da5ce4012a2.png">

The crash seems to happen on navigation INTO the channel list view. We do not yet have reproduction steps, but it's happened at least twice today to us during testing: once navigating into the channel list view (from a parent view), and once navigating back out to the channel list view from the message list view.

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks for reporting the issue. Can you please share any additional details about the setup? Any customizations that you're doing or is it just the display of the channel list?

We will be looking into this, however it would be nice to provide reproduction steps (if possible).

Best,
Martin

**Comment by moubry** [comment]
Our production app is unfortunately doing a lot of customizations so it's difficult to speculate about the exact issue.

My best guess is we're doing channel list filtering. Code snippet:

```
  controller = ChatClient.shared.channelListController(
      query: .init(filter: .and([
          .equal("group_id", to: group.id),
          .containMembers(userIds: [currentUserID])
      ])),
      filter: { channel in
          guard let groupID = channel.extraData["group_id"]?.numberValue else { return false }
          return group.id == Int(groupID)
      }
  )
```

I will also say that it happened a few times to one user rapidly, and then never happened again to that user, or any other user. So it might be a race condition as a result of some intermittent system behavior like low connectivity?

**Comment by martinmitrevski** [comment]
Thanks for providing the additional details. We will try to reproduce it.

**Comment by moubry** [comment]
@martinmitrevski My colleague that this occurred to confirmed that he had indeed logged out before he got these crashes, since he was recording a video of onboarding in our app. Feel free to close if you think this issue will be resolved in a future release, and we can re-test it then. Thank you so much.

**Comment by martinmitrevski** [comment]
@moubry, thanks for confirming. This will be solved with your other ticket: https://github.com/GetStream/stream-chat-swift/issues/2381, in the release that's coming most likely Wednesday or Thursday this week. You will need to use the async logout (with a completion handler) instead. We will notify you on that issue for exact steps.

About this issue, if you still have the crash after upgrading to the async logout, please reopen it.
