### ISSUE TITLE
Duplicate Text in Multiple Attachment

### ISSUE THREAD

**Issue by Developersimform** [GetStream/stream-chat-swiftui#245]
## What did you do?
- Select Multiple Attachments for a single message
- Add Message text with that attachment.

## What did you expect to happen?
- Single Message Text at the bottom of the Multiple Attachment message.

## What happened instead?
- Getting Duplicate message text with Multiple Attachments in the Attachment bubble.

## GetStream Environment
**GetStream Chat version:** 4.24.1
**GetStream Chat frameworks:**StreamChatSwiftUI 4.24.1 
**iOS version:** iOS 16
**Swift version:** swift 5
**Xcode version:** Xcode 14.1
**Device:** iPhone xs

## Additional context

https://user-images.githubusercontent.com/100925886/208034375-de75c9dd-42f9-40c9-8741-8e9e0351529f.mov

**Comment by martinmitrevski** [comment]
Hello @Developersimform,

Thanks for reporting, we will look into it and get back to you when we have an update.

Best,
Martin

**Comment by martinmitrevski** [comment]
@Developersimform this is now fixed and available on our `main` branch.
