### ISSUE TITLE
Multiple Images Chat bubble Thumbnail  flickering

### ISSUE THREAD

**Issue by Developersimform** [GetStream/stream-chat-swiftui#246]
## What did you do?
- Select multiple images and send.

## What did you expect to happen?
- Thumbnail Images should not flicker

## What happened instead?
- Thumbnail Images are flickering

## GetStream Environment
**GetStream Chat version:** 4.24.1
**GetStream Chat frameworks:**StreamChatSwiftUI- 4.24.1
**iOS version:**iOS 16
**Swift version:**swift 5
**Xcode version:**Xcode 14.1
**Device:**iPhone xs

https://user-images.githubusercontent.com/100925886/208097734-81134866-ccd3-453a-8964-ea74d40c8fa3.mov

**Comment by martinmitrevski** [comment]
Hello @Developersimform,

Thanks for reporting, we will look into it.

Best,
Martin

**Comment by laevandus** [comment]
Hi @Developersimform, this has been fixed. Please upgrade to the latest version.
