### ISSUE TITLE
Is there any way to get channels directly from local DB?

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#248]
- Currently, In my search feature, I am creating channelController and synchronise it to get the channel list. synchronise calls API to get query data.
- I tried to get locally fetched channels from channelListViewModel but it doesn't give results sometimes because ChannelList has paginations. I can search for visible channels only.
- Is there any way to fetch channels locally without calling any API bypassing its pagination logic?

## GetStream Environment
**GetStream Chat version:** 4.25.0
**GetStream Chat frameworks:** StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

We don't have a way to fetch channels directly from the local DB, and also this is not in our roadmap at the moment. 

You would need to use the pagination logic if you want to fetch the channels - you could still do it programatically with the channel list controller.

Best,
Martin
