### ISSUE TITLE
Update attachment extraData 

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swiftui#249]
## What did you do?
I need to add some extradata in my image/video/attachment. I have a custom picker for adding files with which i add some extradata to my assets which is of type `AddedAsset`. 
Eg :- `updatedAsset.extraData["width"] = 50`

## What did you expect to happen?
Get extradata of each attachment attached.

## What happened instead?
When `sendMessage` function is called it maps all the assets into `AnyAttachmentPayload` and at that time no extraData is passed into that. 
After that when `sendMessage` function is called we don't get any extra data from the attachment.

Can you please share if I missed something or something needs to be updated from my end ?

Added attachments for reference.

## GetStream Environment
GetStream Chat version: 4.25.0
GetStream Chat frameworks: StreamChatSwiftUI

## Additional context
<img width="735" alt="Screenshot 2022-12-20 at 5 05 05 PM" src="https://user-images.githubusercontent.com/63775307/208658378-e3dc2c46-29f7-46af-9d0c-93930b502809.png">
<img width="525" alt="Screenshot 2022-12-20 at 5 05 11 PM" src="https://user-images.githubusercontent.com/63775307/208658388-bb385e19-25f8-45cb-a90c-e17038af374d.png">

**Comment by martinmitrevski** [comment]
Hey @mdhanif-simformsolutions,

Thanks for reporting. It seems this needs to be fixed in the SwiftUI SDK. 

We will look into it and get back to you when we have updates.

Best,
Martin

**Comment by martinmitrevski** [comment]
Hello @mdhanif-simformsolutions,

This is now fixed, and available on our `main` branch.

Best,
Martin
