### ISSUE TITLE
Cannot delete attached video after closing app when the video is uploading

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swiftui#251]
## What did you do?
Send a message attached with video. While video is uploading kill app. Restart the app again and see if attached video is send properly or not.

## What did you expect to happen?
Attached video should work like a normal message. On which user can perform actions like react, delete etc

## What happened instead?
User not able to react to message or delete message.

## GetStream Environment
GetStream Chat version: 4.25.0
GetStream Chat frameworks: StreamChatSwiftUI
**iOS version:** 16.2
**Xcode version:** 14
**Device:** iPhone Xs Max

## Additional context
Reference video :- [Video Delete issues](https://drive.google.com/file/d/1htmUAIg6LW9RmbQL8juQ_4PstXYlQmzI/view?usp=share_link)

**Comment by mdhanif-simformsolutions** [comment]
Similar Issues with uploading image. 

**Image can't be load when restarting app**
**Message can't be deleted**

Video ref :- [Image Attachment issues](https://drive.google.com/file/d/1qUmVigoIVymEejJ-E0HuHVkePK0jno8l/view?usp=share_link)

**Comment by martinmitrevski** [comment]
Hello @mdhanif-simformsolutions,

Thanks for reporting, we will look into this.

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @mdhanif-simformsolutions,

This is fixed in our low-level client repo. It will be available in the SwiftUI SDK on our next release.

In the meantime, if you need it sooner, you can create a fork that depends on `StreamChat` on its `develop` branch.

Best,
Martin

**Comment by martinmitrevski** [comment]
Hi @mdhanif-simformsolutions,

This is now fixed and available in 4.26.0 and the `main` branch.

Best,
Martin
