### ISSUE TITLE
I get Fatal error: Attempted to read an unowned reference error when running the app

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#256]
## What did you do?
Nothing. Just ran the app

## What did you expect to happen?
App to run

## What happened instead?
it crashed

## GetStream Environment
**GetStream Chat version: Latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: iOS 16.1, minimum deployment 14.0**
**Swift version: 5.7**
**Xcode version: 14.2**
**Device: iPhone 11**

## Additional context
![Screenshot 2022-12-24 at 22 10 18](https://user-images.githubusercontent.com/69051988/209448622-5549df3b-6915-4a3f-b9eb-b8fc3690fa5c.png)

![Screenshot 2022-12-24 at 22 10 25](https://user-images.githubusercontent.com/69051988/209448617-c8f12fd0-3cc2-4dde-9232-079ba3fd03eb.png)

**Comment by martinmitrevski** [comment]
Hello @grandsir,

Did you just run our demo app or you have some customizations in your project? If the second is the case, please share some example code.

Also, you can try cleaning the project if you did some modifications to the view factory, that sometimes helps.

Looking forward to your feedback,
Martin

**Comment by grandsir** [comment]
Yes, cleaning the project did help, it is quite weird. Thanks!
