### ISSUE TITLE
Custom message grouping in SwiftUI

### ISSUE THREAD

**Issue by cvb941** [GetStream/stream-chat-swiftui#257]
## What are you trying to achieve?
I want to alter the default grouping of messages (top, middle, bottom) logic in SwiftUI.

## If possible, how can you achieve this currently?
I have tried to find a view factory that would allow transforming the message list before rendering. However, I could not find a message view that has access to other messages (which is needed to compute the grouping).

## What would be the better way?
The grouping is computed in the `ChatChannelViewModel` in the private `groupMessages()` function. An option would be to make this method `open` so that it could be overridden with custom implementations.

## GetStream Environment
**GetStream Chat version: 4.24.0**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 16**
**Swift version: 5.+**
**Xcode version: 14.2**
**Device: Any**

**Comment by martinmitrevski** [comment]
Hello @cvb941,

Thanks for reporting, we will look into this next week, after the holidays. Either the method would be open or we will provide injecting custom implementation via the utils.

We will keep you updated.
Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @cvb941,

The `groupMessages` method is now open on our `main` branch - you can subclass the `ChatChannelViewModel` and provide your own implementation. 

It's important to set the `messagesGroupingInfo` at the end, with your own grouping (You can use the default implementation for reference).

Best,
Martin

**Comment by cvb941** [comment]
Hi @martinmitrevski,

Would it also be possible to change the visibility of some private properties (I'm looking for `utils` and `messageCachingUtils`) in order to make them usable in my overridden groupMessages method?

**Comment by martinmitrevski** [comment]
Hey @cvb941,

We would like to keep the `messageCachingUtils` private, since this implementation might change in the future and break your implementation. It would be best if you add your own small caching layer (it basically caches the authors during a chat, so it's not that big, the other methods don't impact performance). You can use our implementation for reference.

Best,
Martin
