### ISSUE TITLE
Unread badge not cleared for channel with deleted content

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#259]
I navigated into a channel from `ChatChannelListView` and viewed all of the messages in it, as well as all of the messages in the threads. I expected the unread count badge to clear. The unread badge count persists — it remains at `11`.

The best channel for you to look at while investigating this issue is [`messaging:clasawcx2000801bauzyjfoxs` on the Stream app 1217037](https://dashboard.getstream.io/app/1217037/chat/explorer?path=channels,channel~messaging:clasawcx2000801bauzyjfoxs,messages,message~3c203cd4-31bd-426a-b4a4-82e793105abd). This channel’s content is very simple: it has two messages and zero replies or reactions.

This issue exists in our JustStream project — an Xcode project we created that contains zero customizations except for introducing StreamChatSwiftUI’s `ChatChannelListView`.

<img width="1995" alt="Screenshot 2023-01-04 at 11 07 41 AM" src="https://user-images.githubusercontent.com/144283/210610595-6ff5a573-2585-4895-9fd3-140699683613.png">

This issue is present in our test environment where we often hard delete users and content. Our app-specific database also includes hints that this channel used to have more messages in it than are currently visible. We suspect that the unread count was incremented with new messages, then those messages were (somehow) deleted by the user, or by the user deleting their account, and now those message cannot be seen, so the unread badge persists forever, unable to be cleared.

## GetStream Environment
**GetStream Chat frameworks:** StreamChat (4.25.0), StreamChatSwiftUI (main)
**iOS version:** 16.1
**Swift version:** latest
**Xcode version:** Version 14.2 (14C18)
**Device:** iPhone 11 Pro

**Comment by moubry** [comment]
I'm sorry for the delayed response. Here are the reproduction steps you can use to see this issue in action:

1. Create a new channel with User A.
2. Invite User B to the channel as a member.
3. Navigate User A to the Channel List View.
4. Post messages into the channel as User B.
5. Hard Delete User B like this:
```go
// Deletes a user in Stream. This is a hard delete, which means the user’s
// messages are also deleted.
func (s *StreamService) DeleteUser(user earbuds.User) error {
	if user.StreamUserID == "" {
		return nil
	}
	ctx := context.Background()
	_, err := s.client.DeleteUsers(ctx, []string{user.StreamUserID}, stream.DeleteUserOptions{
		User:          stream.HardDelete,
		Messages:      stream.HardDelete,
	})
	return err
}
```
6. Notice that for User A the number of unread badges does NOT decrement. Navigate into the channel and see that all of User B's messages are gone. Go back to the channel list and the badge is still there. It's impossible to clear it.

**Comment by moubry** [comment]
We've discovered that this issue also seems to exists when you delete a channel that contains unread messages too — it does not seem to be limited to the delete user scenario as I had originally described.

**Comment by martinmitrevski** [comment]
closing this one, since it's not related to the SwiftUI SDK. Best to proceed the communication on the support channels, if the issue still persists.
