### ISSUE TITLE
ChatChannelView scroll view jitters like crazy when you scroll to top or bottom

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#26]
https://user-images.githubusercontent.com/97132583/153679439-9df8de61-634f-42bb-8f74-a3ef08c6c7c6.mp4

## What did you do?
See my video.
1. Scroll to bottom of a ChatChannelView. If you fling too hard, this won't reproduce; but if you just land at the end, the offset jitters like crazy.
2. Scroll to the top of a ChatChannelView. When you pull pretty hard, the scroll offset is all over the place

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat 4.10.0, StreamChatSwiftUI 4.9.0
**iOS version:** iOS 15. 
**Swift version:** 5.5.2
**Xcode version:** 13.2.1
**Device:** iPhone 13 Pro

**Comment by martinmitrevski** [comment]
Hey @linhewinner 

Thanks for reporting the issue. We will analyse it internally and provide fix soon.

Best, 
Martin

**Comment by linhewinner** [comment]
sorry guys, in an effort to work around this issue:
https://github.com/GetStream/stream-chat-swiftui/issues/27

I copy-pasted ChatChannelListView and slightly modified the file. In my rush, I accidentally deleted this line:
```swift
        .navigationBarTitleDisplayMode(viewFactory.navigationBarDisplayMode())
```

That caused the bug. Now I put the line back in, the view works perfectly fine. My bad.
