### ISSUE TITLE
Older messages failing to load.

### ISSUE THREAD

**Issue by sgoodwin** [GetStream/stream-chat-swiftui#267]
Hi y'all! We thought this was fixed, but it's still happening and we're not sure why.

## What did you do?

1. Hop into a chat.
2. Type new messages with the numbers 1-60 to make sure there's enough messages in the chat.
3. Leave the chat and then navigate back.
4. Scroll up in messages to see the older ones.

## What did you expect to happen?

You should see all the way back to your first message, "1".

## What happened instead?

You'll only see back to about 37 or sometimes about 17.

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.3
**Swift version:** 5.7.2
**Xcode version:** 13.0.1
**Device:** iPhone 13 Pro

## Additional context

You can see this happening in the example project we've shared: https://github.com/EarBudsDev/JustStream in the `nav-observation` branch.

The two chats, "Test Loading" and "Test" near the top exhibit this issue, one with just over 40 messages and one with just over 60.

Here's a video showing the issue: https://youtube.com/shorts/AI6TkQNbxcM

The example project is doing very little customization of stream, most notably we've inserted a custom view to let us observe navigation changes better. Even if you remove this and delete our `makeChannelDestination()` function from the `CustomViewFactory` in the project, you'll see the same behavior. It's not totally consistent, but in a day of testing, I rarely saw all the way back to the first message (maybe 2-3 times).

Here is the log output from running the example app, opening a chat, and trying to scroll up to older messages.
[stream_logs.txt](https://github.com/GetStream/stream-chat-swift/files/10544320/stream_logs.txt)

**Comment by martinmitrevski** [comment]
Hey @sgoodwin,

We've debugged this issue and the problem is in the `makeChannelDestination` implementation in your project. 

Basically, what happens is that SwiftUI's `NavigationLink` can call this method few times, which re-creates the channel controller and view model (the following two lines):
```swift
            let channelController = chatClient.channelController(
                for: selectionInfo.channel.cid,
                messageOrdering: .topToBottom
            )
            let channelViewModel = ViewModelsFactory.makeChannelViewModel(
                with: channelController,
                messageController: nil,
                scrollToMessage: nil
            )
```
In our default implementation, we are keeping a state for this to prevent such issues:
```swift
    public func makeChannelDestination() -> (ChannelSelectionInfo) -> ChatChannelView<Self> {
        { [unowned self] selectionInfo in
            let controller = InjectedValues[\.utils]
                .channelControllerFactory
                .makeChannelController(for: selectionInfo.channel.cid)
            return ChatChannelView(
                viewFactory: self,
                channelController: controller,
                scrollToMessage: selectionInfo.message
            )
        }
    }
```
Our `channelControllerFactory` is an implementation detail that we don't expose publicly, but please create something similar to avoid recreating the `channelController`.

Let me know if that helps.
Best,
Martin

**Comment by sgoodwin** [comment]
Hi Martin! I noticed this when I was investigating myself and did try to use something so that the channel controller wasn't being re-created each time. This did not solve the problem for our app or this sample project. As I noted, even if you remove this `makeChannelDestination` entirely and rely on the default implementation from the SDK, this issue is still visible.

**Comment by martinmitrevski** [comment]
Hey @sgoodwin, that's interesting - that actually solved the issue for us while investigating, on your demo project. 

One thing I can think of - sometimes, when you do changes in the view factory, it requires cleaning the project for the changes to be taken into consideration. 

If that doesn't help, can you please push those changes to the demo project, and we will keep investigating.

**Comment by sgoodwin** [comment]
Thanks @martinmitrevski. I always forget the swift compiler gets all confused with protocols and default implementations. After clean+build, things do behave as you describe when deleting our custom implementation of channel destination (and as Sean found when he tried himself). Also after a clean+build, my custom channel controller-sharing code makes a difference and things work properly again. Sorry for the trouble!

**Comment by martinmitrevski** [comment]
awesome, nice to hear that! 👍
