### ISSUE TITLE
StreamChat SwiftUI documentation code is not complete

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#270]
using raw .init() is impossible without specifying the type. And LLVM gives an error as well, just for your information 🙂 

![Screenshot 2023-02-06 at 19 23 05](https://user-images.githubusercontent.com/69051988/217033950-59091773-5eff-46a2-8de1-f9ab95a4547c.png)

[link to documentation](https://getstream.io/chat/docs/sdk/ios/swiftui/message-components/message-reactions/#customizing-the-message-reactions-view)

**Comment by martinmitrevski** [comment]
Hey @grandsir,

Thanks for spotting this. It's going to be fixed with this PR: https://github.com/GetStream/stream-chat-swift/pull/2479, and the docs will be automatically updated with our next release.

Best,
Martin
