### ISSUE TITLE
ChannelList pagination freeze UI

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#273]
## What did you do?
- Login with a user which has more than 100 channels
- Scroll down channels which call `viewModel.checkForChannels(index: index)` for pagination and receives new channels

## What did you expect to happen?
- The new channels should append to the list smoothly.

## What happened instead?
- UI performance decreased dramatically on pagination called.

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.2
**Device:** Iphone-X

## Additional context

https://user-images.githubusercontent.com/47667077/217758881-e5b422a0-d89e-4ab8-830e-fe1a3e7b5bec.mov

**Comment by martinmitrevski** [comment]
Hello @ajay-simform,

Can you please share more details:
- Do you do anything specific or this is the default implementation from the Demo app?
- How many channels / messages per channel do you load per page? (the default is 20)
- Anything else that's worth mentioning?

Thanks, Martin

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,
- The channels page size is 10 and message per channel sets 1.
- Regarding pagination, it is the default implementation.
- showing multiple channels list in the tabBar view. In this case, I use 3 ChatChannelListView with same channel query.

**Comment by martinmitrevski** [comment]
Does it happen if you use only one `ChatChannelListView`? 

Might be better to use a custom component where you will do if-else on the 3 different channel list views, so only one is active at a time. 

Another thing to check would be to see if changes affect all 3 lists (since they are active). Since if they do (they depend on the same query), all the work would be done 3 times at the same time, which is probably causing the issues for you.

**Comment by martinmitrevski** [comment]
closing this one, since we can't do much SDK wise. The suggestions above apply - try to use one channel list view at a time (or don't depend on the same query). Additionally, the `loadingNextChannels` enabled in the other issue will help in improving the experience.
