### ISSUE TITLE
loadingNextChannels variable is not accessible

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#275]
- My plan is to show placeholder shimmer until we get new pagination channels.
- For that, I am planning to make a shimmer condition based on `loadingNextChannels` variable in `ChatChannelListViewModel`.
- But `loadingNextChannels` is not accessible due to private access control.
- please help to make it public. So that I can add shimmer condition based on that variable.

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** Iphone-X

**Comment by martinmitrevski** [comment]
Hi @ajay-simform,

`loadingNextChannels` is now exposed as `public` on our `main` branch.

Best, Martin
