### ISSUE TITLE
LinkAttachmentView not detect Link URL

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#278]
- Simply send a message with `link.xy.xyz/ethx`
- When a message appears, this link is not considered a hyperlink and can't be tappable.
- It should consider a hyperlink.

## GetStream Environment
**GetStream Chat version:** 4.27.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.2
**Device:** Iphone-X

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

I've checked this particular link, and there's not enough metadata for the backend to recognize this as a link attachment.

We don't do local detection of links by default in the SDK, but you can do this by yourself. These are the steps:
- implement the `makeMessageTextView` method in the view factory
- check if you can create a url out of the message text
- if yes, just create a button which will open the created url using `UIApplication.shared.open(url, options: [:])`
- if not, fallback to your default implementation, for example use our `MessageTextView` (or something else if you already have a default implementation).

Hope this helps.
Best,
Martin
