### ISSUE TITLE
Can not find SearchResultsView in scope.

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#280]
https://www.youtube.com/watch?v=526swCwDMX8

I was just following this tutorial to build the swipe actions to set custom swipe actions to our app, and in that tutorial, in order to implement a custom swipe action, he creates a new ChannelList which takes the SearchBar given from the default ChatChannelListView. and it is defined internally as well, I'd be glad if you could make it public.

**Comment by grandsir** [comment]
![Screenshot 2023-03-01 at 18 02 28](https://user-images.githubusercontent.com/69051988/222178223-e313de64-0ac7-499a-ae2d-e8ac162f8062.png)

**Comment by grandsir** [comment]
![Screenshot 2023-03-01 at 18 15 36](https://user-images.githubusercontent.com/69051988/222181725-d99148fe-6c29-48d4-9779-0e158e8a603f.png)
this too

**Comment by martinmitrevski** [comment]
Hello @grandsir,

Thanks for reporting. It makes sense for these two to be public, I've just exposed them on our `main` branch.

Best,
Martin
