### ISSUE TITLE
Odd navigation behaviour in sample app

### ISSUE THREAD

**Issue by crayment** [GetStream/stream-chat-swiftui#281]
## What did you do?

1. Run the demo app from `main` (3c74833d2da65ab6a45ab274c6e87abf703b9ac4) on iPad simulator
2. Tap blue pencil to start a new chat
3. Select anyone from the list
4. Notice the chat opens on the left side, not on the details side as I would expect. So now you have two chats open.

## What did you expect to happen?

I expected the chat would open on the details side.

## What happened instead?

The new chat opened on the left side so I had two chats open

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.2
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** iPad Pro (11-inch) 4th generation

## Additional context

https://user-images.githubusercontent.com/78082/222201758-d207755f-6ac2-4338-84a5-f4bd3c6c22ab.mov

**Comment by martinmitrevski** [comment]
Hey @crayment,

Thanks for reporting. Yes, this is a bug in the sample app, not in the SDK. In any case, we will analyse this and fix it.

Best, Martin

**Comment by martinmitrevski** [comment]
This one is also fixed now in the sample app, thanks for reporting.
