### ISSUE TITLE
Channel being auto selected when it should not

### ISSUE THREAD

**Issue by crayment** [GetStream/stream-chat-swiftui#282]
## What did you do?

- Open demo app on an iPad
- Use Split View features to get the app into a constrained width
- Login by selecting a user
- The channel list shows, but then the first channel is automatically selected

## What did you expect to happen?

The first channel should not be selected in this situation

## What happened instead?

The first channel is selected.

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.2
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** iPad Pro (11-inch) 4th generation

## Additional context

I believe any code using the `isIPad` function is suspect. It's preferable to check the `horizontalSizeClass` to determine if we are in a constrained or regular width to make these types of decisions. In this case `setInitialChannelIfSplitView` is only checking that we are on an iPad and pushing on the channel even when that behaviour will be surprising (not wide enough for a split view).

Another possible solution would be to allow disabling the auto-selection behaviour completely and instead be able to customize the empty view when no selection exists when in the main/detail columns mode.

https://user-images.githubusercontent.com/78082/222227257-b37e65de-ef5c-4d07-8f23-31dfb5d032ce.mov

**Comment by martinmitrevski** [comment]
Hey @crayment,

Thanks for reporting. I agree the current behaviour is not ideal. The horizontal size classes approach was something we already tried, but it always returned `regular` width for some reason. 

In any case, we will look into this in more detail and get back to you.

Best, 
Martin

**Comment by crayment** [comment]
Hmm that's strange. I'm successfully using it in some custom views I'm injecting through the view factory right now via: `@Environment(\.horizontalSizeClass) var horizontalSizeClass`. I know these Split View features don't get a lot of love, but with the new stage manager features handling this correctly becomes much more important.

**Comment by martinmitrevski** [comment]
hey @crayment, this is now fixed and available on our `main` branch, thanks again for reporting.
