### ISSUE TITLE
Message Group Issue 

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#284]
## What did you do?
I am creating a messages view like slack. I made the **CustomMessageView** using the **makeMessageContainerView** modifier of Stream SDK. 

**makeMessageContainerView**
``` Swift
func makeMessageContainerView(
        channel: ChatChannel,
        message: ChatMessage,
        width: CGFloat?,
        showsAllInfo: Bool,
        isInThread: Bool,
        scrolledId: Binding<String?>,
        quotedMessage: Binding<ChatMessage?>,
        onLongPress: @escaping (MessageDisplayInfo) -> Void,
        isLast: Bool
    ) -> some View {
        CustomMessageView(
            channel: channel,
            message: message,
            isInThread: isInThread,
            isLast: isLast
        )
    }

```

**CustomMessageView**
``` Swift
struct CustomMessageView: View{
    let channel: ChatChannel
    let message: ChatMessage
    let isInThread: Bool
    let isLast: Bool
    
    var body: some View{
        
        HStack(alignment: .top, spacing: 10){
            ZStack{
                if let imageUrl = message.author.imageURL{
                    LazyImage(imageURL: imageUrl)
                        .cornerRadius(3, corners: .allCorners)
                } else{
                    RoundedRectangle(cornerRadius: 3)
                        .fill(Color.purple3)
                }
            }
            .frame(width: imageDimention, height: imageDimention)
            
            VStack(spacing: 2){
                if !isInThread{
                    HStack(spacing: 4){
                        
                        Text(message.author.name ?? "")
                            .font(.poppins(name: .poppinsSemiBold, size: 16))
                            .foregroundColor(.black)
                        
                        Text(message.createdAt.stringFromDate(formate: "HH:mm a") ?? "")
                            .font(.poppins(name: .poppinsRegular, size: 14))
                            .foregroundColor(.black.opacity(0.5))
                        
                        Spacer()
                    }
                }
                
                HStack{
                    Text(message.text)
                        .font(.poppins(name: .poppinsRegular, size: 16))
                        .foregroundColor(.black)
                    
                    Spacer()
                }
            }
        }
        .padding(.horizontal, 16)
        .padding(.bottom, 16)
    }
    
    private let imageDimention: CGFloat = 36
}
```
Current design
<img width="349" alt="Screenshot 2023-03-03 at 8 49 41 AM" src="https://user-images.githubusercontent.com/73989872/222752737-35518174-6d38-47cc-a11b-cbd7624632c9.png">

## What did you expect to happen?
How I could identify that the current message is in the group of messages like below
<img width="208" alt="Screenshot 2023-03-03 at 8 50 49 AM" src="https://user-images.githubusercontent.com/73989872/222751412-865063b7-abda-47a1-bb10-61db57292d06.png">
Or a separate message.

## What happened instead?
Current code implementation shows every message as a separate message not in the group of messages, multiple messages sent time same. 

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.2
**Swift version:**Swift 5 +
**Xcode version:** 14.2
**Device:** IPhone 14 Pro Simulator

**Comment by martinmitrevski** [comment]
Hello @muhammadabbas001,

There's a parameter called `showsAllInfo` that is passed to the `makeMessageContainerView`. That one gives the information whether the full info of the message should be presented (is leading the group), or not (is part of the group).

Since you are using your custom container view, and not our default `MessageContainerView`, you will need to do the handling inside your code, taking the `showsAllInfo` flag in consideration. 

Have a look at how we do it in the default implementation here: https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageContainerView.swift.

Hope that helps.
Best,
Martin

**Comment by muhammadabbas001** [comment]
Hi @martinmitrevski thank you so mutch this solution works. Thanks
