### ISSUE TITLE
imageCDN customization not being respected in some places

### ISSUE THREAD

**Issue by crayment** [GetStream/stream-chat-swiftui#286]
## What did you do?

In our app our user avatar URL's are protected by authorization. I am using a custom `StreamImageCDN` subclass to add an appropriate authorization token to requests to our server using the `urlRequest(forImage:)` function. This is working well in one spot, but not in another.

## What did you expect to happen?

I expected the `imageCDN` specified in the `Utils` to be used for image loading in all places.

## What happened instead?

It works here:

<img width="350" alt="Screenshot 2023-03-08 at 10 22 36 AM" src="https://user-images.githubusercontent.com/78082/223786352-64bccf59-e490-4914-90aa-5fcd62052599.png">

And does not work here, the requests from this list do not go through the customized CDN from what I can tell.

<img width="1127" alt="Screenshot 2023-03-08 at 10 19 53 AM" src="https://user-images.githubusercontent.com/78082/223786480-81fe64fd-a5d3-4a4c-8468-13c92e805b24.png">

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.2
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** iPad Pro (11-inch) 4th generation

## Additional context

Here is some code, but the description should be enough I think.

```swift
let utils = Utils(
    imageCDN: CustomImageCDN()
)

class CustomImageCDN: StreamImageCDN {
    override func urlRequest(forImage url: URL) -> URLRequest {
        var request = URLRequest(url: url)
        
        // If the request is going to our API, give it an access token.
        if url.host == DependencyValues._current.activeAPIBaseURL.host,
            let access = try? DependencyValues._current.activePersistence.accessToken()
        {
            request.setValue("Bearer \(access.token)", forHTTPHeaderField: "Authorization")
        }
        
        return request
    }
    
    override func thumbnailURL(originalURL: URL, preferredSize: CGSize) -> URL {
        // We don't support arbitrary resizing, so just discard preferred size if the request is going to our backend
        if originalURL.host == DependencyValues._current.activeAPIBaseURL.host {
            return originalURL
        } else {
            return super.thumbnailURL(originalURL: originalURL, preferredSize: preferredSize)
        }
    }
}
```

**Comment by martinmitrevski** [comment]
Hey @crayment,

Thanks for reporting this, I can confirm it's an issue. We will fix this and provide an update soon.

Best, Martin

**Comment by martinmitrevski** [comment]
Hey @crayment,

This is now fixed and available on our `main` branch. Please check and feel free to reopen it if you still have issues.

Best, Martin

**Comment by crayment** [comment]
Seems to be working great for me now, thanks!
