### ISSUE TITLE
@-mentioning does not always work

### ISSUE THREAD

**Issue by davitykale** [GetStream/stream-chat-swiftui#288]
## What did you do?
If you drop to a new line in a message, you are unable to @-mention anyone.

## What did you expect to happen?
I would expect that you can always @-mention a user whenever users allowed.

Like here -- I dropped down to a newline and can still @-mention.

## What happened instead?
Because of this check: https://github.com/GetStream/stream-chat-swiftui/blob/5c1e97bcc66d3eb2f64b18a2df26c23960f0bd5e/Sources/StreamChatSwiftUI/ChatChannel/Composer/Suggestions/TypingSuggester.swift#L101, @-mentioning fails if you drop down to a new line.

It should likely include `|| textBeforeSymbol == "\n"`.

**Comment by martinmitrevski** [comment]
Hey @davitykale,

Thanks for reporting this, I can confirm it's an issue. Most likely the fix you suggested will work - we will test this and update you when it's fixed.

Best, Martin

**Comment by martinmitrevski** [comment]
Hey @davitykale, the fix you've suggested works and it's available on our `main` branch. Thanks for taking the time, much appreciated 👍
