### ISSUE TITLE
In ChatChannelView, typing indicator covers message

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#29]
![272715082_776173260259132_5693551124117532932_n](https://user-images.githubusercontent.com/97132583/153690113-c7ef45ef-1a27-4b8e-b7c5-a2bc5dfae9de.jpg)

See screenshot.
You could argue this is working as intended ... but there has got to be a better UI design to avoid the covering the message?

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat 4.10.0, StreamChatSwiftUI 4.9.0
**iOS version:** 15
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 Pro

**Comment by martinmitrevski** [comment]
Hi @linhewinner,

The placement of the typing indicator above the message list and covering the last message is the default product design. 

There are two options to change this behaviour: 
- change the typing indicator to be shown in the navigation bar. More details here: https://getstream.io/chat/docs/sdk/ios/swiftui/components/typing-indicators/
- Turn off the typing indicators completely from the dashboard and implement a custom view with the position that suits best. With this approach, you will need to use the lower level components, not the `ChatChannelListView`.

Hope this helps. We can't change design of the default component at this moment.

Best, 
Martin
