### ISSUE TITLE
Placeholder avatar consistency and blurry rendering

### ISSUE THREAD

**Issue by crayment** [GetStream/stream-chat-swiftui#290]
## What are you trying to achieve?
When users don't have an avatar set there should be a way to customize the icon shown for them in a way that renders non-blurry and consistently throughout the UI.

## If possible, how can you achieve this currently?

I believe I can customize `personPlaceholder` but it still renders blurry. There is also `avatarPlaceholders`. I don't think either of these let me fix the fact that the image renders blurry. I can only change the image, not the way it is resized.

## What would be the better way?

Why are there two placeholder avatar systems? If no good reason it would be preferable to have a single customization point and consistent behaviour, right?

It also might be better to give me full rendering of the placeholder view, so that I can control how it is resized and make sure it doesn't come out blurry like it does today. But as long as I could ensure clear rendering I don't really need full control.

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.2
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** iPad Pro (11-inch) 4th generation

## Additional context

<img width="1416" alt="Screenshot 2023-03-15 at 9 44 54 AM" src="https://user-images.githubusercontent.com/78082/225366411-09ee4474-586f-46e8-8b86-b824d55778fd.png">

**Comment by martinmitrevski** [comment]
Hey @crayment,

Thanks for reporting this, we will improve this in the SDK - there should be one avatar logic and the images shouldn't be blurry.

Will get back to you when we have an update.

Best, Martin

**Comment by martinmitrevski** [comment]
This is now fixed and available on our `main` branch.
