### ISSUE TITLE
Customize Channel Info View

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swiftui#291]
## What did you do?
Hi,
I need to customize the **ChatChannelInfoView**. I tried to use **ChannelInfoDivider**, **ChatInfoOptionsView**, **ChatChannelInfoButton** to skip the remaining views from Info View but could not use them. 

## What did you expect to happen?
Could you please (**ChannelInfoDivider**, **ChatInfoOptionsView**, **ChatChannelInfoButton**) make them public to customize ChatChannelInfoView as our need. Or is there any other best way to customize the **ChatChannelInfoView**.

## What happened instead?
Write now I see the following ChatChannelInfoView.
![WhatsApp Image 2023-03-16 at 10 56 21 AM](https://user-images.githubusercontent.com/127435927/225680093-f639866f-f7df-4d22-9946-1dda500b2875.jpeg)

But I need this view.
![WhatsApp Image 2023-03-16 at 10 59 07 AM](https://user-images.githubusercontent.com/127435927/225681011-5a38166b-e30d-451e-ad25-aed2ffcb347d.jpeg)

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** IOS 16
**Swift version:** Swift 5 +
**Xcode version:** 14.2
**Device:** IPhone 14 Pro Simulator

**Comment by martinmitrevski** [comment]
Hi @Zee-93, 

We've exposed ChatInfoOptionsView and ChatChannelInfoButton as public. The ChannelInfoDivider is a trivial divider that you can re-create in the app, we would like to keep it private.

In general, since there are many variations of this screen, we recommend re-creating it instead of exposing separate slots. You can do it now easily with the new public components.

Best, Martin

**Comment by Zee-93** [comment]
@martinmitrevski 
Thanks for your kind support. Now I can customize the ChatChannelInfoView very easily. 

Could you put the selected views to a separate view. This will help use to customize the ChatChannelInfoView more. 
<img width="957" alt="Screenshot 2023-03-17 at 6 07 51 AM" src="https://user-images.githubusercontent.com/127435927/225888368-351c5727-497f-4915-9ffc-7fee73bc69c4.png">

I need to remove the ChannelNameUpdateView from ChatChannelInfoView.
<img width="319" alt="Screenshot 2023-03-17 at 6 10 10 AM" src="https://user-images.githubusercontent.com/127435927/225888818-e05dabbf-970c-4fb7-9076-4416b8ab9c07.png">
