### ISSUE TITLE
Expose NewChatView

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swiftui#292]
## What did you do?
I need to navigate on the NewChatView but could not find any way to navigate on that View. Is there any way to go to on NewChatView or could you expose that view to use that?

## What did you expect to happen?
I need to navigate on NewChatView for search users like the following view.
![WhatsApp Image 2023-03-17 at 11 06 13 AM](https://user-images.githubusercontent.com/127435927/226001126-907d6338-c174-4609-bcc9-9433a8a2337a.jpeg)
This is the screenshot of our react native application. 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @Zee-93,

The new chat view is not part of the SDK, it's a sample implementation provided in the demo app.

You will need to implement this in your app. You can find and reuse our reference implementation here: https://github.com/GetStream/stream-chat-swiftui/blob/main/DemoAppSwiftUI/NewChatView.swift.

The button is added with the custom channel modifier here: https://github.com/GetStream/stream-chat-swiftui/blob/main/DemoAppSwiftUI/CustomChannelHeader.swift.

Best, Martin
