### ISSUE TITLE
Search Channel By Other User's Names or Phone Numbers

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swiftui#293]
## What did you do?

1. Is there any way to update the search channel query? Right now our channel name is other user's name. We need to search channels by other user's names because our actual channel name is nil. 
2. Also is there any way to search channels by other users' phone numbers which are in the extra data of the **ChatMessage**?

## What did you expect to happen?

1. I need to search the channel by the second user's name, not from the actual channel name. 
2. Also search by the phone number of second user

## What happened instead?
Right now I could not search the channel by other user's names or phone numbers.

![WhatsApp Image 2023-03-17 at 2 23 20 PM](https://user-images.githubusercontent.com/127435927/226024555-c8c4007d-2f67-4ac7-b3e4-ed9823062663.jpeg)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @Zee-93,

You can do that with a custom implementation. You will need to create your own view and an instance of the `MessageSearchController`. You can find the docs about this class here: https://getstream.io/chat/docs/ios-swift/search/?language=swift&q=MessageSearch.

Best, Martin

**Comment by Zee-93** [comment]
Hi @martinmitrevski ,

Why we can't search channels direct by channel user name?

Write now I am searching the channels by members names by using this code.
``` Swift

func searchChannels(){
        let controller = chatClient.channelListController(
            query: .init(
                filter:
                        .and(
                            [
                                .equal(.type, to: .messaging),
                                .containMembers(userIds: [userAuthanticationManager.supportUserId ?? ""]),
                                .query(.memberName, text: "Zee Shan")
                            ]
                        ),
                sort: [.init(key: .lastMessageAt, isAscending: false)],
                pageSize: 10
            )
        )
        
        controller.synchronize { error in
            if let error = error {
                // handle error
                print(error)
            } else {
                print(controller.channels.count)
            }
        }
    }

```
But getting this error.
```
2023-03-20 07:09:48.077 [ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:67] [decodeRequestResponse(data:response:error:)] > API request failed with status code: 400, code: 4 response:
{
  "code" : 4,
  "message" : "QueryChannels failed with error: \"search is not enabled for field channels.member.user.name.\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "details" : [

  ],
  "StatusCode" : 400,
  "duration" : "0.00ms"
})
```

Is there any way to search channels directly from members' names?

**Comment by martinmitrevski** [comment]
Hey @Zee-93,

We don't have support for searching channels by name. It's on our roadmap, can't promise a concrete timeline, but we are hoping to start working on this in the next quarter.

**Comment by ylai-msrl** [comment]
Hello,

I can see that swift side have implemented the search channel function, may I know how to implement this function in swiftUI?

https://github.com/GetStream/stream-chat-swift/pull/2703

**Comment by martinmitrevski** [comment]
Hi @ylai-msrl, 

You can use a channel query with autocomplete, as an example you can see the UIKit implementation here: https://github.com/GetStream/stream-chat-swift/blob/59f1912e7c45f002ba38e03bf6ef9db2b3653e2d/Sources/StreamChatUI/ChatChannelList/Search/ChatChannelSearchVC.swift#L23.

Hope that helps,
Martin

**Comment by ylai-msrl** [comment]
```
func searchChannel(text: String) {
        let controller = chatClient.channelListController(
            query: .init(
                filter: .and([
                            .containMembers(userIds: [chatClient.currentUserId ?? ""]),
                            .autocomplete(.name, text: text)
                        ])
            )
        )
        
        controller.synchronize { [weak self] error in
            if error == nil {
                print(controller.channels)
            }
        }
    }
```

For anyone who need some references~

**Comment by martinmitrevski** [comment]
Thanks for sharing the code 👍
