### ISSUE TITLE
Can't customize channel list items

### ISSUE THREAD

**Issue by IKukshtel** [GetStream/stream-chat-swiftui#294]
## What did you do?
Hello, I'm trying to customize channel list items view via implementing `func makeChannelListItem` in my custom ViewFactory but nothing happens. At the same time, other methods work correctly, for example with `func makeChannelListFooterView()` I can fully change footer view.

```
public func makeTrailingSwipeActionsView(
    channel: ChatChannel,
    offsetX: CGFloat,
    buttonWidth: CGFloat,
    swipedChannelId: Binding<String?>,
    leftButtonTapped: @escaping (ChatChannel) -> Void,
    rightButtonTapped: @escaping (ChatChannel) -> Void
) -> some View {
    Text("Chat list item")
}
    
public func makeChannelListFooterView() -> some View {
    Text("Section footer")
}
```

## What did you expect to happen?
I expect that I can partially or fully change channel list item views.

## What happened instead?
Nothing changed, views are default

## GetStream Environment
**GetStream Chat version:** 
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.2
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** Simulator iPhone 14 Pro

**Comment by martinmitrevski** [comment]
Hi @IKukshtel,

There are two common possibilities why your method is not called:
- your method signature doesn't match. This can be either a simple typo, or providing a different generic type than the one that the factory will resolve. For example, in `makeChannelListItem` there's a generic type called `ChannelDestination`. That one has to match the one you've provided in the view factory.
- If you are sure that the method signatures are correct, sometimes even clean project + derived data resolves. Xcode sometimes has trouble detecting changes in protocol implementations.

Hope that helps. 
Best, Martin

**Comment by IKukshtel** [comment]
Hi @martinmitrevski, 
I checked both versions and it did not help, but finally restarting the mac did the trick 🫠
Thank you for the quick response!
