### ISSUE TITLE
Ability to set `skipPush` through `MessageComposerViewModel`

### ISSUE THREAD

**Issue by ferhatabd** [GetStream/stream-chat-swiftui#295]
## What are you trying to achieve?
Being able to set `skipPush` while we are calling `sendMessage` within `MessageComposerViewModel` 

## If possible, how can you achieve this currently?
Extending the `sendMessage` method's arguments to accept `skipPush` and also pass that value to the `createNewMessage` & `createNewReply` calls.

## What would be the better way?
Exposing all default arguments of `channelController.createNewMessage` & `messageController.createNewReply` to `sendMessage` method of the `MessageComposerViewModel`. This way we would have control over setting `skipPush` when there is a need to.

## GetStream Environment
**GetStream Chat version:** 4.29.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** iPhone / iPad

**Comment by martinmitrevski** [comment]
Hi @ferhatabd,

Thanks for reporting. Yes, that makes sense, we've updated this in our `main` branch.

Best, Martin
