### ISSUE TITLE
Support Nuke 12

### ISSUE THREAD

**Issue by paulz** [GetStream/stream-chat-swiftui#301]
## What are you trying to achieve?
App depends on Nuke >12.0.0

## If possible, how can you achieve this currently?
Downgrade to Nuke 9

## What would be the better way?
v 4.30.0 allows Nuke 12

## GetStream Environment
**GetStream Chat version:** 4.3.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.2
**Device:** iPhone

## Additional context

Xcode fails to resolve dependencies:

> Showing All Errors Only
> Failed to resolve dependencies Dependencies could not be resolved because root depends on 'nuke' 12.0.0..<13.0.0 and root depends on 'stream-chat-swiftui' 4.0.0..<5.0.0.
> 'stream-chat-swiftui' >= 4.0.0 practically depends on 'nuke' {10.0.0..<11.0.0, 11.3.0} because 'stream-chat-swiftui' 4.29.0 depends on 'nuke' 11.3.1 and 'stream-chat-swiftui' 4.30.0 depends on 'nuke' 11.3.1.
> 'stream-chat-swiftui' {4.0.0..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' {10.0.0..<11.0.0, 11.3.0} because 'stream-chat-swiftui' 4.27.0 depends on 'nuke' 11.3.1 and 'stream-chat-swiftui' 4.28.0 depends on 'nuke' 11.3.1.
> 'stream-chat-swiftui' {4.0.0..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' {10.0.0..<11.0.0, 11.3.0} because 'stream-chat-swiftui' 4.25.0 depends on 'nuke' 11.3.1 and 'stream-chat-swiftui' 4.26.0 depends on 'nuke' 11.3.1.
> 'stream-chat-swiftui' {4.0.0..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' {10.0.0..<11.0.0, 11.3.0} because 'stream-chat-swiftui' 4.23.0 depends on 'nuke' 11.3.0 and 'stream-chat-swiftui' 4.24.0 depends on 'nuke' 11.3.1.
> 'stream-chat-swiftui' {4.0.0..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.21.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.22.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.19.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.20.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.17.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.18.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.15.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.16.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.13.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.14.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.11.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.12.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.11.0, 4.11.1..<4.12.0, 4.12.1..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.9.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.10.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.9.0, 4.9.1..<4.10.0, 4.10.1..<4.11.0, 4.11.1..<4.12.0, 4.12.1..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.7.0 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.8.0 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.7.0, 4.7.1..<4.8.0, 4.8.1..<4.9.0, 4.9.1..<4.10.0, 4.10.1..<4.11.0, 4.11.1..<4.12.0, 4.12.1..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.6.3 depends on 'nuke' 10.0.0..<11.0.0 and 'stream-chat-swiftui' 4.6.4 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.6.3, 4.6.5..<4.7.0, 4.7.1..<4.8.0, 4.8.1..<4.9.0, 4.9.1..<4.10.0, 4.10.1..<4.11.0, 4.11.1..<4.12.0, 4.12.1..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because 'stream-chat-swiftui' 4.6.1 depends on 'nuke' 10.0.0..<11.0.0.
> 'stream-chat-swiftui' {4.0.0..<4.6.1, 4.6.2..<4.6.3, 4.6.5..<4.7.0, 4.7.1..<4.8.0, 4.8.1..<4.9.0, 4.9.1..<4.10.0, 4.10.1..<4.11.0, 4.11.1..<4.12.0, 4.12.1..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} practically depends on 'nuke' 10.0.0..<11.0.0 because no versions of 'stream-chat-swiftui' match the requirement {4.0.0..<4.6.0, 4.6.2..<4.6.3, 4.6.5..<4.7.0, 4.7.1..<4.8.0, 4.8.1..<4.9.0, 4.9.1..<4.10.0, 4.10.1..<4.11.0, 4.11.1..<4.12.0, 4.12.1..<4.13.0, 4.13.1..<4.14.0, 4.14.1..<4.15.0, 4.15.1..<4.16.0, 4.16.1..<4.17.0, 4.17.1..<4.18.0, 4.18.1..<4.19.0, 4.19.1..<4.20.0, 4.20.1..<4.21.0, 4.21.1..<4.22.0, 4.22.1..<4.23.0, 4.23.1..<4.24.0, 4.24.1..<4.25.0, 4.25.1..<4.26.0, 4.26.1..<4.27.0, 4.27.1..<4.28.0, 4.28.1..<4.29.0, 4.29.1..<4.30.0, 4.30.1..<5.0.0} and 'stream-chat-swiftui' 4.6.0 depends on 'nuke' 10.0.0..<11.0.0.
> 
> 
>

**Comment by paulz** [comment]
also allows us avoid old issues with Nuke: https://github.com/kean/Nuke/issues/689

**Comment by martinmitrevski** [comment]
Hi @paulz,

Thanks for reporting. We will analyse the impact of Nuke 12 to our SDK - if there are no breaking API or functionality changes, we could update to the latest version.

We will update you on this ticket when we have more info.

Best, Martin

**Comment by paulz** [comment]
Thank you for looking into this.

**Comment by Sam-Spencer** [comment]
Any updates on plans to support Nuke 12?
