### ISSUE TITLE
XcodeCloud build fails

### ISSUE THREAD

**Issue by zqazi114** [GetStream/stream-chat-swiftui#304]
## What did you do?
My project integrates StreamChat SwiftUI SDK (through Xcode Package Manager). I use CI / CD with XcodeCloud. Until recently I had no issues. But when I submit a build now I get an error that traces to one of the files in StreamChat's SDK.

## What did you expect to happen?
Successful build

## What happened instead?
Error:
Initializer for conditional binding must have Optional type, not 'PHFetchResultCollection'
AttachmentPickerView.swift:75

## GetStream Environment
**GetStream Chat version:** 4.23.0 and main respectively
**GetStream Chat frameworks:** StreamChatSwift, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** swift5

**Xcode version:** 14.2 (14C18)
**Device:** N/a

## Additional context
See image of error att
<img width="919" alt="Screen Shot 2023-04-16 at 12 10 10 AM" src="https://user-images.githubusercontent.com/12015464/232237080-ce3f0a82-6182-49bc-952a-f15394f2a934.png">
ached

**Comment by martinmitrevski** [comment]
Hi @zqazi114,

This build error was happening on Xcode 14.3, but it's already solved in the latest release (4.30.0) and on our `main` branch.

Please update to the latest version and the issue will be solved.

Best, Martin
