### ISSUE TITLE
InputTextView cursor index not set as expected

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#308]
It is incorrect for the text view cursor to be positioned at the beginning of the message when editing.
Rather, the cursor for the text view should be placed at the end of the text.

## GetStream Environment
**GetStream Chat version:** 4.31.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16
**Swift version:** 5
**Xcode version:** 14.2
**Device:** iPhone-X

## Additional context

https://user-images.githubusercontent.com/47667077/234853075-2f6fd130-ca89-47b3-b682-4ae40df125e2.mov

**Comment by martinmitrevski** [comment]
Hi @ajay-simform,

Thanks for reporting, we will look into it.

Best, Martin

**Comment by martinmitrevski** [comment]
This is now fixed and available on our `main` branch.

**Comment by ajay-simform** [comment]
Hi @martinmitrevski ,
Thanks for the update. The applied logic works well with the simple text. But it creates a problem if the text has emoji.

Best, Ajay

https://user-images.githubusercontent.com/47667077/235416286-b3be8287-c5bf-48b1-8c85-b6f9ecf4cccf.mov
