### ISSUE TITLE
make InputTextView customizable

### ISSUE THREAD

**Issue by paulz** [GetStream/stream-chat-swiftui#309]
## What are you trying to achieve?

Change keyboard type from `default` to `.send`

## If possible, how can you achieve this currently?

Tried to use `ViewFactory.makeComposerInputView` but that requires implementing whole `ComposerInputView` with `ComposerTextInputView` and a long chain of dependencies.

## What would be the better way?

```
ViewFactory.makeInputTextView
ViewFactory.makeComposerTextInputView
```

## GetStream Environment
**GetStream Chat version:** 4.3.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.2
**Device:** iPhone

**Comment by martinmitrevski** [comment]
Hi @paulz,

There are two options here, and both have some tradeoffs:
1. We can expose `makeComposerTextInputView`, that's not a problem. However, exposing the `InputTextView` via a public factory method or even a public component is not an option for us, since it's a UIKit component and an implementation detail that we might replace in future versions. If we proceed in this direction, you can use a newly introduced `makeComposerTextInputView`, but you would still need to maintain your version of `InputTextView` by yourself.
2. We can expose the return key type (I assume you meant that one, not the keyboard type), via the `ComposerConfig`. However, I assume you would want to also send a message when that button is tapped, right? In that case, we should also expose a way to implement a delegate method.

In both cases, users won't be able to press return to enter a new row in the composer input view. Is that your desired behaviour?

Looking forward to your feedback.
Best, Martin

**Comment by paulz** [comment]
Thank you @martinmitrevski 

What we trying to achieve is to use "Send" button in iOS keyboard to send message. Understandably we won't allow users have "Enter" key, as we do not need multi line input.

And we would need somehow have ability to disable that "Send" button (ideally we can have control when). Our designer wants to disable send message while another user is typing.

**Comment by martinmitrevski** [comment]
Thanks for providing additional details. In that case, I think it's best to go with the 1st option - expose a `makeComposerTextInputView`, while you create your own version of `InputTextView`. I think you would need to listen to some delegate text view delegate methods to prevent users from sending messages while others are typing, so it's best to have full control over that view.

The typing information is available in the `ChatChannelViewModel`, in particular the `shouldShowTypingIndicator`. One option is to inject the view model from the outside, and provide access to it in the composer / text view too. Another option is to read this info directly from the channel's `currentlyTypingUsersFiltered`.

If this approach works for you, we will expose a new `makeComposerTextInputView`. 
Looking forward to your reply.

**Comment by paulz** [comment]
Thank you @martinmitrevski 

If my questions is already answered in docs, please share a link, trying to understand how to inject models
> One option is to inject the view model from the outside

I see there is a `ViewModelsFactory` and models are open classes, but factory methods are static so how can one override them if there is no instance of `ViewModelsFactory`? We are successfully using `ViewFactory` by creating our factory to conform to `ViewFactory` protocol

For example: https://github.com/GetStream/stream-chat-swiftui/blob/4d7fa3d08de8ce5f955df89f75973f5241d77e3f/Sources/StreamChatSwiftUI/ViewModelsFactory.swift#L51-L60

is used in https://github.com/GetStream/stream-chat-swiftui/blob/4d7fa3d08de8ce5f955df89f75973f5241d77e3f/Sources/StreamChatSwiftUI/ChatChannelList/MoreChannelActionsView.swift#L32-L35

**Comment by martinmitrevski** [comment]
Hey @paulz, 

All the main views init methods (`ChannelListView`, `ChatChannelView`, `MessageComposerView`), have an optional view model parameter, that by default is nil and in that case we create the view model internally.

However, for cases like this, you can instantiate the `ChatChannelViewModel`, and inject it when the channel view is created in the `makeChannelDestination` method, by passing it in the init. You can do it in a similar way for the message composer view, by creating a custom view that will also expect the channel view model created above. For this, you would need to implement the `makeMessageComposerViewType`.

Here's the `ChatChannelView` init for reference:
```swift
    public init(
        viewFactory: Factory,
        viewModel: ChatChannelViewModel? = nil,
        channelController: ChatChannelController,
        messageController: ChatMessageController? = nil,
        scrollToMessage: ChatMessage? = nil
    ) {
        _viewModel = StateObject(
            wrappedValue: viewModel ?? ViewModelsFactory.makeChannelViewModel(
                with: channelController,
                messageController: messageController,
                scrollToMessage: scrollToMessage
            )
        )
        factory = viewFactory
    }
```

Let me know if that helps.

**Comment by martinmitrevski** [comment]
Hey @paulz,

The new `makeComposerTextInputView` method in the view factory is now available on our `main` branch.

Let us know if you need anything else.

Best, Martin

**Comment by paulz** [comment]
Thank you
