### ISSUE TITLE
Make SelectedChannelID a Binding in [ChatChannelListView]

### ISSUE THREAD

**Issue by vincentno1** [GetStream/stream-chat-swiftui#312]
## What are you trying to achieve?

I would love to be able to control which channel is showing. (aka a deep link )
It looks like the variable "selectedChannelID" is designed for this purpose,
how ever it somehow it's not a binding variable.

Is it possible to make this change?
Or there is another way to implement the deep link?
I had go through all the document and examples but can't find any solution.
Thanks!

**Comment by martinmitrevski** [comment]
Hey @vincentno1, 

The `selectedChannelId` is used just for the creation of the chat channel list view. Afterwards, the `@Published` variable called `selectedChannel` in the `ChatChannelListViewModel` should be used for this purpose.

It is provided in some factory methods as a `@Binding`, but if you need it in some other parts of your app, you can instantiate the `ChatChannelListViewModel` and inject it in the list view. With that, you can easily control the `selectedChannel` variable.

Hope that helps.
Best, Martin

**Comment by vincentno1** [comment]
Hi @martinmitrevski ,

Thank you for your rapid reply.
I figured it out with your lead.

Thanks,
Vincent
