### ISSUE TITLE
compiler warning: TwoStepMentionCommand.swift:106:28: empty collection literal requires an explicit type

### ISSUE THREAD

**Issue by paulz** [GetStream/stream-chat-swiftui#313]
Thank you for the stream chat! not a big deal, just triggered a warning on our CI:

## What did you do?
build app with latest SPM package

## What did you expect to happen?
no warnings

## What happened instead?
compiler warning:
> SourcePackages/checkouts/stream-chat-swiftui/Sources/StreamChatSwiftUI/ChatChannel/Composer/Suggestions/InstantCommands/TwoStepMentionCommand.swift:106:28: empty collection literal requires an explicit type
>                     value: []
>                            ^~
> 

## GetStream Environment
**GetStream Chat version:** 4.31
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16
**Swift version:** 5.8
**Xcode version:** 14.3
**Device:** simulator

**Comment by martinmitrevski** [comment]
Hey @paulz,

Thank you for reporting. We will fix it in one of our next releases.

Best, Martin

**Comment by martinmitrevski** [comment]
This is now fixed on our `main` branch and it will be included in the next release.
