### ISSUE TITLE
unreadCountPublisher publishes only an initial value

### ISSUE THREAD

**Issue by ylai-msrl** [GetStream/stream-chat-swiftui#319]
## What did you do?
I wants to get the unread channel counts when have new messages comes. This is the code and I omitted some of the unrelated code.

```
class chat {
    @Published var currentUserController: CurrentChatUserController?
    @Published var channelUnreadCount: Int = 0

    init () {
      self.currentUserController = self.chatClient.currentUserController()
      self.currentUserController?.synchronize()

     self.currentUserController?.unreadCountPublisher
            .receive(on: DispatchQueue.main)
            .sink { [weak self] unreadCount in
                guard let self else {
                    return
                }
                self.channelUnreadCount = unreadCount.channels
            }
            .store(in: &cancelBag)
    }
}
```

## What did you expect to happen?
unread publisher triggered after new messages arrived to let me update unread channel count

## What happened instead?
No triggering of unread publisher after new messages

## GetStream Environment
**GetStream Chat version:** 4.31.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.6.1
**Swift version:** 5
**Xcode version:** Xcode 14.2
**Device:** Iphone 11

## Additional context
Similar issue with https://github.com/GetStream/stream-chat-swift/issues/1447

**Comment by martinmitrevski** [comment]
Hey @ylai-msrl, 

Can you add the completion handler to the synchronize call and make sure that it's invoked. Also, if there's an error there, please share it.

**Comment by ylai-msrl** [comment]
Hello, I am having error of this

![Screenshot 2023-05-24 at 2 23 30 PM](https://github.com/GetStream/stream-chat-swiftui/assets/113869377/449d3fd1-18c7-420d-a55d-19d97db0ad66)

**Comment by martinmitrevski** [comment]
Hello, 

This error means that you call syncronize before you are connected to the chat. Make sure that the completion block of `connect` finishes, and then create this class and call syncronize.

Afterwards, it should work well.

**Comment by ylai-msrl** [comment]
Solved by listening to the variable `connected` which triggered by finishing connect of chat client, then start to synchronize current user, then add unreadCountPublisher, then the publisher will be able to update automatically. Thank you!

```
self.connected
            .receive(on: DispatchQueue.main)
            .sink { [weak self] connected in
                guard let self else {
                    return
                }
                if self.currentUserController != nil, connected ?? false {
                    self.currentUserController?.synchronize { error in
                        if error == nil {
                            self.currentUserController?.unreadCountPublisher
                                .receive(on: DispatchQueue.main)
                                .sink { [weak self] unreadCount in
                                    guard let self else {
                                        return
                                    }
                                    self.channelUnreadCount = unreadCount.channels
                                }
                                .store(in: &self.cancelBag)
                        }
                    }
                }
            }
            .store(in: &cancelBag)
```
