### ISSUE TITLE
When I switch profiles, the channels list lags

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#320]
## What did you do?
When I switch profiles, the channels list lags. See the following video.

https://github.com/GetStream/stream-chat-swiftui/assets/73989872/f109b05f-c95a-48cd-abe9-c17cb6f58e5f

I am using the following code for switching the user from **StreamChat** SDK. First logout the. user from **StreamChat** SDK and then re-connect the user with **StreamChat** SDK.

```Swift
func switchUser(profile: ProfileItem, onComplete: @escaping (()->())){
        chatClient.logout{ [unowned self] in
            let loginData = LoginData(userToken: profile.jwt, supportToken: profile.supportToken, name: profile.username, supportUserID: profile.supportUserId, companyID: nil, companyName: profile.companyName)
            userAuthanticationManager.setUserLoggedInWith(loginData: loginData, isSaveInCoreData: false)
            ChatManager.shared.connectUser {
                onComplete()
            }
        }
    }
```
For connect user, I am using the following code.

```Swift
func connectUser(onComplete: (()->())? = nil) {
        chatClient.connectUser(
            userInfo: .init(
                id: userAuthanticationManager.supportUserId!,
                name: userAuthanticationManager.username),
            token: try! Token(rawValue: userAuthanticationManager.supportToken!)
        ) { error in
            if let error = error {
                print("failed to connect the user with stream \(error)")
            } else {
                logger.info("user connected with the stream sdk", category: .chat)
                self.registerForPushNotifications()
            }
            onComplete?()
        }
    }
```

## What did you expect to happen?
I want the channel list should not lag. 

## What happened instead?
Currently when I switch the user, then channels list lags.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @muhammadabbas001, 

Are you using the same `ChatChannelListView` for the different workspaces? Is the previous view model discarded when you switch the user?

This feels like an issue in your app with some not cleared state, since if you login/logout with different users, the performance is the same, both in our demo app and other customers.

**Comment by martinmitrevski** [comment]
yes, maybe you can try attaching an `id` modifier to the list or the view that contains it, where you will provide the id of the logged in user.

Additionally, are all other dependencies from the `ChatChannelListView` recreated? (the channel list controller, view model)

**Comment by muhammadabbas001** [comment]
@martinmitrevski 
Thanks for your kind support. The lagging issue occurs because my previous view is not being removed from memory. 

I refresh the view by hiding and unhiding the ChatView on the base of the loader when the user update.

```Swift
if !currentReactives.presentFullScreenLoader{
      ChatView(currentReactives: currentReactives)
}
```
