### ISSUE TITLE
Gradient Mask for message bubbles in channel view

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swiftui#326]
## What are you trying to achieve?
We want to be able to apply a gradient to the message bubbles in channels so that the sender's message bubbles appear to change color as they scroll up and down the screen over the gradient. 

Here's a mockup of what we're trying to achieve:

![Screenshot 2023-06-01 at 9 24 37 AM](https://github.com/GetStream/stream-chat-swiftui/assets/17079221/bd48bce6-8a65-4509-9d69-23beab032cf2)

## If possible, how can you achieve this currently?
Not sure. Any advice?

**Comment by martinmitrevski** [comment]
Hey @jfru,

This would require some custom implementation on your end, to use a custom message container view and bubbles.

I've found a possible approach for SwiftUI here: https://stackoverflow.com/questions/60366728/how-to-make-my-objects-in-a-vstack-mask-to-different-full-screen-size-gradients.

Please check it and let us know if we can expose something to help you with it (provided it's not a breaking change in our SDK).

Hope that helps.
Best, Martin

**Comment by jfru** [comment]
We'll check it. Appreciate it.

**Comment by jfru** [comment]
Hi @martinmitrevski - see this message from @chan-reclip who tried and failed to implement:

"Nah… I can't. I indeed need to have ScrollView (or [MessageListView](https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift)) level customisation point.

I could do something similar like below but it seems impossible to clip the bubbles that go out of screen because of the issue I mentioned above. (see bubbles at the bottom)"


https://github.com/GetStream/stream-chat-swiftui/assets/17079221/e5f91953-8f18-4def-a44f-3f48c130c5bd
