### ISSUE TITLE
Gradient Mask in Chat: take 2

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swiftui#327]
I added a comment to this ticket, but it's closed so I'm creating a new issue to make sure it doesn't get missed. 🙏 
Here's the original: https://github.com/GetStream/stream-chat-swiftui/issues/326

**Comment by chan-reclip** [comment]
Just to add a bit more context.

I was trying to implement the right column of https://stackoverflow.com/a/60369498.
The left column can be implement as it is now.

**Comment by martinmitrevski** [comment]
Hey @chan-reclip,

Can you please specify what do you need exposed from the SDK to support the use-case?

**Comment by chan-reclip** [comment]
@martinmitrevski Thanks for the quick response!

It would be perfect if I can provide `ViewModifier` for [this MessageListView instance](https://github.com/GetStream/stream-chat-swiftui/blob/6d96435ddd442ba1fff9b7e5c263e51b13fd0b21/Sources/StreamChatSwiftUI/ChatChannel/ChatChannelView.swift#L46) or [this ScrollView](https://github.com/GetStream/stream-chat-swiftui/blob/6d96435ddd442ba1fff9b7e5c263e51b13fd0b21/Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift#L116) via `ViewFactory`.

We already have [makeMessageListModifier](https://github.com/GetStream/stream-chat-swiftui/blob/6d96435ddd442ba1fff9b7e5c263e51b13fd0b21/Sources/StreamChatSwiftUI/ViewFactory.swift#L202) ([used here](https://github.com/GetStream/stream-chat-swiftui/blob/6d96435ddd442ba1fff9b7e5c263e51b13fd0b21/Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift#L191)) but that one resides inside of the [ScrollView](https://github.com/GetStream/stream-chat-swiftui/blob/6d96435ddd442ba1fff9b7e5c263e51b13fd0b21/Sources/StreamChatSwiftUI/ChatChannel/MessageList/MessageListView.swift#L116), so it can only be used to implement the left column of the above linked StackOverflow answer.

**Comment by martinmitrevski** [comment]
If I understand correctly, you just need a regular `ViewModifier` attached to the top of the `MessageListView` and exposed via the view factory, right?

**Comment by chan-reclip** [comment]
@martinmitrevski Yes, that's correct.

**Comment by martinmitrevski** [comment]
hey @chan-reclip, 

I've added this in a new branch called `messagelist-container-modifier`. Please check if it works for you. 

The modifier is called `makeMessageListContainerModifier()`.

If it's all good, we will merge it in our `main` branch and include it in our next release.

Looking forward to your feedback.

**Comment by chan-reclip** [comment]
@martinmitrevski The change looks perfect. Thanks!

**Comment by martinmitrevski** [comment]
Hi @chan-reclip, great! This is now available in our `main` branch and it will be included in the next release.

**Comment by chan-reclip** [comment]
Awesome, thanks!
