### ISSUE TITLE
Auto Back Navigate in IPad

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#329]
## What did you do?
I implemented the search user screen which is given in the SDK's extra code named "NewChatView". When I click the user and then the user navigates to the ChatView with that user if the channel exists. It's working fine on **iPhone** but it auto-back navigates on **iPad**. 

I am getting the following logs after auto back navigation on **iPad**.
```
2023-06-19 12:55:32.793593-0500 DripJobs Chat[22382:743979] [Text] UITextView 0x7f95398a6600 is switching to TextKit 1 compatibility mode because its layoutManager was accessed. Break on void _UITextViewEnablingCompatibilityMode(UITextView *__strong, BOOL) to debug.
NavigationLink presenting a value must appear inside a NavigationContent-based NavigationView. Link will be disabled.
Query: 
```

I am using the following code for navigating over the **ChatChannelView**. 
```Swift
if viewModel.navigateToChat{
    NavigationLink(
        destination: ChatChannelView(
            viewFactory: CustomChatViewFactory.shared,
            channelController: chatClient.channelController(for: viewModel.selectedChannelId!)
        ),
        isActive: $viewModel.navigateToChat){}
}
```

## What did you expect to happen?
I want when navigating over **ChatChannelView** then not auto-back navigate.

## What happened instead?
It's back navigated automatically. 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @muhammadabbas001,

The "new chat" view works as expected in our demo app (it doesn't go back on iPads). 

This part is anyway outside the SwiftUI SDK and something in your app, therefore I'm closing this issue.

Please check again the code in our demo app.

Best, Martin

**Comment by muhammadabbas001** [comment]
@martinmitrevski One thing more I did not use any NavigationView in my app. Only I am using the NavigationView which is inside the SDK because my app is only based on chat.
