### ISSUE TITLE
Make MessageListDateUtils customizable

### ISSUE THREAD

**Issue by ondrejkorol** [GetStream/stream-chat-swiftui#331]
## What are you trying to achieve?
Hi there, I'm trying to add date indicators within the chat. My goal is to mimic other messaging apps (e.g. Messages, Messenger) which display timestamps between groups of messages.

<img width="247" alt="image" src="https://github.com/GetStream/stream-chat-swiftui/assets/68337693/87d200b7-fa61-4b69-90fb-ecbaac3f598d">

I know Stream Chat offers a way how can we have this behavior by updating `MessageListConfig.dateIndicatorPlacement` to `.messageList`, but it seems that it only displays a date when **a day is different**.

_June 19
messages
June 20
messages_

But most of the messaging apps display these indicators in a matter of hours/minutes (e.g. messages sent after 30/60 minutes)

_June 19, 08:00
messages
June 19, 09:00
messages
June 19, 09:30
messages_

## If possible, how can you achieve this currently?
I'm not aware there is an option to change `.messageList` behavior as we can't change the `MessageListDateUtils` logic.
If I understand correctly, this class is responsible for deciding whether a date indicator should be shown (there is a method that works with `isDifferentDay` property).
`messageListDateUtils` is not a public property in `Utils` class, and it's getting created in its init method without a chance to supply a custom version.

```
func showMessageDate(
        for index: Int?,
        in messages: LazyCachedMapCollection<ChatMessage>
    ) -> Date? {
        guard let index = index else {
            return nil
        }

        let message = messages[index]
        let previousIndex = index + 1
        if previousIndex < messages.count {
            let previous = messages[previousIndex]
            let isDifferentDay = !Calendar.current.isDate(
                message.createdAt,
                equalTo: previous.createdAt,
                toGranularity: .day
            )
            if isDifferentDay {
                return message.createdAt
            } else {
                return nil
            }
        } else {
            return message.createdAt
        }
    }
```

## What would be the better way?
Have a way how we can define a different logic for displaying date indicators, e.g. use `.hour` as a granularity parameter to check whether the message was sent within the same hour. Eventually, we could find a way how to make it even more flexible (e.g. using date components, comparing the number of minutes).
Or are we worried about performance issues?
Curious to hear your thoughts!

## GetStream Environment
**GetStream Chat version:** 4.32.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15+
**Swift version:** 5
**Xcode version:** 14.2

**Comment by martinmitrevski** [comment]
Hi @ondrejkorol,

One option would be to expose a closure in our `MessageListConfig`, where you get the previous and current message and you need to return an optional date. If the date is not nil, it will be presented in the message list.

Sth like this:
```
let date = { previous, current in
       let previousDate = previous.createdAt
       let currentDate = current.createdAt
       // do something with the dates
       if conditionMet {
           return currentDate
       } else {
          return nil
       }  
}
```
How does that sound?

As in performance, I don't really expect any implications, since you will mostly do simple date comparisons we already do.

Best,
Martin

**Comment by ondrejkorol** [comment]
Hi @martinmitrevski ,

this sounds great! As it follows the closure pattern used for other parts of Stream Chat SDK.
So you think this closure would be then integrated into `MessageListDateUtils` `showMessageDate(..)` method .. which can have the default (current) behavior = comparing days. And with this closure, we could use hours/minutes to decide when the date should be returned.
That would be awesome!

**Comment by martinmitrevski** [comment]
Hey @ondrejkorol,

This is now available on our `main` branch. There's a new `dateSeparator` closure in `MessageListConfig`'s `MessageDisplayOptions`, which has the current implementation as the default one.

You can provide your own logic there and have the custom date behaviour you need.

Please look at the default implementation `defaultDateSeparator(message: ChatMessage, previous: ChatMessage) -> Date?` for more details.

Best, Martin

**Comment by ondrejkorol** [comment]
I'm always amazed by the willingness and speed of the Stream Chat team. Thank you so much, Martin, this helped a lot - it works very nicely.
