### ISSUE TITLE
Provide a better way to implement custom LinkAttachmentView

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swiftui#334]
## What are you trying to achieve?

I want to provide a `CustomLinkAttachmentView` for my custom URL while using the existing `LinkAttachmentView` for other URLs such as youtube.com.

Currently, my approach is to override `ViewFactory.makeLinkAttachmentView(...)`:

```swift
class MyCustomViewFactory: ViewFactory {

    // .....

    typealias MessageViewModifier = MyCustomMessageViewModifier
    func makeMessageViewModifier(for messageModifierInfo: MessageModifierInfo) -> MessageViewModifier {
        MyCustomMessageViewModifier(messageModifierInfo: messageModifierInfo)
    }

    @ViewBuilder
    func makeLinkAttachmentView(
        for message: ChatMessage,
        isFirst: Bool,
        availableWidth: CGFloat,
        scrolledId: Binding<String?>,
        onLongPress: Block?
    ) -> some View {
        if message.text.contains("https://custom.url.com/") {
            CustomLinkAttachmentView()
        } else {
            DefaultViewFactory.shared.makeLinkAttachmentView(
                for: message,
                isFirst: isFirst,
                availableWidth: availableWidth,
                scrolledId: scrolledId
            )
        }
    }

    // .....
}
```

Unfortunately, this approach is flawed. Given `DefaultViewFactory.makeLinkAttachmentView()` passes itself as a `viewFactory` to `LinkAttachmentContainer` ([code](https://github.com/GetStream/stream-chat-swiftui/blob/2ec67cb94fecbac7a2e0d3492df2a5ca79da1474/Sources/StreamChatSwiftUI/DefaultViewFactory.swift#L349)), `LinkAttachmentContainer` will not honour our custom `makeMessageViewModifier` implementation ([code](https://github.com/GetStream/stream-chat-swiftui/blob/2cbb9babe49487f65ccc051f20fb43b12c4b4a4d/Sources/StreamChatSwiftUI/ChatChannel/MessageList/LinkAttachmentView.swift#L58-L63)).

## If possible, how can you achieve this currently?

One way to fix this issue is to add a public initializer to the `LinkAttachmentContainer` class so that it can be created on our side, allowing us to pass our custom `ViewFactory` to it.

```swift
class MyCustomViewFactory: ViewFactory {

    // .....

    typealias MessageViewModifier = MyCustomMessageViewModifier
    func makeMessageViewModifier(for messageModifierInfo: MessageModifierInfo) -> MessageViewModifier {
        MyCustomMessageViewModifier(messageModifierInfo: messageModifierInfo)
    }

    @ViewBuilder
    func makeLinkAttachmentView(
        for message: ChatMessage,
        isFirst: Bool,
        availableWidth: CGFloat,
        scrolledId: Binding<String?>,
        onLongPress: Block?
    ) -> some View {
        if message.text.contains("https://custom.url.com/") {
            CustomLinkAttachmentView()
        } else {
            LinkAttachmentContainer(
                factory: self,            // This will be our own MyCustomViewFactory
                message: message,
                width: availableWidth,
                isFirst: isFirst,
                scrolledId: scrolledId
            )
        }
    }

    // .....
}
```

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @chan-reclip,

The public init of `LinkAttachmentContainer` is now available in our `main` branch and it will be included in the next release.

Best, Martin

**Comment by chan-reclip** [comment]
@martinmitrevski Awesome, thanks!
