### ISSUE TITLE
New crash, ChannelsAvatarMerger

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#335]
v 4.33.0

<img width="1147" alt="Screenshot 2023-06-26 at 4 28 14 PM" src="https://github.com/GetStream/stream-chat-swiftui/assets/3814772/1a59cf59-99bb-4fd5-9b00-b9c862da0b07">

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

Are there any reproduction steps for the crash? How often does it happen?

Also, is it possible to get a more detailed crash log?

Thanks, Martin

**Comment by AndrewSB** [comment]
pretty rarely, like .01% of sessions, very intermittent.

sorry i don't have anything else that's useful, no repro steps i know of

**Comment by martinmitrevski** [comment]
We've made the code safer there, so hopefully there won't be any other crashes like this.

If it still happens, please let us know.
