### ISSUE TITLE
Deliver enclosing message's context to the quoted message view container

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swiftui#337]
## What are you trying to achieve?

I want to customise the quoted messages differently based on the quoting (enclosing) message.

## If possible, how can you achieve this currently?

I can't really think of a easier way to do this without breaking existing contract of `ViewFactory`.
If it's ok to break the interface, we can achieve by adding `quotingMessage` to `ViewFactory.makeQuotedMessageView(...)`.

```swift
    func makeQuotedMessageView(
        quotedMessage: ChatMessage,
        quotingMessage: ChatMessage?,       // this can be nil if `isInComposer == true`
        fillAvailableSpace: Bool,
        isInComposer: Bool,
        scrolledId: Binding<String?>
    ) -> QuotedMessageViewType
```

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @chan-reclip,

You can access the parent message's id with the `parentMessageId` property in the `ChatMessage`. You can use that id to find the whole message in your datasource (the `messages` array).

As you already mentioned, we can't really change the interface, since that would be a breaking change.

Hope that helps, Martin

**Comment by chan-reclip** [comment]
Hi @martinmitrevski,

```swift
    /// The ID of the parent message, if the message is a reply, otherwise `nil`.
    public let parentMessageId: MessageId?
```

This comment says it's available if the message is a replay. But in my case, it's the other way around.

<img width="126" alt="Screenshot 2023-06-29 at 7 12 55 pm" src="https://github.com/GetStream/stream-chat-swiftui/assets/128518318/dd83d70b-9295-42f6-8414-007ada38e832">

In the above picture, I want to know about "Quoting" when I draw "Quoted".

Also, from what I tested, `parentMessageId` was always `nil`. Maybe it's a bug?

**Comment by chan-reclip** [comment]
@martinmitrevski In case you missed my comment above. ^^^

**Comment by martinmitrevski** [comment]
Hey @chan-reclip, 

I did some analysis, and unfortunately the only way is to do a breaking change of the factory method. We can't do that at the moment, we can only do it when we have a major version release.

In the meantime, if it's very important to you, you can fork it and update frequently with our `main` branch. That will introduce some maintenance effort on your side though.

If you have any other idea how to improve this w/o a breaking change or a hack, we're open to it.

Best, Martin

**Comment by chan-reclip** [comment]
@martinmitrevski Yeah, I also thought it would be not easy to make such change for a unique use case like this.
No worries, thanks for having a look!
