### ISSUE TITLE
AttachmentTextView does not honour Appearance.fonts

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swiftui#340]
## What did you do?

Customised font via `Appearance`.

## What did you expect to happen?

All messages to have the same body font specified in Appearance.fonts.body.

## What happened instead?

The font is applied to normal message but not to ones with image attachment.

![image](https://github.com/GetStream/stream-chat-swiftui/assets/128518318/2c7b540f-ba8c-4093-b0c7-c68536e5c2bb)
it may be a bit hard to tell but if you look at the individual letter shapes (ones like k, o, and e are more different) you can see that this is another typeface.

Maybe `fonts.body` is missing here: https://github.com/GetStream/stream-chat-swiftui/blob/3159ae656f7c9a81b2e0c88f3ed8ba568bdd3529/Sources/StreamChatSwiftUI/ChatChannel/MessageList/ImageAttachmentView.swift#L90

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by chan-reclip** [comment]
cc @jfru

**Comment by martinmitrevski** [comment]
Hey @chan-reclip,

Thanks for spotting this, it's now fixed.

Best, Martin
