### ISSUE TITLE
XCFramework Distribution

### ISSUE THREAD

**Issue by Sam-Spencer** [GetStream/stream-chat-swiftui#342]
## What are you trying to achieve?
I would like to have a binary distribution / XCFramework distribution of the SwiftUI Stream library. 

## If possible, how can you achieve this currently?
I can compile the XCFramework myself after manually checking for new releases. Unfortunately, this can be pretty time consuming, and I loose the versioning that comes with SPM. Currently, it appears that only the LLC and UIKit libraries are available as XCFrameworks.

## What would be the better way?
The SwiftUI library is available as an XCFramework.

## GetStream Environment
**Swift version:** 5.7
**Xcode version:** 14.3

**Comment by martinmitrevski** [comment]
Hi @Sam-Spencer,

Thanks for reporting. This is already in our roadmap, and it will be probably tackled in one of our next sprints.

We will let you know when it's available.

Best, Martin

**Comment by testableapple** [comment]
Hi @Sam-Spencer,

This should be available starting from our next release (`4.40.0`).

Best wishes,
Alexey
