### ISSUE TITLE
Editing messages causes attachment to disappear.

### ISSUE THREAD

**Issue by sgoodwin** [GetStream/stream-chat-swiftui#345]
## What did you do?

Long-press on a message in chat to edit the message that has an attachment.

## What did you expect to happen?

The message text would be edited and you would continue to see the attachment as well.

## What happened instead?

The message is in fact edited, but then the attachment disappears.

## GetStream Environment
**GetStream Chat version:** StreamChatSwiftUI main, StreamChat 4.34.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.1
**Swift version:** 5.8.1
**Xcode version:** 14.3.1
**Device:** Simulator

## Additional context

We're using the standard chat message list. We are customizing the actual display of the message some via the factory API. In theory that shouldn't affect the existence of an attachment should it?

**Comment by martinmitrevski** [comment]
Hey @sgoodwin,

Thanks for raising the issue. This is a missing feature - we've added editing of attachments in the low-level client (StreamChat) in the previous release, and it will soon come in the SwiftUI SDK. 

We will let you know when this is available.

Best, Martin

**Comment by sgoodwin** [comment]
Hi Martin! In our case we aren't expecting to be able to edit the attachment, but we were expecting to be able to edit the message without losing the attachment.

**Comment by martinmitrevski** [comment]
Exactly, but for that we need to pass the current attachments in the edit message API call, which was not possible until recently. This should solve the issue.

**Comment by sgoodwin** [comment]
Ohhh ok. Thanks!

**Comment by martinmitrevski** [comment]
Hey @sgoodwin,

This is now fixed on our `main` branch, and will be included in our release later this week.

Please let me know if it fixes the issue for you when you have a moment.

Best, Martin

**Comment by sgoodwin** [comment]
Hi Martin,

Glad the change could be made, but it does"t seem to fix the problem. From what I can see it's because the function `toAnyAttachmentPayload` doesn't allow any custom attachment types, so there's an empty array for the messages we're trying to edit.

**Comment by martinmitrevski** [comment]
Sorry, I didn't realize you were using custom attachments. I've exposed a closure to implement this logic in your app, where you can also convert the custom attachments before they are sent for editing.

The closure is called `attachmentPayloadConverter` and it's in `Utils.composerConfig`. If you support the default attachments as well, you can call the default implementation, plus wrap your custom attachments with the `AnyAttachmentPayload` and add them to the array.
```
        let composerConfig = ComposerConfig(attachmentPayloadConverter:  { message in
            var attachments = message.allAttachments.toAnyAttachmentPayload()
            // add the custom attachments here
            return attachments
        })
        let utils = Utils(
            composerConfig: composerConfig
        )
        streamChat = StreamChat(chatClient: chatClient, utils: utils)
```

Hope that solves the issue.

**Comment by sgoodwin** [comment]
That did the trick! Thank you very much.
