### ISSUE TITLE
Video attachment has no sound with Silent Mode On

### ISSUE THREAD

**Issue by ondrejkorol** [GetStream/stream-chat-swiftui#353]
I'm getting reports from users that videos sent via chat sometimes don't have sound. But it turned out the problem is present when people have Silent Mode turned on and don't use external speakers/headphones.
People expect the sound because the "Speaker" icon is visible, but unless people:
- have Silent Mode turned off, or
- there are external speakers/headphones (that work even with Silent Mode),
there is no sound.
![IMG_2729](https://github.com/GetStream/stream-chat-swiftui/assets/68337693/591cade2-c059-49a8-b69e-b20de7322d74)

I'd expect the Video Player should play sound even when the Device has Silent Mode (as that's the behavior adopted by other Messaging apps).

A few observations:
1) It looks like the issue is not reproducible via Simulator - that always work
2) the issue could be only present on iOS 16+ ([Apple Thread](https://developer.apple.com/forums/thread/716019), not sure though!)
3) The fix could be related to enabling `.playback` mode for AVAudioSession (e.g. [this answer](https://stackoverflow.com/a/34735386/6561672))

## GetStream Environment
GetStream Chat version: 4.35.2
GetStream Chat frameworks: StreamChat, StreamChatUI 4.35.2/main
iOS version: 15 – 16.5
Swift version: 5
Xcode version: 14.3.1
Device: doesn't matter

**Comment by martinmitrevski** [comment]
Hi @ondrejkorol,

Thanks for the report and the analysis, we will look into it.

Best, Martin

**Comment by martinmitrevski** [comment]
Hey @ondrejkorol,

This one is fixed on our `main` branch, and it will be included in the next release.

Best, Martin

**Comment by ondrejkorol** [comment]
Now it works even in silent mode! Thanks.

However, if I play a video and close the player, the video is still playing and you can hear the sound. (Not sure if it was caused by the change or if it wasn't noticeable before). The video should stop, right?
