### ISSUE TITLE
Detect message change in MessageComposerView

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#355]
## What did you do?
I am trying to customize the MessageComposerView. I tried to detect the message change like below. 
```Swift
public func makeMessageComposerViewType(
        with channelController: ChatChannelController,
        messageController: ChatMessageController?,
        quotedMessage: Binding<ChatMessage?>,
        editedMessage: Binding<ChatMessage?>,
        onMessageSent: @escaping () -> Void
    ) -> some View {
        return ZStack(alignment: .top){
            MessageComposerView(
                viewFactory: self,
                channelController: channelController,
                messageController: messageController,
                quotedMessage: quotedMessage,
                editedMessage: editedMessage,
                onMessageSent: onMessageSent
            )
            
            if message = messageController?.message?.text {
                Text("Message \(message)")
            }
        }
    }
```

But, **messageController?.message?.text** does not give the updated value when I enter the text. 

## What did you expect to happen?
How to get the updated message text value when the message enters?

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @muhammadabbas001, 

The `MessageComposerView` allows adding your own `MessageComposerViewModel`. The  published `text` property from there is what you need.

So best to create a new view, and add `MessageComposerViewModel` as a StateObject there. You can listen to the `text` property from there.

Best, Martin

**Comment by muhammadabbas001** [comment]
@martinmitrevski Kindly put a code example for how to create a custom ViewModel for observing the message text.
