### ISSUE TITLE
build successful but no simulator.

### ISSUE THREAD

**Issue by nmn28** [GetStream/stream-chat-swiftui#358]
hi, i want to consider this code for an app im building. i downloaded the code and build is successful but no simulator? please let me know if there is a way to fix it. All the best.

**Comment by martinmitrevski** [comment]
Hi,

The SDK is selected as a default target. If you want to run our demo app, you should select that one as a target and run it (see screenshot).

![Screenshot 2023-08-28 at 09 35 57](https://github.com/GetStream/stream-chat-swiftui/assets/2971717/b52e5c41-0a52-4599-b8d2-7f3fb6f779df)

Best,
Martin
