### ISSUE TITLE
Some image attachments have invalid (local) image_url 

### ISSUE THREAD

**Issue by ondrejkorol** [GetStream/stream-chat-swiftui#362]
Hi! Users report that sometimes sending multiple images fails and it results in gray squares.
When I looked into Stream Explorer, I found the problematic message contains multiple image attachments where:
Displayed images have a correct `image_url` set to: `https://ohio.stream-io-cdn.com/...`
But the gray squares (failed uploads) have `image_url` set to:
- `file:///var/mobile/Media/DCIM/112APPLE/IMG_2931.HEIC` (from device)
- `file:///Users/ondrejkorol/Library/Developer/CoreSimulator/Devices/...` (from simulator)

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-09-12 at 11 06 51](https://github.com/GetStream/stream-chat-swiftui/assets/68337693/201e624f-bfda-4af2-b53b-df693f5a0a5b)

<img width="456" alt="image" src="https://github.com/GetStream/stream-chat-swiftui/assets/68337693/1606e32f-7eec-4f1c-8771-d4f9d2686f4f">

I wasn't able to simulate this in SwiftUI example app on the simulator..  so this is probably some misconfiguration on our side? Although I'd appreciate any insights on how could we debug/fix this.

## What did you do?
Select multiple photos from the photo library, send them and:
- turn off mobile data/wifi, or
- close and kill the app

## What did you expect to happen?
I'd expect images that weren't successfully uploaded won't be sent to other users. And the sender would see them in "failed" state or they'd be thrown away.

## What happened instead?
The message containing these wrongly uploaded images was delivered to other people. These images have invalid (local) image_url.

## GetStream Environment
**GetStream Chat version:** 4.36.0
**GetStream Chat frameworks:** StreamChatSwiftUI main
**iOS version:** iOS 15.5 - iOS 17.0
**Swift version:** 5

**Comment by martinmitrevski** [comment]
Hey @ondrejkorol,

Are your users on version 4.34.0 or above? We fixed the ability to retry failed attachments in that release: https://github.com/GetStream/stream-chat-swift/releases/tag/4.34.0.

**Comment by ondrejkorol** [comment]
I was testing it yesterday with 4.36.0 (StreamChat) and the main branch of StreamChatSwiftUI.
The issue is that people can get into this state where the local URL is stored on BE.
I try to send 4 images, one is uploaded and the app is killed -> the message is stored on BE with 3 invalid URLs.

**Comment by martinmitrevski** [comment]
Do they eventually open the app again? Since if they don't, the uploading is not retried anymore.

**Comment by ondrejkorol** [comment]
I get what you mean, but there is a different issue. It's not that the image attachment would end up in a failed state. It's uploaded on BE with the local (temporary) URL, so as a result - other users see gray squares.
E.g. a message with two attachments looks like this: 
<img width="471" alt="Screenshot 2023-09-14 at 11 08 29" src="https://github.com/GetStream/stream-chat-swiftui/assets/68337693/3473bb7f-0f56-43fc-b7a6-d521c91f434f">

And finally, I was able to simulate it in the example SwiftUI app (StreamChat 4.36.0). It's not obvious in the Simulator (because of cache/local storage). But once you try it on a real device, you'll see these broken URLs as well.
I can see errors in logs:
`
Task <5010DF27-CAF3-4235-B369-1B36CEBFC5E6>.<32> finished with error [-1 100] Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSErrorFailingURLStringKey=file:///Users/.../Library/Developer/CoreSimulator/Devices/786FEADC-013B-4B40-8522-EFDEDC6A8A05/data/Media/DCIM/100APPLE/IMG_0008.HEIC, ...
`


See the video:


https://github.com/GetStream/stream-chat-swiftui/assets/68337693/93721928-810e-4cf3-a64d-d81f8997fcba

**Comment by martinmitrevski** [comment]
Thanks for providing additional details. We would need to analyse it a bit. 

We will get back to you when we have updates.

**Comment by martinmitrevski** [comment]
This is fixed in the latest versions of the low-level client.
