### ISSUE TITLE
Channel Members are still visible after leaving a channel

### ISSUE THREAD

**Issue by ondrejkorol** [GetStream/stream-chat-swiftui#365]
Hi. We’re getting reports that sometimes users who left a channel are still visible to other users.
My assumption is that there is some kind of cache issue.

It’s easy to replicate it within the Example app.
You’ll need **two** devices or simulators and pick two random accounts. For example:

As Luke Skywalker
- Create a group chat and add Leia Organa

As Leia O.
- Open the group chat.

If Luke S. leaves the group chat while Leia **has the app open**,
 - he’ll be correctly removed on his device, on BE, and on Leia’s device ✅

If Luke S. leaves the group chat while Leia **has the app closed**,
 - he’ll be correctly removed on his device, on BE, but ✅
 - he’ll stay visible as a channel member on Leia’s device ❌ (`lastActiveMembers` still returns Luke; unless you log out on that device, which clears the cache)

![IMG_3238 2](https://github.com/GetStream/stream-chat-swiftui/assets/68337693/e152d0ac-d02d-4ffc-ab7c-507ca9918534)

## GetStream Environment
**GetStream Chat version:** 4.36.0
**GetStream Chat frameworks:** StreamChatSwiftUI main
**iOS version:** iOS 15.5 - iOS 17.0
**Swift version:** 5

**Comment by martinmitrevski** [comment]
Hey @ondrejkorol,

Thanks for reporting, we will look into it.

Best, Martin

**Comment by laevandus** [comment]
Hi @ondrejkorol This issue is fixed in [4.58.0](https://github.com/GetStream/stream-chat-swiftui/releases/tag/4.58.0) Thank you for reporting it!
