### ISSUE TITLE
Could we add scroll-to-top behavior?

### ISSUE THREAD

**Issue by sgoodwin** [GetStream/stream-chat-swiftui#366]
## What are you trying to achieve?

When showing a channel, we have the ability to scroll to a specific message if we know which message to scroll to, but we'd like to be able to scroll to the first message in a channel when we show a channel (as opposed to the most recent).

## If possible, how can you achieve this currently?

Technically you can do this if you happen to know what the first message is, but a channel controller only knows about the most recent messages initially.

## What would be the better way?

Ideally we'd be able to specify when creating a ChatChannelView that we want it to show first to last instead of showing most recent.

## GetStream Environment
**GetStream Chat version: 4.36.0**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 16+**
**Swift version: 5.9**
**Xcode version: 15**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @sgoodwin,

We don't have support for such feature. As you pointed out, we don't have support for the oldest message. Additionally, our message list doesn't have bi-directional scrolling support.

At the moment, I'm not able to provide any info about when/if this feature would be added in our SDK. 

Best, Martin
