### ISSUE TITLE
Deleted messages state private visibility, yet show to others

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#371]
## GetStream Environment
**GetStream Chat version: Latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 16**
**Swift version: 5.8**
**Xcode version: 14**
**Device: iPhone 13**

## Additional context
![IMG_6625](https://github.com/GetStream/stream-chat-swiftui/assets/69051988/04c8f105-c186-463f-8b4f-e222ceeb829e)
![IMG_6626](https://github.com/GetStream/stream-chat-swiftui/assets/69051988/d4dba301-6dae-4bb3-bec8-804545bd50a9)

**Comment by martinmitrevski** [comment]
Hey @grandsir,

Thanks for reporting, we will look into this.

Best, Martin

**Comment by martinmitrevski** [comment]
Hey @grandsir,

This is now fixed on `main` and it will be included in the next release. Note that the bug was only the visibility of the indicator. If you want to hide the deleted messages for other users, you need to change the value for `deletedMessagesVisibility` in `ChatClientConfig`.
