### ISSUE TITLE
Expose ChatChannelInfoView's subviews 

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#372]
## What are you trying to achieve?
I need to customize the ChatChannelInfoView. So that's why kindly expose the following views.

1. ChannelNameUpdateView
2. ChatInfoMentionText
3. ChannelInfoItemView
4. NavigatableChatInfoItemView
5. NavigatableChatInfoItemView
6. NavigatableChatInfoItemView
7. PinnedMessagesView
8. MediaAttachmentsView
9. FileAttachmentsView

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
We already have these exposed for a while, please update to a newer SDK version.
