### ISSUE TITLE
VideoPlayerView continues to play the video after closing iOS 17.1 (VideoAttachmentView)

### ISSUE THREAD

**Issue by kuserhii** [GetStream/stream-chat-swiftui#390]
## What did you do?
Open the video attachment to full screen and then press the close button

## What did you expect to happen?
VideoPlayerView is closed and the video must stop playing

## What happened instead?
VideoPlayerView is closed but the audio continues playing

## GetStream Environment
**GetStream Chat version: 4.39**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 17.1**
**Swift version: 5**
**Xcode version: 15.0.1**
**Device: iPhone 14**

## Proposed fix
Proposed fix in VideoPlayerView:

Nilify the current item into onDisappear 

```
  public var body: some View {
        VStack {
            GalleryHeaderView(
                title: author.name ?? "",
                subtitle: author.onlineText,
                isShown: $isShown
            )
            VideoPlayer(player: avPlayer)
            Spacer()
            HStack {
                ShareButtonView(content: [attachment.payload.videoURL])
                    .standardPadding()

                Spacer()
            }
            .foregroundColor(Color(colors.text))
        }
        .onAppear {
            try? AVAudioSession.sharedInstance().setCategory(.playback, options: [])
            avPlayer.play()
        }
         .onDisappear {
            avPlayer.replaceCurrentItem(with: nil)
        }
    }
```

Here we add 

```
.onDisappear {
     avPlayer.replaceCurrentItem(with: nil)
}
```

**Comment by ondrejkorol** [comment]
Noticed the same issue: https://github.com/GetStream/stream-chat-swiftui/issues/353

**Comment by martinmitrevski** [comment]
Hey @kuserhii,

Thanks for reporting and for the proposed fix. We've applied this change on our `main` branch and it will be included in the next release.

Best, Martin
