### ISSUE TITLE
Recently-saved images to camera roll doesn't show up

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#396]
## What did you do?
- Opened the app - minimized it down (didn't close it)
- Saved a photo someone sent me from iMessage to my camera roll
- Opened a chat
- Opened up camera roll to send a photo
- Can't see that recently saved photo

## GetStream Environment
**GetStream Chat version:Latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:iOS 15**
**Swift version:5.9**
**Xcode version:15**
**Device:iPhone 11**

**Comment by martinmitrevski** [comment]
Hey @grandsir,

Thanks for reporting. This is now fixed and it will be included in the release in the next few days.

Best, Martin
