### ISSUE TITLE
Scrolling through media crashes app

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#397]
## GetStream Environment
**GetStream Chat version: Latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 15**
**Swift version: 5.9**
**Xcode version: 15**
**Device:iPhone 11**

## Additional context
I tried on a different device, it didn't crash. But it was really slow in there as well.

https://github.com/GetStream/stream-chat-swiftui/assets/69051988/f18f5bf5-0d99-4009-9f6b-f02247974006

**Comment by martinmitrevski** [comment]
Hey @grandsir,

Thanks for reporting. Is this happening consistently on the same device? If yes, do you have any additional stack trace that you could share with us? 

Also, are you doing some customizations in this part?

**Comment by grandsir** [comment]
There are no customizations on this part. Crash does not occur frequently but slowness occurs almost on every device.

**Comment by martinmitrevski** [comment]
Hey @grandsir,

This is now improved on our `main` branch, and it will go into the next release.

Best, Martin
