### ISSUE TITLE
New messages marked read while the app is in the background

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swiftui#399]
## What did you do?

1. Enter into a chat thread.
2. Background the app.
3. Receive a new chat message to the chat thread.

## What did you expect to happen?

The app icon shows a unread badge. (The unread badge is wired to `CurrentChatUserController.unreadCountPublisher`)

## What happened instead?

The unread badge briefly appears and then disappears.
The debugger shows that the newly arrived message was marked read while the app is in the background.

## GetStream Environment
**GetStream Chat version:** 4.40.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.0.3
**Swift version:** 
**Xcode version:** 15.0.1
**Device:** iPhone 12 mini

## Additional context

- I am aware of https://github.com/GetStream/stream-chat-swift/issues/2826 and hoped it would fix this issue but it didn't work for us.
- I also noticed there are lines of code that seem to address this issue: https://github.com/GetStream/stream-chat-swiftui/blob/833a1db6c47cbf2f291e6d052b174884bf7d7cfc/Sources/StreamChatSwiftUI/ChatChannel/ChatChannelView.swift#L167-L173
  This, again, doesn't work for us. Not sure why but `onChange` never gets called.

Instead, I have a fix which works for us but I'm not too sure if that's a right fix. I want you guys to have a look: https://github.com/GetStream/stream-chat-swiftui/pull/398 (The code is proven to work and the PR was intensionally left in Draft state.)

**Comment by martinmitrevski** [comment]
Hey @chan-reclip,

Thanks for reporting and providing a PR. This is actually not related to the presentation mode, but to when mark read should be called. 

I've fixed the issue and it's available on our `main` branch. It will be released in the next few days.

Best, Martin

**Comment by chan-reclip** [comment]
@martinmitrevski Awesome, thanks!
