### ISSUE TITLE
BUG - Quoted Message with Custom Attachment Shows Blank

### ISSUE THREAD

**Issue by mikaelacaron** [GetStream/stream-chat-swiftui#400]
## What did you do?
Reply to a message who's only content is a custom attachment, without text.

## What did you expect to happen?
See the custom attachment message as part of the reply in the quoted message and the composer

## What happened instead?
When replying to a message with a custom attachment (that has no text), the quoted message is shown as empty, rather than showing the custom attachment

## GetStream Environment
**GetStream Chat version:** the latest version
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** iOS 17.0
**Swift version:** 5.9
**Xcode version:** 15.0
**Device:** iPhone 15 Pro (but also seen on other devices)

## Additional context
I've fixed this on my [fork](https://github.com/mikaelacaron/stream-chat-swiftui/tree/quoted-message-attachment-fix) but it isn't ready for a PR yet

In the `QuotedMessageView` checking for `hasCustomAttachment` and returning a new factory method I created called `makeCustomAttachmentQuotedViewType`

**Comment by mikaelacaron** [comment]
It is up to you all! 👍 I haven't written tests for this yet and I haven't updated the docs for it

**Comment by martinmitrevski** [comment]
We can pick this up internally to wrap things up, no worries 👍

**Comment by martinmitrevski** [comment]
This is now available on our `main` branch and it will be released soon. 

The method would be called `makeCustomAttachmentQuotedView(for message: ChatMessage)`. 

Thanks again for reporting and proposing the fix!

**Comment by mikaelacaron** [comment]
I'll try to get the PR up by this week

**Comment by martinmitrevski** [comment]
it's actually already included, you would just need to update to our latest version (today or tomorrow). We had to speed this one up, since we are releasing today.
