### ISSUE TITLE
Navigation bar in Channel loading state

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swiftui#408]
## What are you trying to achieve?
Hello, I've modified the makeChannelHeaderViewModifier method to have my own navigationBar, but it's not displayed when the channel loads, so if there's a problem during loading I'm potentially stuck on the loading page.

## If possible, how can you achieve this currently?
I've tried playing with controller.synchronize to display a navigation bar as long as I don't have the synchronize callback, but I'm having trouble with duplicating elements in my toolbar once it is loaded.

## What would be the better way?
Apply makeChannelHeaderViewModifier in the loading state too.

## GetStream Environment
**GetStream Chat version: 4.41.0**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hey @BarragaoA,

Can you explain in more details what's the issue? The `makeChannelHeaderViewModifier` needs a channel to show the information presented there - the loading view is displayed only when the channel is not loaded.

In that case, the default navigation bar back button is shown, so you can leave the screen (see screenshot).

![Simulator Screenshot - iPhone 15 Pro - 2023-12-12 at 15 38 59](https://github.com/GetStream/stream-chat-swiftui/assets/2971717/4d8fd2ee-edc6-4400-b8e1-a98d27c3a16a)

**Comment by BarragaoA** [comment]
I'm still new to SwiftUI, maybe I'm doing something wrong.
I open my channel page in a sheet (in modal) 
```
.fullScreenCover(isPresented: $viewModel.chatDetailDisplayed, content: {
            NavigationView{
                ChatDetailView(channelId: viewModel.channelId,
                               isPresented: $viewModel.chatDetailDisplayed)
            }.navigationTitle("")
        })
```
        
In ChatDetailView I display ChatChannelView :
`ChatChannelView(viewFactory: ChatDetailFactory(isPresented: $isPresented), channelController: viewModel.chatController!)`

And here's my ChatDetailFactory :

```
class ChatDetailFactory: ViewFactory {
    @Injected(\.chatClient) public var chatClient
    @Binding var isPresented: Bool
    
    init(isPresented: Binding<Bool>) {
        self._isPresented = isPresented
    }
    
    func makeChannelHeaderViewModifier(for channel: ChatChannel) -> some ChatChannelHeaderViewModifier {
        CustomChatChannelModifier(channel: channel, isPresented: $isPresented)
    }
}

struct CustomChatChannelModifier: ChatChannelHeaderViewModifier {
    var channel: ChatChannel
    @Binding var isPresented: Bool

    func body(content: Content) -> some View {
        content.toolbar {
            CustomChatChannelHeader(channelName: channel.name ?? "Unknown") {
                isPresented = false
            }
        }.setTealishNavBar()
    }
}

struct CustomChatChannelHeader: ToolbarContent {
    var channelName: String
    var onTapTrailing: () -> ()

    var body: some ToolbarContent {
        ToolbarItem(placement: .principal) {
            Text(channelName)
        }
        ToolbarItem(placement: .destructiveAction) {
            Button {
                onTapTrailing()
            } label: {
                Image.quit
                    .resizable()
            }
        }
    }
}
```

During loading I can not see any close button just a white page with the loader. Maybe It is beaucoup of the way I display it ?

**Comment by BarragaoA** [comment]
I find a way to do what I wanted.
I apply my modifications directly to the channelView and I remove it from the channelModifier.

```
channelView.toolbar {
            CustomChatChannelHeader(channelName: viewModel.channelName) {
                isPresented = false
            }
        }
        .setTealishNavBar()
```

```
class ChatDetailFactory: ViewFactory {
    @Injected(\.chatClient) public var chatClient
    @Binding var isPresented: Bool
    
    init(isPresented: Binding<Bool>) {
        self._isPresented = isPresented
    }
    
    func makeChannelHeaderViewModifier(for channel: ChatChannel) -> some ChatChannelHeaderViewModifier {
        CustomChatChannelModifier(channel: channel)
    }
}

struct CustomChatChannelModifier: ChatChannelHeaderViewModifier {
    var channel: ChatChannel
    
    func body(content: Content) -> some View {
        content
    }
}


```

**Comment by martinmitrevski** [comment]
glad to hear that 👍 Closing this one.
