### ISSUE TITLE
Archiving chats

### ISSUE THREAD

**Issue by arnav-webknot** [GetStream/stream-chat-swiftui#409]
## What are you trying to achieve?
We can archive chats and they will go in another folder or some other list controller.

## If possible, how can you achieve this currently?
Not possible

## What would be the better way?
Make two controllers, one will be primary and other will be archived. And just move the channel to archive controller list. 

## GetStream Environment
**GetStream Chat version:*4.44.0*
**GetStream Chat frameworks:*StreamChatUI SwiftUI*
**iOS version:*iOS 17.0*
**Swift version:*5.9*
**Xcode version:*15.0*
**Device:*iPhone 15 Pro*

**Comment by martinmitrevski** [comment]
Hey @arnav-webknot,

You can pass extra data in your channel when you archive it (e.g. archive = true), and then use that as a filter for the 2 different channel list controllers.

Relevant links: 
Updating a channel partially: https://getstream.io/chat/docs/ios-swift/channel_update/?language=swift
Filtering by extra data: https://getstream.io/chat/docs/sdk/ios/client/controllers/channels/#filtering-with-extra-data

Hope that helps,
Martin
