### ISSUE TITLE
Chat Input Border on edit

### ISSUE THREAD

**Issue by borut-t** [GetStream/stream-chat-swiftui#410]
## What are you trying to achieve?
I need to support two states for the border on the chat input view. I've used `colorPallete.innerBorder` so far to set border for the input view. However, I would like to change border to different color as soon as user starts editing/typing the message.

## If possible, how can you achieve this currently?
Completely rewrite the `ComposerInputView`.

## What would be the better way?
Since I don't want to build the whole input view from scratch just to support that, I was wondering if there is an option you can add a configuration for that as well?

## GetStream Environment
**GetStream Chat version:** 4.45.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17
**Swift version:** 5.9
**Xcode version:** 15.x
**Device:** iPhone

**Comment by martinmitrevski** [comment]
Hey @borut-t,

So basically you want to have different border color depending on whether there's a text or not?

**Comment by borut-t** [comment]
@martinmitrevski not really. I want to have different state when input has focus. So I soon as keyboard is on, I need to paint the border differently compared to when keyboard is hidden.

**Comment by martinmitrevski** [comment]
Hey @borut-t,

We have exposed `composerInputHighlightedBorder` in the `ColorPalette` for this on our `main` branch, that's going to be included in the next release.

Its default value is the same as the `innerBorder`.

Best, Martin

**Comment by borut-t** [comment]
That's a great news 🙌
