### ISSUE TITLE
Cannot eliminate chat input view safe area

### ISSUE THREAD

**Issue by borut-t** [GetStream/stream-chat-swiftui#411]
## What did you do?
```swift
var body: some View {
  if viewModel.isChatReady, let controller = viewModel.channelController {
    ChatChannelView(
      viewFactory: MyChatViewFactory(),
      channelController: controller
    )
    .background(.red)
  } else {
    VStack {
      Spacer()
      ProgressView()
      Spacer( )
    }
  }
}
```
<img width="458" alt="Screenshot 2023-12-18 at 11 01 11" src="https://github.com/GetStream/stream-chat-swiftui/assets/677166/4ea13995-a2a2-402a-8f51-d58a6ef90c58">

## What did you expect to happen?
Spacing between tabBar and message input view shouldn't be there.

## What happened instead?
Extra spacing.

## GetStream Environment
**GetStream Chat version:** 4.45.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17
**Swift version:** 5.9
**Xcode version:** 15.x
**Device:** iPhone

**Comment by martinmitrevski** [comment]
Hey @borut-t,

Thanks for reporting, we will look into this. 

Best, Martin

**Comment by martinmitrevski** [comment]
Hey @borut-t,

We actually already have a way to disable tabbar handling via the message list config.

```swift
let utils = Utils(messageListConfig: MessageListConfig(handleTabBarVisibility: false))
let streamChat = StreamChat(chatClient: chatClient, utils: utils)
```

With this setup, and your sample code, there's no more extra spacing on my setup.

Let me know if that fixes it for you as well.

Best, Martin

**Comment by borut-t** [comment]
Nice one. Didn't know it exists. Thanks 🙌
