### ISSUE TITLE
Is channel pagination working well ?

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swiftui#416]
## What did you do?
I try to display all my channels, but as soon as there are more than 30 they don't all appear.
I try set a page size to 200 but it only return me the 30 first channels.
I try to paginate 3 by 3 to see what happen but I only get the 3 first channels. I do not know what happen.

Here's my code :
`ChatChannelListView(viewFactory: SPChannelListFactory(), channelListController: viewModel.listController)`

```
let listController = chatClient.channelListController(
            query: .init(filter: .and([.equal(.type, to: .messaging), .containMembers(userIds: [currentId])]),
                         sort: [.init(key: .lastMessageAt, isAscending: false)],
                         pageSize: 200 )) // I tried 3
```

```
class SPChannelListFactory: ViewFactory {
    @Injected(\.chatClient) public var chatClient
    
    func makeChannelListItem(channel: ChatChannel, channelName: String, avatar: UIImage, onlineIndicatorShown: Bool, disabled: Bool, selectedChannel: Binding<ChannelSelectionInfo?>, swipedChannelId: Binding<String?>, channelDestination: @escaping (ChannelSelectionInfo) -> ChatChannelView<SPChannelListFactory>, onItemTap: @escaping (ChatChannel) -> Void, trailingSwipeRightButtonTapped: @escaping (ChatChannel) -> Void, trailingSwipeLeftButtonTapped: @escaping (ChatChannel) -> Void, leadingSwipeButtonTapped: @escaping (ChatChannel) -> Void) -> some View {
        ChatCustomListItem(viewModel: ChatCustomListItemVM(chatChannel: channel))
    }
}
```

## GetStream Environment
**GetStream Chat version: 4.41.0**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hey @BarragaoA,

The maximum allowed limit of channels is 30, as described here: https://getstream.io/chat/docs/ios-swift/query_channels/?language=swift.

If you send a bigger value than that, it will always return 30. 

Setting a too small value like 3 can also be unpredictable, since the `onAppear` from SwiftUI would be called immediately for all cells, which might have an impact on the pagination.

Hope that helps, 
Martin
