### ISSUE TITLE
Unread counter isn't working

### ISSUE THREAD

**Issue by arnav-webknot** [GetStream/stream-chat-swiftui#417]
## What did you do?
I tried using the built in functionality of unread count of a chat controller but that keeps returning zero. 

Source: https://getstream.io/chat/docs/sdk/ios/common-content/reference-docs/stream-chat-ui/chat-channel-list/chat-channel-unread-count-view/

## Alternative approach I am doing
```
if let controller = streamHelperVM.programChatController {
    controller.synchronize()
    streamHelperVM.programChannelUnreadChat = 0
    for channel in controller.channels {
        if channel.isUnread {
            streamHelperVM.programChannelUnreadChat += 1
        }
    }
}
```
Unfortunately this approach leads into getting too many request error 429 (https://getstream.io/chat/docs/ios-swift/api_errors_response/?language=swift) and streamchat completely stops working for a solid minute.

## What did you expect to happen?
The function should provide the correct count of the unread badge and should update automatically when the controller updates. 

## What happened instead?
It keeps on returning zero

## GetStream Environment
**GetStream Chat version: *4.45.0*
**GetStream Chat frameworks: *StreamChatSwiftUI*
**iOS version: *iOS 17*
**Swift version: *Swift 5.5*
**Xcode version: *Xcode 15.0*
**Device: *All*

**Comment by martinmitrevski** [comment]
Hey @arnav-webknot,

The component you linked is from the legacy SwiftUI wrappers of the UIKit SDK. I assume you are using the SwiftUI SDK instead - in that case you shouldn't use that component.

Going back to the issue - if you want to get the whole unread count for the user, you can use the `CurrentChatUserControllerDelegate` as described here.

From the code snippet, I assume you want to get it only for a particular "program", right? In that case, iterating through the channels shouldn't cause 429s, unless you invoke the code too many times. 

The chunk you provided should be called only one time (the `synchronize` part), when you setup your view (i.e when your "program" is selected). Then, for updates, you rely on the delegate methods of the channel list controller (or the combine publishers):

```swift
func controller(
        _ controller: ChatChannelListController,
        didChangeChannels changes: [ListChange<ChatChannel>]
    ) {
          // here you get the updated list of channels.
         //  you should do the computation of the unread count here.
    }
```

With that, you only have one request to start watching the channels, and then you rely on WebSocket events to compute updates.

Hope that helps,
Martin
