### ISSUE TITLE
Facing too many request error when fetching chat controllers. Need a better approach.

### ISSUE THREAD

**Issue by arnav-webknot** [GetStream/stream-chat-swiftui#418]
## Quick overview of chat in my app
I have multiple programs in my app. Each program has its own individual network chats as well as a common program chat. 
So for example:
I am in 8 programs, and each program has an average of 4 networks and one common program chat. That would be 5 individual chat controller requests on my home page when a particular program is selected. 

#### Home Screen and Program Switcher
<img width="250" alt="Home screen" src="https://github.com/GetStream/stream-chat-swiftui/assets/141209044/3cd87a8e-5708-4fc2-b5fc-a3d1adcd3509"> <img width="250" alt="Program Switcher" src="https://github.com/GetStream/stream-chat-swiftui/assets/141209044/94959dff-6184-49e1-a38c-0ed8810c80ca">

#### Chat Page
<img width="250" alt="Chat Page" src="https://github.com/GetStream/stream-chat-swiftui/assets/141209044/c963f973-c5a6-4b4a-a543-ca1d32e48894">

## My approach for fetching channels
I am having an on appear modifier on home screen which fetches the controllers of each and every network and a program chat along with their unread count.
And in program switcher, each cell has on appear which fetches all the controllers in the program gives an unread count. 

Code for fetching controllers:
```
func getProgramChannelController(programID: String) {
    DispatchQueue.main.async {
        guard let controller = StreamChatViewModel.shared.programChannelListController(withProgramId: programID, isArchived: self.activateArchivingFeature ? false : nil) else { return }
        controller.synchronize { [weak self] error in
            guard let self = self else { return }
            if let error {
                print("STREAM ERROR", error.localizedDescription)
            } else {
                self.programChatController = controller
            }
        }
    }
}
    
func getAllNetworkChatController(programID: String, profileID: Int) {
    fetchNetworks(profileID: profileID) { networks in
        for network in networks {
            guard let controller = StreamChatViewModel.shared.channelListController(withNetworkId: network.id, withProgramId: programID, isArchived: self.activateArchivingFeature ? false : nil) else { return }
            controller.synchronize { [weak self] error in
                guard let self = self else { return }
                if let error {
                    print("STREAM ERROR", error.localizedDescription)
                } else {
                    let networkForChatModel = NetworkForChatModel(network: network, chatController: controller)
                    self.allNetworkControllers.append(networkForChatModel)
                }
            }
        }
    }
}
```

Code for unread counter:
```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
  guard let controller = StreamChatViewModel.shared.unreadCount(programID: self.programId) else { return }
  controller.synchronize { error in
      if let error {
          print(error.localizedDescription)
      } else {
          for channel in controller.channels {
              if channel.isUnread {
                  self.notificationCount += 1
              }
          }
      }
  }
}
```

## GetStream Environment
**GetStream Chat version: 4.45.0**
**GetStream Chat frameworks: StreamChatSwiftUI**
**iOS version: iOS 17**
**Swift version: Swift 5.5**
**Xcode version: Xcode 15.0**
**Device: All**

**Comment by martinmitrevski** [comment]
Hey @arnav-webknot,

Let me first summarize the use-case of your app and how I think it should work, to make sure I understand it correctly:
- first 2 screens are your app-specific logic.
- when you tap on a program, you load 2 channel list controllers - one for "network" and one for "program channels". 
- For those, you have a custom UI that utilizes the channel list controller.
- On tap, you open (most likely) the `ChatChannelView` from the SDK that requires a channel controller.

```
I am having an on appear modifier on home screen which fetches the controllers of each and every network and a program chat along with their unread count.
```
This is very expensive and not recommended. It fires too many requests at the same time.

To avoid having too many requests, the lifetime of your list controllers should be scoped to when a program is selected. Therefore, only 2 channel list controllers at a time. The channel controllers are created when a channel is selected, so there should be only one live at any moment.

From what I see, you cache the controllers, if I'm not mistaken (`allNetworkControllers` array) - their lifetime should be tied to a program.

Another expensive thing you do is the unread count - you shouldn't be creating a new controller for this. You should re-use the same controller you already have to iterate through the channels. Having 2 list controllers of the same query can have unpredictable behaviour.

Every call to `synchronize` starts watching the channels that are in the controller. In this case, that's not needed for the way your app is structured.

Hope that helps.

Martin

**Comment by arnav-webknot** [comment]
Is there any way to filter the controller once again after I have fetched it once?

**Comment by martinmitrevski** [comment]
What do you mean by filter? When you create the controller, you specify a query (e.g. give me channels where I'm member of, with the program = "some program"), and when there are changes to the channel list (new channels, unread count changes, etc), you receive those updates via the delegate methods:
```swift
    func controller(
        _ controller: ChatChannelListController,
        didChangeChannels changes: [ListChange<ChatChannel>]
    )
```

**Comment by arnav-webknot** [comment]
So what I mean by filter is that. Let's say I fetch a controller which belongs to one specific program. Then on another screen, I wanna show different lists according to their custom properties i.e. network id or something else.

**Comment by martinmitrevski** [comment]
If the query is different, you should create a new controller. If the previous one is not active on that new screen (E.g. you switch programs), you should deallocate it for performance reasons (not to receive web socket events when you don't need them).
