### ISSUE TITLE
Nothing happens on clicking message commands button in message composer

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-swiftui#42]
## What did you do?
I am using latest master branch via SPM. Clicking on the thunder icon for message commands does not present the commands dialog, it just shows as the commands button in blue color as selected. The same scenario is reproducible in the latest demo app as well.

## What did you expect to happen?
To open a diaslog where user can select a message commad to run

## What happened instead?
The message commad icon's color is changed to `blue` and no dialog is shown.

## GetStream Environment
**GetStream Chat version:** Using from master branch
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 14.8.1
**Swift version:** Swift 5
**Xcode version:** 13.2.1
**Device:** iPhone 11

**Comment by martinmitrevski** [comment]
Hey @JayMehta97,

Thanks for reporting this. It was indeed a regression with the previous commit. It's fixed now again and the commands popup appears.

Best,
Martin

**Comment by JayMehta97** [comment]
Hey @martinmitrevski , 

Thanks for the quick fix, its working now.
