### ISSUE TITLE
Support for async completion for token provider

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-swiftui#421]
It would be nice to use an async token provider vs the synchronise version that we have.

**Comment by martinmitrevski** [comment]
Hi @rlee1990,

Can you please clarify what you mean? The token provider is already asynchronous:

```swift
public typealias TokenProvider = (@escaping (Result<Token, Error>) -> Void) -> Void
```

If your request is to use Swift Concurrency (async/await), then you can wrap this callback with checked continuations: https://www.hackingwithswift.com/quick-start/concurrency/how-to-use-continuations-to-convert-completion-handlers-into-async-functions.

Hope that helps.

**Comment by rlee1990** [comment]
@martinmitrevski no this does not help. I have an async function that returns the token
```let tokenData = await FunctionsService().GetStreamToken(userId: user!.id)```
I created this function below to use for the token provider
```
func loadChatToken(completion: @escaping (Result<Token, Error>) -> Void) async {
        do {
            let tokenData = await FunctionsService().GetStreamToken(userId: user!.id)
            let token = try Token(rawValue: tokenData)
            completion(.success(token))
        } catch {
            completion(.failure(error))
        }
    }
```

I get this error ```Cannot pass function of type '(@escaping (Result<Token, any Error>) -> Void) async -> ()' to parameter expecting synchronous function type```

**Comment by rlee1990** [comment]
@martinmitrevski any more information on this?
