### ISSUE TITLE
audio session hijack when backing out from a thread into the inbox

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#423]
## What did you do?

upgraded from 4.40.0 to 4.47.0

## What did you expect to happen?

no changes with the audio session

## What happened instead?

now, when exiting a thread and going back to the inbox, our audio session gets hijacked and our app's recording functionality gets turned off

## Additional context

i haven't looked deeply into the changes between 4.40.0 -> 4.47.0, but i saw a mention of a Video SDK, so i thought i'd ask before i started debugging further/doing a bisect of your repository to see when the functionality broke for our app

any ideas why this might be happening? PS: this may belong on the core stream-chat-swift SDK but wasn't sure

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, 

We recently introduced async voice messages: https://getstream.io/chat/docs/sdk/ios/swiftui/voice-recording/. This feature is disabled by default, but it might impact you in some way. 

Based on the flow you described (breaks only after leaving a channel), I applied a possible fix on our `main` branch. Can you please check if that fixes the issue for you?

If not, we would need more details (e.g. some logs) to debug this further.

In any case, this is not connected to our Video SDK - that one is a separate product with no dependency to chat.

**Comment by AndrewSB** [comment]
yup, `main` works, can we get that into a release?

**Comment by AndrewSB** [comment]
also getting 4.49.0 of the core SDK would be nice in that release
