### ISSUE TITLE
Enable customization of SearchResultsView

### ISSUE THREAD

**Issue by kirsanov-dev** [GetStream/stream-chat-swiftui#426]
## What are you trying to achieve?

We are looking to enhance the user experience in the app by adding a custom empty view for searches that return no results within the ChatChannelListView component on iOS (SwiftUI version).

## If possible, how can you achieve this currently?

Currently, there doesn't seem to be a straightforward way to implement this due to the complex nature of the ChatChannelListView component, which is deeply integrated with a lot of internal methods and properties not designed for customization.

## What would be the better way?

The ideal solution would be to allow override the default SearchResultsView or at least its EmptyView by adding a viewFactory.makeChannelListSearchResultsEmptyView or  viewFactory.makeChannelListSearchResultsView methods as it's done for some components.

## GetStream Environment
**GetStream Chat version:**
latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
14+
**Swift version:**
5.5+
**Xcode version:**
14.0.1+
**Device:**
iPhone only

**Comment by martinmitrevski** [comment]
Hey @kirsanov-dev,

Yes, it makes sense to improve the customization of the search results view. We're going to expose a method for the whole search results view, you can handle the empty state differently in your custom implementation.

Follow this PR for updates: https://github.com/GetStream/stream-chat-swiftui/pull/428.

Best, Martin
