### ISSUE TITLE
Support for async completion for token provider

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-swiftui#427]
I have an async function that returns the token
let tokenData = await FunctionsService().GetStreamToken(userId: user!.id)
I created this function below to use for the token provider

```
func loadChatToken(completion: @escaping (Result<Token, Error>) -> Void) async {
        do {
            let tokenData = await FunctionsService().GetStreamToken(userId: user!.id)
            let token = try Token(rawValue: tokenData)
            completion(.success(token))
        } catch {
            completion(.failure(error))
        }
    }
```

I get this error Cannot pass function of type '(@escaping (Result<Token, any Error>) -> Void) async -> ()' to parameter expecting synchronous function type

ChatClient.shared.connectUser(userInfo: .init(id: cUser.id.uuidString.lowercased(), name: cUser.socialInfo.username, imageURL: cUser.profilePhoto.url, extraData: ["blurHash": .string(cUser.profilePhoto.blurHash)]), tokenProvider: loadChatToken)

**Comment by martinmitrevski** [comment]
Hi @rlee1990,

As already mentioned, you can wrap the async method in a task and use it in the token provider.

```swift
Task {
         await loadChatToken(completion: completion)
}
```

One note - please use our support channel for integration questions, the issue reporting here is only for bugs. Link to our support channel: https://support.getstream.io/hc/en-us.

Best, Martin
