### ISSUE TITLE
User is able to send blank message

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-swiftui#43]
## What did you do?
Type one or multiple spaces in the message input box and the send button would get enabled and clicking on it will send the empty message.

## What did you expect to happen?
If there are only blank spaces in the message input bar then the send button should stay disabled.

## GetStream Environment
**GetStream Chat version:** From `main` branch
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 14.8.1
**Swift version:** Swift 5
**Xcode version:** 13.2.1
**Device:** iPhone 11

**Comment by martinmitrevski** [comment]
Thanks @JayMehta97 for reporting this. It was a quick fix and this is now available on `main`.

**Comment by JayMehta97** [comment]
Hey @martinmitrevski,

Thanks for the quick fix, its working now.
