### ISSUE TITLE
Issue scrolling UP when presenting the ChatChannelView as a .sheet

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swiftui#434]
## What did you do?
* Present the ChatChannelView as a .sheet (not full presentation)
* When at the bottom of the list do a long scroll **up**

## What did you expect to happen?
* Nothing

## What happened instead?
* It start to trigger the dismiss like if i'm scrolling down. Which is forcing me to present it as a .fullScreenCover to avoid the issue

## GetStream Environment
**GetStream Chat version:** 4.48.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.2
**Swift version:** 5.x
**Xcode version:** 15.2
**Device:** iPhone 11 pro and Simulator iPhone 15 Pro

## Additional context

https://github.com/GetStream/stream-chat-swiftui/assets/1914557/34708989-0bf2-41f9-bddb-602188612d76

**Comment by martinmitrevski** [comment]
Hi @fceldeiro,

This is a known issue, mostly around limitations in the available SwiftUI APIs by Apple:
- https://github.com/GetStream/stream-chat-swiftui/issues/374
- https://github.com/GetStream/stream-chat-swiftui/issues/253
- https://github.com/GetStream/stream-chat-swiftui/issues/227

At the moment, there's no way to solve this properly in the SDK. Possible workarounds that customers in the tickets have done are:
- build their own sheet
- use full screen cover (as you already pointed out)
- use UIKit for the navigation part (with a custom modal transitioning delegate).

Hope that helps,
Martin
