### ISSUE TITLE
Discrepancy in username visibility between Android and iOS chat screens

### ISSUE THREAD

**Issue by kirsanov-dev** [GetStream/stream-chat-swiftui#437]
There is a discrepancy between Android and iOS regarding the visibility of usernames beneath the messages on the Chat screen. This makes it challenging to discern who has sent which message. Could this be addressed on the SDK side?
<img width="325" alt="Screenshot at Feb 20 09-22-04" src="https://github.com/GetStream/stream-chat-swift/assets/80982911/1f72cf5d-ea47-4711-9b0c-1698a0eaf963">

**Comment by nuno-vieira** [comment]
@kirsanov-dev OK, I've transferred the issue to our SwiftUI repo then. 

Can you `print` the data of `author.name` and check if it contains the name`

**Comment by nuno-vieira** [comment]
@kirsanov-dev  Another thing is that for DM channels, 1-1 the name is not displayed on propose since it is redundant data. Maybe on Android you used a Group Channel, and on iOS you are using a Direct Message Channel?

**Comment by kirsanov-dev** [comment]
@nuno-vieira I'm using Direct Message Channel for several people. Not a channel. On Android such DMCs have user names enabled below the messages, just tested it. So the question remains, whether it's possible to add such feature to DMCs on iOS (SwiftUI)?

**Comment by kirsanov-dev** [comment]
@nuno-vieira just tested that on Android the names are displayed even in a DMC with 2 people, so the discrepancy between iOS and Android really exists.
