### ISSUE TITLE
VoiceRecordingView should use viewfactory's bubble modifier

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#440]
in `VoiceRecordingContainerView.swift`, `VoiceRecordingContainerView` uses `.messageBubble`
![Screenshot 2024-02-27 at 01 16 06](https://github.com/GetStream/stream-chat-swiftui/assets/69051988/d82e1e46-64d1-405c-9f12-6d2a969dc86f)

it should use
`factory.makeMessageViewModifier`
instead

**Comment by martinmitrevski** [comment]
Hi @grandsir,

Thanks for reporting, that should be the case indeed. Will be solved here: https://github.com/GetStream/stream-chat-swiftui/pull/441.

Best, Martin

**Comment by grandsir** [comment]
Thanks @martinmitrevski, is voice memos a fully-supported feature in streamchat-swiftui, or is it something in development still? We use that in our chat app but the UX is not feasible enough our team feels

**Comment by martinmitrevski** [comment]
it's fully supported feature. Which UX parts are not feasible enough, can you provide us more details? I will pass it to our design team.

**Comment by grandsir** [comment]
Sure, the UI part is OK only there are some flaws, here's what our users and we think:

1- Voice recording button is not responsive enough, when you tap to it, it takes a good 2-3 seconds for recording to start, that could be reduced
2- Unlike the apps like whatsapp, when you tap and swipe up the mic icon, it doesn't start the voice recording
3- There's no haptic feedback for recording voice memos
4- The sound quality of voice memos are very low
5- This one is a bug, when adjusting the playback speed of a voice memo, such as doubling it to 2x, it initially works fine. However, after the memo ends and you replay it, the speed reverts back to 1x.
