### ISSUE TITLE
Inability to Override executeOnMessageSent in TwoStepMentionCommand Subclass

### ISSUE THREAD

**Issue by looopers** [GetStream/stream-chat-swiftui#442]
## What did you do?
I followed the documentation for implementing custom commands in a SwiftUI app using Stream Chat: [Customizing Composer Commands](https://getstream.io/chat/docs/sdk/ios/swiftui/chat-channel-components/composer-commands/). My objective is to create a "/block" command that enables users to block others directly from the chat interface.

## What did you expect to happen?
I anticipated being able to override the executeOnMessageSent method in my subclass of TwoStepMentionCommand, as suggested by the example in the documentation. This would allow me to define custom behaviour for the "/block" command, effectively blocking the selected user when the command is executed.

## What happened instead?
The compiler emits an error when trying to override the executeOnMessageSent method, stating that overriding a non-open instance method outside of its defining module is not allowed. As a result, although my custom command appears in the chat interface, it lacks functionality because I cannot attach any actions to it.

**Compile error:**
```Overriding non-open instance method outside of its defining module```

<img width="1006" alt="Capture d’écran 2024-02-27 à 22 56 53" src="https://github.com/GetStream/stream-chat-swiftui/assets/122487755/899f1c03-209b-48a6-81aa-c2461d4b7218">

## GetStream Environment
**GetStream Chat version:** 4.45.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16
**Swift version:** Swift 5
**Xcode version:** 14.3.1
**Device:**

**Comment by martinmitrevski** [comment]
Hi @looopers,

Yes, you are correct, sorry for the inconvenience. This is now fixed on our `main` branch and it will be included in our next release.

Best, Martin

**Comment by martinmitrevski** [comment]
Available in 4.50.0.
