### ISSUE TITLE
Instant commands button is displayed when there are no commands configured

### ISSUE THREAD

**Issue by sslash** [GetStream/stream-chat-swiftui#451]
## What did you do?
* I have made a custom command that I only want to staff users to see
* I configure the `CommandsHandler` like this, ish:
```
if isAdmin {
    let instantCommands = [MyCustomBroadcastCommand()]
    handler = CommandsHandler(commands: [mentionsCommand, instantCommands])
} else {
   // because this is empty, I expect the commands button not to show in the UI
   handler = CommandsHandler(commands: [])
}
```
* If I open the chat-screen as a non-admin user, I still see the instant commands button, but when I tap it, it opens an empty pop-up 

## What did you expect to happen?
* The instant-commands button should not show at all if there are no commands to display

## What happened instead?
* It shows the button, but it opens an empty/buggy-looking popup

## GetStream Environment
**GetStream Chat version:** 4.49.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.0.0
**Swift version:**  5
**Xcode version:** 15.0.1
**Device:** iPhone 15 pro

## Additional context
Optimally, I could just configure in the API/Dashboard that my custom command should only be available for staff/admin users, but I see no way to do this? I might be wrong though, so please shed some light on this if I'm mistaken. But this is the reason I try to enforce it on the client..

Here's an example for non-admin users:

https://github.com/GetStream/stream-chat-swiftui/assets/1174520/2e27daf4-c64a-456a-92e7-074538fbc97d

Thanks!

**Comment by martinmitrevski** [comment]
Hey @sslash,

Thanks for reporting. This is a limitation on our dashboard - there's no way to configure different commands for different user roles. The client side is dashboard driven - and it always reads the one configured for all users. 

Although not ideal, the solution here would be for you to provide your custom implementation of the `AttachmentPickerTypeView` with the following method in the `ViewFactory`:

```swift
public func makeLeadingComposerView(
        state: Binding<PickerTypeState>,
        channelConfig: ChannelConfig?
    ) -> some View
```

You could do an if-else based on your user role - if it's admin you can just return the default implementation `DefaultViewFactory.shared.makeLeadingComposerView`. If it's regular user, you can just provide the attachments button.

Hope that helps, 
Martin

**Comment by sslash** [comment]
Thanks for the fast reply @martinmitrevski 🙌

The approach you are describing makes sense to me. Being a bit new to the ViewFactory concept, from my understanding, you can't really return two different view kinds using this approach, e.g:

```
public func makeLeadingComposerView(
            state: Binding<PickerTypeState>,
            channelConfig: ChannelConfig?
    ) -> some View {
        if isAdmin {
            return DefaultViewFactory.shared.makeLeadingComposerView(state: state, channelConfig: channelConfig)
        } else {
            return EmptyView()
        }
    }
```
gives the error `Function declares an opaque return type 'some View', but the return statements in its body do not have matching underlying types`.

I would prefer not to wrap the two views in `AnyView` to get around the problem, as that's suboptimal in performance terms and generally advised against.

Any suggestion for improving that?

Cheers!

**Comment by sslash** [comment]
Perfect, thanks @martinmitrevski 🙌
