### ISSUE TITLE
Support programmatic insert mention command into message composer

### ISSUE THREAD

**Issue by sslash** [GetStream/stream-chat-swiftui#455]
## What are you trying to achieve?
I want to be able to have a button (that is visible on a few chosen users in the UI) such that when tapping it, the message composer will be filled with an `@<name of user>` ie mention string. This would be a really helpful way for us to lower the barrier to @-mention certain people in the chat. So not a DM, but just doing the job of pre-filling the mention string (and connecting the mentioned-user in the view-model I assume).

## If possible, how can you achieve this currently?
Having looked through the docs and source code for this lib, I haven't found a way to achieve this. Maybe it would be possible to declare the `ChatMessageController` higher up in the SwiftUI view tree, and mutate the message there, but it feels a bit awkward having to pass the controller all the way down, and also risk loads of re-renders if the view-model is high up in the chain. Might be wrong about that one though! 

## What would be the better way?
Maybe something like `chatController.prepareMessage(mentionedUserId: <id>) for example.` I'm sure there are many ways to achieve this, and the authors of this lib surely has good thoughts for what the most elegant way to achieve this would be, if its something they feel makes sense to support of course. 

## GetStream Environment
**GetStream Chat version:** 4.49.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.0.0
**Swift version:**  5
**Xcode version:** 15.0.1
**Device:** iPhone 15 pro

## Additional context

This is just as much, is there a way to do this now, kind of question, rather than a feature request.

Any help would be highly appreciated!

**Comment by martinmitrevski** [comment]
Hi @sslash,

If I understand correctly, you want to have some view with few users, and when you tap on them, you want to add them in the message text and as mentioned users?

We don't have out of the box support for such case - but what you can probably do is modify the `text` and `mentionedUsers` in the `MessageComposerViewModel` when a user taps in your custom view. You can also use the `selectedRangeLocation` to know where is the cursor. 

Note that you will need to inject the `MessageComposerViewModel` into the `MessageComposerView`, and keep it somewhere in your app, so you can manipulate it. For that, you can implement your version of the view factory method `makeMessageComposerViewType`, where you will use the default message composer, but with a view model you instantiated on your side.

Hope that helps,
Martin

**Comment by sslash** [comment]
@martinmitrevski This seem to work!

However, having to instantiate `MessageComposerViewModel` and keep it in sync with the ChatChannelController reference, feels scary in terms of redundant/dropped re-renders and potential retain cycles.

I've tried to pull out the most important things of my app structure, and would love your input whether you think this is the right approach or not. Basically the only way I see how to do it is by using global singleton objects:

```
// Global wrapper around the ChatChannelController
// we reinstantiate the ChatChannelController each time the user changes channel
class MCChatHandle: ObservableObject {
    static let shared: MCChatHandle = .init()

        @Published var controller: ChatChannelController? {
        didSet {
            guard let controller else { return }
            
            // Each tim we change channel this will also be re-instantiated
            // since it has a reference to the ChatChannelController
            let viewModel = ViewModelsFactory.makeMessageComposerViewModel(
                with: controller,
                messageController: nil
            )
            
            MessageComposerViewModelWrapper.shared.configure(with: vm)
        }
    }
}

struct MyScreen: View {
    @ObservedObject var chatHandle: MCChatHandle = .shared

    @ObservedObject var sheetManager: SheetManager = .shared
    
    var body: some View {

        if let controller = chatHandle.controller {
            ChatChannelView(viewFactory: CustomViewFactory.shared,
                            channelController: controller)
            
            // somewhere in app we open this sheet which has a button to 
            // start forming a mention message
            .sheet(isPresented: $sheetManager.isPresented) {
                CustomMentionButtonView(handleTap: { chatUser in

                    // Inject the mention command / text into the input view
                    let newText = "@\(chatUser.name) "
                    MessageComposerViewModelWrapper.shared.viewModel?.text = newText
                    MessageComposerViewModelWrapper.shared.viewModel?.mentionedUsers.insert(chatUser)

                    // this didn't really do anything?
                    MessageComposerViewModelWrapper.shared.viewModel.selectedRangeLocation = newText.count
                }) 
            }
        }
    }
}

// Global wrapper around the MessageComposerViewModel
// so we can edit the input field directly
class MessageComposerViewModelWrapper: ObservableObject {
    @Published var viewModel: MessageComposerViewModel?
    
    static let shared: MessageComposerViewModelWrapper = .init()
    
    private init() {}
    
    func configure(with viewModel: MessageComposerViewModel) {
        self.viewModel = viewModel
    }
}

class CustomViewFactory: ViewFactory {

    @Injected(\.chatClient) public var chatClient
    
    private init() {}

    public static let shared = CustomViewFactory()
    
    public func makeMessageComposerViewType(
        with channelController: ChatChannelController,
        messageController: ChatMessageController?,
        quotedMessage: Binding<ChatMessage?>,
        editedMessage: Binding<ChatMessage?>,
        onMessageSent: @escaping () -> Void
    ) -> some View {        
        return MessageComposerView(
            viewFactory: self,

            // Here we inject the shared view-model
            viewModel: MessageComposerViewModelWrapper.shared.viewModel,
            channelController: channelController,
            messageController: messageController,
            quotedMessage: quotedMessage,
            editedMessage: editedMessage,
            onMessageSent: onMessageSent
        )
    }
}
```

Thoughts @martinmitrevski ?

Btw I'm unsure how you intended to use `selectedRangeLocation` because nothing really happens if I modify it. I'm probably not doing it correctly though.

Thanks again @martinmitrevski ! 🙌

**Comment by martinmitrevski** [comment]
Hey @sslash,

Glad to hear you made it working.

> However, having to instantiate MessageComposerViewModel and keep it in sync with the ChatChannelController reference, feels scary in terms of redundant/dropped re-renders and potential retain cycles.

If you are using the same instance of the view model and the controller, there's nothing to worry about performance wise. The only difference is that you manage the lifecycle of the object, which gives you more control to do custom things.

As for retain cycles, the channel controller doesn't hold the view model, so there's no risk for it. Just to make sure, you can open the memory debugger to confirm it.

> Basically the only way I see how to do it is by using global singleton objects

This is one way to do it. Another could be to keep everything as variables in the view factory, since also the other view that uses the message composer view model is injected via the view factory. This is up to you and what feels best for your app.

Looking at the code, I have one thing to point out:
```swift
didSet {
            guard let controller else { return }
```
Here you are basically checking if a controller is not nil as the only condition. If you leave a channel and enter a new one, if you don't reset this value, the new controller for that channel would not be configured in the view model.

Therefore, you can check if the `controller.channel?.cid` is equal with the previous value before deciding to return.

Hope that helps,
Martin

**Comment by sslash** [comment]
Gotcha, thanks again! I think we can close this one then 😁
