### ISSUE TITLE
Add `userRole` to `UserDisplayInfo`

### ISSUE THREAD

**Issue by sslash** [GetStream/stream-chat-swiftui#458]
## What are you trying to achieve?
Display a role "badge" on user's avatar image in message-list. E.g if a user is admin or part of the customer-service team, we want to show that in form of a badge

## If possible, how can you achieve this currently?
```
struct CustomAvatarView: View {
    @Injected(\.chatClient) private var chatClient
    
    var userDisplayInfo: UserDisplayInfo
    
    var body: some View {
        let controller = chatClient.userController(userId: userId)
        let isAdmin = controller.user?.userRole == .admin
        
        MessageAvatarView(avatarURL: imageUrl)
            .overlay {
                if isAdmin {
                    AdminBadge()
                }
            }
    }
}
```

The problem with this is I have to instantiate the userController for each avatar row, which seems quite heavy, and has side-effects. I'm also not sure if the user-role will always be available this way.

## What would be the better way?
The following changes would in my opinion add positive value not only for us, but other users who might want to show different user-info based on the user's role. It also feels like a good fit for the `UserDisplayInfo` struct, but that's just my opinion ☺️ 

```
public struct UserDisplayInfo {
    // old fields ...
    public let userRole: UserRole? // <-- new

    public init(id: String, name: String, imageURL: URL?, userRole: UserRole?) {
        self.id = id
        self.name = name
        self.imageURL = imageURL
        self.userRole = userRole
    }
}

// and in MessageCachingUtils:
private func saveUserDisplayInfo(for message: ChatMessage) -> UserDisplayInfo {
        let user = message.author
        let userDisplayInfo = UserDisplayInfo(
            id: user.id,
            name: user.name ?? user.id,
            imageURL: user.imageURL,
            userRole: user.userRole // <-- new
        )
// ... other things

```

Keen on hearing your thoughts on this! Also, happy to make a PR if you all agree with the approach.

## Additional context

Example of badge on avatar (see arrow):

<img width="1247" alt="image" src="https://github.com/GetStream/stream-chat-swiftui/assets/1174520/1cf4374a-6e86-4df0-ba09-19bcb7164500">

**Comment by martinmitrevski** [comment]
Thanks for reporting, we added this in our `main` branch and it will be available in the next release.
