### ISSUE TITLE
Add image attachment animation / transition from UIKit SDK to SwiftUI SDK.

### ISSUE THREAD

**Issue by kylecfoley** [GetStream/stream-chat-swiftui#46]
## What are you trying to achieve?

In UIKit SDK, when tapping an image in the chat, the image scales up to fill the screen (similar to iMessage). In the SwiftUI SDK, the image opens in a separate overlay that slides up from the bottom of the viewport. The UIKit animation feels more efficient and more elegant.

UIKit:

https://user-images.githubusercontent.com/13056226/163627556-bf234272-bd99-412a-909a-6f4f546b2f92.mp4

SwiftUI:

https://user-images.githubusercontent.com/13056226/163627554-c897df4a-256a-44d7-b51f-cba9170595ed.mp4

## GetStream Environment
**GetStream Chat version:** Latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.2
**Swift version:** 5
**Xcode version:** 13.2.1
**Device:**

**Comment by kylecfoley** [comment]
My team is currently working to implement Stream Chat, we have found a lack of design parity between the SwiftUI and UIKit SDKs :)

**Comment by martinmitrevski** [comment]
Hey @kylecfoley, 

We also have this in our pipeline, we will increase its priority now that there's an interest in this animation. 

We will let you know as soon as we have update.

Regards,
Martin

**Comment by kylecfoley** [comment]
Excellent, thank you for the fast reply.
