### ISSUE TITLE
Unable to use ChatMessageAttachmentPreviewVC

### ISSUE THREAD

**Issue by tciuro** [GetStream/stream-chat-swiftui#461]
## What did you do?

I started with this:

```swift
import SwiftUI
import StreamChat
import StreamChatSwiftUI

class CustomChatAttachmentPreviewVC: ChatMessageAttachmentPreviewVC {
    
}
```
Xcode complains that `ChatMessageAttachmentPreviewVC` cannot be found. Suggests importing `StreamChatUI`, but when I do import it, it cannot find it (as expected, since I haven't added the package.) The problem is that if I try to add the package (the URL at https://github.com/GetStream/stream-chat-swift is the only way I found to add it), Xcode complains that it cannot resolve it.

What's also confusing is this paragraph:
> UIKit SDK
The StreamChatUI SDK is our UI SDK for UIKit components. If your application needs to support iOS 13 and below, this is the right UI SDK for you.

So what if I need to reach out to UIKit from SwiftUI in iOS 17? What do I use? Just `StreamChatSwiftUI`? It doesn't appear to be the case.

The file is supposed to be here:

```
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageAttachmentPreviewVC.swift
```

So why is `import StreamChatSwiftUI` showing an error that it cannot find the file?

<img width="1266" alt="image" src="https://github.com/GetStream/stream-chat-swiftui/assets/412899/9de1c7fc-78b8-444e-81ca-9ac49dc2ae3b">

## What did you expect to happen?

To import `StreamChatSwiftUI` and recognize `ChatMessageAttachmentPreviewVC`

## What happened instead?

See explanation and screenshot above.

## GetStream Environment
**GetStream Chat version:** 4.50.0
**GetStream Chat frameworks:** StreamChatSwiftUI 4.50.1
**iOS version:** 17.3/17.4
**Swift version:** swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
**Xcode version:** 15.2
**Device:** doesn't matter. Won't compile.

**Comment by martinmitrevski** [comment]
Hi @tciuro, 

The `ChatMessageAttachmentPreviewVC` is part of the UIKit SDK, and it's not available in the SwiftUI SDK. We offer two SDKs, depending on what fits better for your app. Therefore, you can't use components from our UIKit SDK into our SwiftUI SDK.

If you want to use other UIKit standard components into our SwiftUI SDK, you can use the standard way with view representables.

Hope that helps,
Martin

**Comment by tciuro** [comment]
@martinmitrevski I understand, but in order to use UIViewRepresentable, I need to be able to link to the class first, right? How do I install the UIKit package? I've been having problems with it with Xcode complaining that the package isn't valid. What's the SPM package URL I should be using?

**Comment by martinmitrevski** [comment]
The UIKit package is under `StreamChat`: https://github.com/getstream/stream-chat-swift. 
You need to select the checkmark for StreamChatUI when importing the package, as described here: https://getstream.io/chat/docs/sdk/ios/basics/integration/.

**Comment by tciuro** [comment]
@martinmitrevski something is not right: I'm adding the package `https://github.com/getstream/stream-chat-swift` and this is what I see next:

![image](https://github.com/GetStream/stream-chat-swiftui/assets/412899/0699ea64-f5db-4587-81cf-498b6ec0bbbd)

I already have `https://github.com/getstream/stream-chat-swiftui` installed. But when I try with `stream-chat-swift`, it resolves to `stream-chat-swiftui`! And it shows the dialog above. By the way, if I select Target, the app is grayed out because I already have `stream-chat-swiftui` installed. Why is `stream-chat-swift` resolving to `stream-chat-swiftui`?

Thanks for the help.

**Comment by tciuro** [comment]
Reproducible case (standard SwiftUI app adding `https://github.com/getstream/stream-chat-swift`):

[StreamIssue.zip](https://github.com/GetStream/stream-chat-swiftui/files/14724883/StreamIssue.zip)

**Comment by martinmitrevski** [comment]
I've tried your sample project, and added the UIKit SDK, it resolves correctly. I suspect there's a caching issue on your Xcode. Maybe try "File -> Packages -> Reset Package Caches", or try removing and adding all the packages again. Also deleting derived data could help.

**Comment by tciuro** [comment]
Hi @martinmitrevski, just for the sake of completeness in case someone stumbles on this issue: is this supposed to compile?:
```swift
import Foundation
import SwiftUI
import StreamChatUI

// Package installed: https://github.com/getstream/stream-chat-swift

class CustomChatAttachmentPreviewVC: ChatMessageAttachmentPreviewVC {
    
}
```
I have reset the packages and completely removed `DerivedData` and I still continue having the `No such module 'StreamChatUI'` error.

Why is this not working for me? 😣

**Comment by tciuro** [comment]
@martinmitrevski I jusr read your message again and saw that you mention this:

>I've tried your sample project, and added the UIKit SDK, it resolves correctly.

What is the UIKit SDK? According to the documentation, it's `https://github.com/getstream/stream-chat-swift`, right? Or am I missing something here? Would you mind sending me the revised sample project to see what's going on? Thanks again!

**Comment by martinmitrevski** [comment]
Maybe also check your `~/.gitconfig`, to see if sth was changed there.

The code compiles on the updated project, which I'm attaching. We don't recommend using both of the SDKs together - they are serving the same purpose - but that doesn't mean it's not possible.

The UIKit SDK is part of https://github.com/getstream/stream-chat-swift.

[StreamIssue.zip](https://github.com/GetStream/stream-chat-swiftui/files/14725842/StreamIssue.zip)

**Comment by tciuro** [comment]
OK... I'm going crazy here:

1) the revised project you sent me compiles fine on both Macs.
2) If I try to add the UIKit SDK on the first sample project I sent you, it does not work: it resolves to the SwiftUI package! (see screenshot above.)
3) I basically looked at your revised project's dependencies:

<img width="906" alt="image" src="https://github.com/GetStream/stream-chat-swiftui/assets/412899/018e50d1-6249-427a-a4ca-5d288bc0dd62">

I simply cannot add the `StreamChat` package because it tells me that the project already contains it. If I go ahead anyway and add it, nothing happens. I'm left with the `StreamChatSwiftUI` package.

How did you manage to add `StreamChat` without hitting this issue?

**Comment by martinmitrevski** [comment]
I just added it like a regular package, nothing special. Maybe you can open the Packages page, right click on the SwiftUI one, and remove it, then try adding it again (see screenshot).

![Screenshot 2024-03-22 at 17 58 19](https://github.com/GetStream/stream-chat-swiftui/assets/2971717/3442c0e6-77fd-4d46-bc69-b2dfedfa3c63)

**Comment by tciuro** [comment]
Finally! 😮‍💨

This is what I had to do:

1) remove the `Stream` package from dependencies
2) add `StreamChat` first (https://github.com/GetStream/stream-chat-swift)
    2.1) A surprise: four items appear in the list
    2.2) Select `StreamChat` and `StreamChatSwiftUI` (choose the proper target from the popup)
3)  Add the `StreamChatSwiftUI` pachage (https://github.com/getstream/stream-chat-swiftui)

That did it.

Recommendations:

- update the installation instructions. The order of the package installation seems to matter. As currently stated in the documentation, it's no slam dunk.
- perhaps mention that both the UIKit and SwiftUI packages need to co-exist if one needs to dig to UIKit via`UIViewRepresentable`.

@martinmitrevski I'm not sure why you say Stream doesn't recommend installing both, though it's possible. If one needs to use `UIViewRepresentable` to customize the UI, there is no other choice (unless you remove the possibility to access your UIKit APIs, which at the moment would limit additional customization UI customization, and may I dare to say, would be a bad decision.)

Thanks so much for the help!
