### ISSUE TITLE
Message links

### ISSUE THREAD

**Issue by borutlatecheckout** [GetStream/stream-chat-swiftui#468]
## What are you trying to achieve?
I would like to handle links (urls) in messages similar to how UITextView works in UIKit. I have a custom implementation of the message view.

## If possible, how can you achieve this currently?
I can use UITextView wrapper for swiftui currently, but it doesn't work properly with the current setup of the chat.
I've also noticed there is a `LinkDetectionTextView` available inside SDK, but is not publicly available for use. 

## What would be the better way?
To have a native support within the SDK or to open up access to `LinkDetectionTextView`.

## GetStream Environment
**GetStream Chat version:** latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.x
**Swift version:** 5.10
**Xcode version:** 15x
**Device:** iPhone

**Comment by martinmitrevski** [comment]
Hi @borutlatecheckout,

We have exposed `LinkDetectionTextView` as public on our `main` branch, it's going to be available in our next release.

Best, Martin

**Comment by borutlatecheckout** [comment]
Great 🙌  Thanks @martinmitrevski!
