### ISSUE TITLE
Custom emoji reactions over message [Swift UI]

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#47]
## What are you trying to achieve?
We are using SwiftUI SDK. We would like to have custom emojis have in place for reactions.
It can be done right now, but as far as I can see the tint color of those emojis are hardcoded and can not be configured.

## If possible, how can you achieve this currently?
We use the default emojis in place

## What would be the better way?
If it's possible to pass custom images and configure `tintColor` from outside, would be amazing. So basically the tint color should be an optional parameter

## GetStream Environment
**GetStream Chat version:** Latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** Latest
**Swift version:** 5
**Xcode version:** Version 13.3 (13E113)
**Device:** iPhone 12/13 | Simulator

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze,

Thanks for creating the issue. We actually already have this possibility on our `main` branch, and it will be included in the next release (most likely tomorrow).

In the meantime, you can also connect to the `main` branch, if you want to use it straight away.

The way it works is, we have the following optional reaction colors (set them to nil to avoid tinting altogether, or put any other color you prefer):
- `reactionCurrentUserColor: UIColor?` - for reactions done by the current user
- `reactionOtherUserColor: UIColor?` - for reactions done by other users in the chat
- `selectedReactionBackgroundColor: UIColor?` - specify color when a reaction is selected (Similar to FB Messenger).

Hope this helps. If you have any other questions, please let me know.

Best,
Martin

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski Hello.
Thanks for your fast reply.
I will checkout main branch and test and will get back to you.

**Comment by GeorgeVashakidze** [comment]
Works fine. Thanks a lot. 
@martinmitrevski when do you think SDK will be released?

**Comment by martinmitrevski** [comment]
Glad to hear @GeorgeVashakidze. The release will be today, in a few hours. 

I will ping you on this issue when it's released.

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, the release is postponed for tomorrow. You can use `main` safely until then.
