### ISSUE TITLE
Unable to initialise some public structs with public property

### ISSUE THREAD

**Issue by daljeetseera** [GetStream/stream-chat-swiftui#477]
## What did you do?
I am trying to make a custom ChatChannelListViewModel for specific UI changes but I am facing a situation where I am not able to use some public structs because of their internal initialisation. Example - InjectedChannelInfo. There is no public init in it due to which its unable to create a instance of it outside the framework.

## What did you expect to happen?
Structs which are defined public along with properties must have public init so that it can be utilised outside of the Stream SDK.

## What happened instead?
Unable to create a instance and blocked with further custom changes.

## GetStream Environment 
**GetStream Chat version:** - 'StreamChatSwiftUI', '4.51.0'
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** iOS 17.0
**Swift version:** Swift 5.0
**Xcode version:** Xcode 15.0
**Device:** iPhone 15 Pro Max

## Additional context
Structs which are defined which are not public is okay. Though, which are define public must have public init.

**Comment by martinmitrevski** [comment]
Hi @daljeetseera,

Thanks for reporting. We added the public init of `InjectedChannelInfo` in our `main` branch and it will be available in the next release.

Best, Martin
