### ISSUE TITLE
Pass GIF to Chat (GIPHY SDK)

### ISSUE THREAD

**Issue by kylecfoley** [GetStream/stream-chat-swiftui#48]
Our team has implemented the GIPHY SDK in Stream but is unable to pass a GIF into the chat. Currently, we have only been able to pass a video or link. 

Based on user testing and our assessment of leading chat apps on the market, the GIPHY SDK provides a more common and more powerful user experience for selecting GIFs than the existing GIPHY implementation that Stream uses. 

![image](https://user-images.githubusercontent.com/13056226/164136412-3a059242-9f30-4902-a451-3e5950a9e1a2.gif)

**Comment by martinmitrevski** [comment]
Hey @kylecfoley,

For this case I would suggest to look into our custom attachments feature, which would allow you to achieve a giphy selector that's different from what we offer in the SDK.

Here are the docs for adding custom attachments: https://getstream.io/chat/docs/sdk/ios/swiftui/components/message-composer/#customizing-the-attachmentpickertypeview. 

The example in the docs is with a contact list, but the same concept applies for any other type of attachment such as a giphy:
- in the custom attachment slot in the attachment picker, you can add the giphy selector from the SDK you are using.
- extend the input composer with your own type of attachment.
- update the rendering of the message list with the new type of attachment.

Hope this helps. If you have some questions about the guide on custom attachments, please let me know.

Regards,
Martin

**Comment by martinmitrevski** [comment]
Hey @kylecfoley,

Anything else we can help you with regarding this issue?

Looking forward to your update.
Best, 
Martin

**Comment by kylecfoley** [comment]
Hey @martinmitrevski,

Thanks for following up. We will be revisiting this item in one of our sprints this month, I think it is safe to close for now :)

**Comment by martinmitrevski** [comment]
Great, thanks for the update @kylecfoley.
