### ISSUE TITLE
External edit of a message breaks message UI

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swiftui#484]
## What did you do?
I'm sending a message and then editing multiple times.

## What did you expect to happen?
I'm expecting the message to be displayed properly.

## What happened instead?
The message breaks and has a very inconsistent behavior. I compared this to the web chat explorer at the same time and works properly there.
Also I did some experimentation around it and it looks like the culprit is in around `MessageTextView` or `StreamTextView` 

## GetStream Environment
**GetStream Chat version:** 4.55.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.4
**Swift version:** 5+
**Xcode version:** 15.3
**Device:** iPhone 15 Pro Sim and iPhone 15 Device

## Additional context

https://github.com/GetStream/stream-chat-swiftui/assets/1914557/ed8dc3a7-38be-4a0d-80c9-fc6c2ade7f55

**Comment by martinmitrevski** [comment]
Hey @fceldeiro,

Thanks for reporting, we will look into it.

Best, Martin
