### ISSUE TITLE
Composer view component changes

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#49]
## What are you trying to achieve?
Hello. I am trying to modify composer view. I have two issues right now.

1. change height of inputs and buttons

2. change background color of whole composer view. 

## What would be the better way?
1.  Would be nice to have separate prop under `Appearance` to set height of input view. Right now I can not change it.
2.  I can change the background color of whole composer view, but it discards changes for input. So would be nice to have separate prop under colors to set `ComposerViewType` background color in `Appearance`

## GetStream Environment
**GetStream Chat version:** Latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** Latest
**Swift version:** 5
**Xcode version:** Version 13.3 (13E113)
**Device:** iPhone 12/13 | Simulator

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze, thanks for the questions. 

I would need some more input from you to understand the correct use-case.

1. About the first one, you want to increase the size of the text input and the buttons on the left and right?
- for the input text view, we can expose config to control the size. 
- for increasing the button on the left and right, the approach would be to create your own views, by implementing the methods `makeLeadingComposerView` and `makeTrailingComposerView`.
2. About the second one, have you tried the method `makeComposerViewModifier`? Basically, you can apply background with a custom view modifier:
```swift
func makeComposerViewModifier() -> some ViewModifier {        
    BackgroundViewModifier()
}

struct BackgroundViewModifier: ViewModifier {
    
    public func body(content: Content) -> some View {
        content
            .background(Color.blue)
    }
}
``` 
Will this help you to achieve the desired UI?

Also, sharing a screenshot might help.

Best,
Martin

**Comment by kylecfoley** [comment]
Hey @martinmitrevski , I have provided a screenshot of our progress below for reference:

<img width="947" alt="Screen Shot 2022-04-20 at 10 07 29 AM" src="https://user-images.githubusercontent.com/13056226/164285251-97cce1a5-9028-433f-bad0-eaba4355f4cb.png">

**Comment by GeorgeVashakidze** [comment]
> Hey @GeorgeVashakidze, thanks for the questions.
> 
> I would need some more input from you to understand the correct use-case.
> 
> 1. About the first one, you want to increase the size of the text input and the buttons on the left and right?
> 
> * for the input text view, we can expose config to control the size.
> * for increasing the button on the left and right, the approach would be to create your own views, by implementing the methods `makeLeadingComposerView` and `makeTrailingComposerView`.
> 
> 2. About the second one, have you tried the method `makeComposerViewModifier`? Basically, you can apply background with a custom view modifier:
> 
> ```swift
> func makeComposerViewModifier() -> some ViewModifier {        
>     BackgroundViewModifier()
> }
> 
> struct BackgroundViewModifier: ViewModifier {
>     
>     public func body(content: Content) -> some View {
>         content
>             .background(Color.blue)
>     }
> }
> ```
> 
> Will this help you to achieve the desired UI?
> 
> Also, sharing a screenshot might help.
> 
> Best, Martin

Hello. Thanks for your answer.
Of course I saw this, but I guess it gets called only for Swift UIKIt version, not for SwiftUI right?

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze, 

The modifier is called only for the SwiftUI version, not the UIKit one. So it can be used for changing the background.

For the size, the screenshot @kylecfoley provided helps, so I will expose additional config for controlling the sizes so you don't have to re-implement the views in the composer.

Will provide an update during the day.
Regards,
Martin

**Comment by GeorgeVashakidze** [comment]
hmm it is not called for me :/ may be issue with the version?

**Comment by martinmitrevski** [comment]
The composer modifier was already released in the previous version, 4.13.0, so it should be available even if you are not connected to `main`. 

Can you please share the code how are you calling it? I might be able to give you a hint what's wrong.

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski Thank you. so the background worked. I think I was just using View instead of view modifier and that was the reason.

When you think height prop will be avaialble?

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski 
also what can be a reason that these two functions are not called?

```swift
func makeChannelListModifier() -> ChannelViewModifier {
    ChannelViewModifier()
}

func makeChannelListDividerItem() -> some View {
    Rectangle()
        .fill(Color(with: .soot))
        .frame(height: 1)
}

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, about the height props, I'm working on it now, so it should be available soon. We might even include it in today's release if it works well.

About the methods - are they not called at all, or just your changes are not applied? If not called at all, do you have some custom implementation around the channel list or you use the one from the SDK? 
Additionally, about the first one, I'm assuming that `ChannelViewModifier` is a modifier, not a view, right?

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, additional question. The + button on the left, is it your own custom button or one from the SDK? Do you need frame props there?

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski  The first one is a modifier right, not a view.
They are not called, not sure why. No we dont have custom implementations for channel List, only this.

```swift
extension StreamViewFactory {
    func makeComposerViewModifier() -> ComposerViewModifier {
        ComposerViewModifier()
    }
    
    func makeChannelListModifier() -> ChannelViewModifier {
        ChannelViewModifier()
    }
    
    func makeChannelListDividerItem() -> some View {
        Rectangle()
            .fill(Color(with: .soot))
            .frame(height: 1)
    }
}

Regarding this [question](https://github.com/GetStream/stream-chat-swiftui/issues/49#issuecomment-1104884367), it is my own button for the composer left view

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, before I make this available on `main`, just to double check if everything would be there:
`ComposerConfig`, where you can set:
- `public var inputViewMinHeight: CGFloat` - the minimum height of the input view.
- `public var inputFont: UIFont` - the font of the input view.

Extension of the colors:
- `composerPlaceholderColor: UIColor` - for the placeholder text foreground color
- `composerInputBackground: UIColor` - for the input view background color

I think this is all you need to accomplish the screenshot from above.

About the modifiers, could you also share the content of `ChannelViewModifier`?

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski first of all thanks a lot.
I think it is enough for now 
```swift
struct ChannelViewModifier: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .background(Color(with: .night))
    }
}

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski 
one more question.

is it possible to move `MessageAuthorAndDateView` upon message?
I would put it myself on top, but issue is, that i can not remove `MessageAuthorAndDateView` at atll

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, in the `Utils` class from above, we also have `MessageListConfig`. One of the configuration options there is the `MessageDisplayOptions` struct, which has a property `showMessageDate`. You can set this to false to hide the dates.

Then, you could try implementing sth like this:
```swift
    func makeMessageContainerView(channel: ChatChannel, message: ChatMessage, width: CGFloat?, showsAllInfo: Bool, isInThread: Bool, scrolledId: Binding<String?>, quotedMessage: Binding<ChatMessage?>, onLongPress: @escaping (MessageDisplayInfo) -> Void, isLast: Bool) -> some View {
        let defaultView = DefaultViewFactory.shared.makeMessageContainerView(
            channel: channel,
            message: message,
            width: width,
            showsAllInfo: showsAllInfo,
            isInThread: isInThread,
            scrolledId: scrolledId,
            quotedMessage: quotedMessage,
            onLongPress: onLongPress,
            isLast: isLast
        )
        
        return VStack {
            Text("your date view here")
            defaultView
        }
    }
```

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski 
```swift
utils.messageListConfig = .init(
            messageListType: .messaging,
            typingIndicatorPlacement: .bottomOverlay,
            groupMessages: true,
            messageDisplayOptions: MessageDisplayOptions(
                showAvatars: true,
                showMessageDate: false,
                animateChanges: true
            ),
            messagePaddings: MessagePaddings(),
            dateIndicatorPlacement: .messageList,
            pageSize: 50,
            messagePopoverEnabled: true
        )
        
this should help right ?

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, yes, but there's no need to setup everything, since it has default values. Here's a shorter version:
```swift
        let messageDisplayOptions = MessageDisplayOptions(showMessageDate: false)
        let config = MessageListConfig(messageDisplayOptions: messageDisplayOptions)
        let utils = Utils(messageListConfig: config)
```

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski 
it still shows username.
so username is not hidden
<img width="318" alt="Screenshot 2022-04-21 at 14 43 04" src="https://user-images.githubusercontent.com/5709365/164441707-b426d588-e96e-480a-b102-e69a124bd5db.png">

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski also is it possible to get messageAuthorName safely and without having any performance issue? as Creator is lazy var. 'messageCachingUtils' is inaccessible due to 'internal' protection level, so is there any other way except of author getter?

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, 
Yes, you are right about the username. Now I've added an additional config for `showAuthorName` in the `MessageDisplayOptions`:
```swift
let messageDisplayOptions = MessageDisplayOptions(showMessageDate: false, showAuthorName: false)
let config = MessageListConfig(messageDisplayOptions: messageDisplayOptions)
let utils = Utils(messageListConfig: config)
```
About the second part, I've also exposed `MessageAuthorAndDateView` that you can safely use. It's initalized with the `ChatMessage`.
However, if you want to provide your custom UI, then you can add your own caching layer similar to the caching utils. We don't want to make this one public, since it's an implementation detail that will likely change in the future.

**Comment by GeorgeVashakidze** [comment]
Thanks a lot. You helped me a lot.

**Comment by martinmitrevski** [comment]
Great, glad to hear that. 

I will close this issue, if you have anything else, please create another issue.

**Comment by GeorgeVashakidze** [comment]
Of course. Thanks a lot

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski I will create new ticket for this
https://github.com/GetStream/stream-chat-swiftui/issues/49#issuecomment-1104715544
