### ISSUE TITLE
Ability to set custom background for chat composer and list view

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#50]
## What are you trying to achieve?

- Set custom background color for chatview -> composer (including safe area)
- Set custom background color for chatview -> list

## What would be the better way?
Have props for  both cases to set the background colors

## GetStream Environment
**GetStream Chat version:** Latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** Latest
**Swift version:** 5
**Xcode version:** Version 13.3 (13E113)
**Device:** iPhone 12/13 | Simulator

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze, 

Have you tried achieving this with the corresponding modifiers?

- `makeComposerViewModifier` for the composer (as discussed in another issue):
```swift
func makeComposerViewModifier() -> some ViewModifier {        
    BackgroundViewModifier()
}

struct BackgroundViewModifier: ViewModifier {
    
    public func body(content: Content) -> some View {
        content
            .background(Color.blue)
            .edgesIgnoringSafeArea(.bottom)
    }
}
```
Note the `edgesIgnoringSafeArea` part for adding the background in the safe area.

- `makeMessageListModifier` for the message list. Implementation is similar as in the composer.

**Comment by GeorgeVashakidze** [comment]
![165511071-4f551ba3-934f-4d5a-8dfa-38602f78356c](https://user-images.githubusercontent.com/5709365/166187745-78a6aca2-03f8-4ee8-abc4-607183f2a498.png)

hello @martinmitrevski 

Do you think it is possible to change remaining black backgrounds with red color as well?
So there are two places remaining.

1. space between composer and list
2. safearea

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze,

Sorry, about the composer, I mis-typed the modifier, the .edgesIgnoringSafeArea should be inside the color modifier, not as a separate one. Here's the full working example for both options:
```swift
    func makeComposerViewModifier() -> some ViewModifier {
        BackgroundViewModifier()
    }
    
    func makeMessageListBackground(colors: ColorPalette, isInThread: Bool) -> some View {
        Color.red
    }
```
And the background modifier is:
```swift
struct BackgroundViewModifier: ViewModifier {
    
    public func body(content: Content) -> some View {
        content
            .background(Color.red.edgesIgnoringSafeArea(.bottom))
    }
}
```

**Comment by GeorgeVashakidze** [comment]
Works fine. Thanks a lot
