### ISSUE TITLE
Podspec Missing Tag Specification Causes Installation to Default to Main Branch

### ISSUE THREAD

**Issue by masarusanjp** [GetStream/stream-chat-swiftui#501]
## What did you do?

I used CocoaPods to install the StreamChatSwiftUI library and specified version 4.56.0 in my Podfile.

## What did you expect to happen?

I expected CocoaPods to install the StreamChatSwiftUI library version 4.56.0 as specified in the Podfile.

## What happened instead?

Despite specifying version 4.56.0, CocoaPods installed the library from the main branch as 4.56.0 instead.

## GetStream Environment
**GetStream Chat version:** 4.56.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** iOS17.4
**Swift version:** 5.9
**Xcode version:** 15.3
**Device:** 

## Additional context

The issue is likely caused by the absence of a tag specification in the source field of the podspec.
https://github.com/GetStream/stream-chat-swiftui/blob/main/StreamChatSwiftUI.podspec
```diff
-    spec.source = { :git => "https://github.com/GetStream/stream-chat-swiftui.git" }
+    spec.source = { :git => "https://github.com/GetStream/stream-chat-swift.git", :tag => "#{spec.version}" }
```

### Podfile

```
target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'StreamChat'
  pod 'StreamChatSwiftUI', '4.56.0'

end


```

### Reproduce Step

- put Podfile
- remove cocoapods cache
  - `$ rm -rf /Users/user_name/Library/Caches/CocoaPods/Pods/Release/StreamChatSwiftUI`
- remove Pods
  - `$ rm -rf Pods`
- run pod install
  - `pod install --repo-update --verbose` 

### Log for pod install

Heres are part of logs for `bundle exec pod install --verbose`

You can see that StreamChat is cloned with the 4.56.1 branch specified, but StreamChatSwiftUI is cloned with the 4.56.0 version specified, but without branch specified.

```
-> Installing StreamChat (4.56.1)
 > Git download
 > Git download
     $ /opt/homebrew/bin/git clone https://github.com/GetStream/stream-chat-swift.git /var/folders/lz/_krgc_vs3_g607vtmjqwypxr0000gp/T/d20240605-91455-akg4wq --template= --single-branch --depth 1 --branch 4.56.1
     Cloning into '/var/folders/lz/_krgc_vs3_g607vtmjqwypxr0000gp/T/d20240605-91455-akg4wq'...
     Note: switching to 'a834ab04e1006210e2d74ca629815e71564582c1'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:

       git switch -c <new-branch-name>

     Or undo this operation with:

       git switch -

     Turn off this advice by setting config variable advice.detachedHead to false

  > Copying StreamChat from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/StreamChat/4.56.1-4ac6d` to `Pods/StreamChat`

-> Installing StreamChatSwiftUI (4.56.0)
 > Git download
 > Git download
     $ /opt/homebrew/bin/git clone https://github.com/GetStream/stream-chat-swiftui.git /var/folders/lz/_krgc_vs3_g607vtmjqwypxr0000gp/T/d20240605-91455-arnwco --template= --single-branch --depth 1
     Cloning into '/var/folders/lz/_krgc_vs3_g607vtmjqwypxr0000gp/T/d20240605-91455-arnwco'...
  $ /opt/homebrew/bin/git -C /var/folders/lz/_krgc_vs3_g607vtmjqwypxr0000gp/T/d20240605-91455-arnwco rev-parse HEAD
  eb42f8be4d0b07181f954469529af3766ffa0572
  > Copying StreamChatSwiftUI from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/StreamChatSwiftUI/4.56.0-6f8f7` to `Pods/StreamChatSwiftUI`
```

**Comment by martinmitrevski** [comment]
Hey @masarusanjp,

Thanks for spotting this - it indeed seems to be an issue. @testableapple please look into this.

**Comment by masarusanjp** [comment]
Thank you for the quick fix. 
Currently, specifying pod 
`'StreamChatSwiftUI', :git => "https://github.com/GetStream/stream-chat-swiftui.git", :tag => "4.56.0"`
 is working as a workaround, so I will wait for the next version release.
