### ISSUE TITLE
`makeMessageReadIndicatorView` is not called anymore if I use custom `makeMessageContainerView`

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#51]
## What did you do?
I can successfully remove `SEEN` view when somebody see my message by implementing `makeMessageReadIndicatorView`, but if I implement `makeMessageContainerView` then `makeMessageReadIndicatorView` is not called anymore.

## What did you expect to happen?
`makeMessageReadIndicatorView` func should be called anyway

## What happened instead?
`makeMessageReadIndicatorView` func is not called anymore

## GetStream Environment
**GetStream Chat version:** Latest
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** Latest
**Swift version:** 5
**Xcode version:** Version 13.3 (13E113)
**Device:** iPhone 12/13 | Simulator

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze,

The issue here is that by calling the `DefaultViewFactory.shared. makeMessageContainerView`, all its subviews will use the default view factory, which would not call the methods from your custom factory. 

The solution here would be to use the message container directly instead (I've exposed it now):
```swift
func makeMessageContainerView(channel: ChatChannel, message: ChatMessage, width: CGFloat?, showsAllInfo: Bool, isInThread: Bool, scrolledId: Binding<String?>, quotedMessage: Binding<ChatMessage?>, onLongPress: @escaping (MessageDisplayInfo) -> Void, isLast: Bool) -> some View {
        let defaultView =  MessageContainerView(
            factory: self,
            channel: channel,
            message: message,
            width: width,
            showsAllInfo: showsAllInfo,
            isInThread: isInThread,
            isLast: isLast,
            scrolledId: scrolledId,
            quotedMessage: quotedMessage,
            onLongPress: onLongPress
        )
        
        return VStack {
            Text("your date view here")
            defaultView
        }
    }
```

Hope this helps. 
Martin

**Comment by GeorgeVashakidze** [comment]
Many thanks @martinmitrevski 
let me check

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski `Cannot find 'MessageContainerView' in scope`

**Comment by martinmitrevski** [comment]
Did you update the StreamChatSwiftUI package to the latest version? It's available on `main`, and the release is finally happening today.
 
Btw, if you only want to hide read indicators, you can also do it via the Stream dashboard on the backend.

**Comment by GeorgeVashakidze** [comment]
Yes I am pointing to main branch. Let me remove the cache

**Comment by GeorgeVashakidze** [comment]
Works. Thanks a lot @martinmitrevski

**Comment by GeorgeVashakidze** [comment]
Closing this as it works now
