### ISSUE TITLE
Configurable Video Attachment Parameters

### ISSUE THREAD

**Issue by kylecfoley** [GetStream/stream-chat-swiftui#52]
One of our product's core features is unlockable photo/video content (user can pay to unlock photo and video within the chat). It would be ideal for us to control some of Stream's video attachment parameters:

- Compression level / quality
- Resolution
- Max file size
- Max video duration (if limit exists)

Thank you,
Kyle

**Comment by martinmitrevski** [comment]
Hey @kylecfoley, 

About this one, I would suggest getting in touch with our support and sales teams first. We need to better understand what you exactly need and whether we can support that, and that would be harder to grasp from a GH issue.

Thanks and regards,
Martin
