### ISSUE TITLE
SwiftUI empty state for chat

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#54]
## What are you trying to achieve?
Hi. Is it possible to have emptyview for chat if there is no message and have ability to replace whole message content with custom view? It is supported on Android so wondering wether it can be done on iOS as well?

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze,

Yes, we can expose this as well. Expect an update soon. 

Regards,
Martin

**Comment by GeorgeVashakidze** [comment]
Thanks a lot 🥇

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze,

This is now available on `main`. The channel and the colors are passed to this method, called `makeEmptyMessagesView`. Here's the usage:

```swift
func makeEmptyMessagesView(
        for channel: ChatChannel,
        colors: ColorPalette
) -> some View {
        Color(colors.background)
            .frame(maxWidth: .infinity, maxHeight: .infinity)
}
```

**Comment by GeorgeVashakidze** [comment]
Cool. works as expected. Thanks a lot
