### ISSUE TITLE
PhotoAttachmentCell not instantiatable due to internal protection level

### ISSUE THREAD

**Issue by masarusanjp** [GetStream/stream-chat-swiftui#543]
## What are you trying to achieve?

- I am going to create a custom PhotoAttachmentPickerView
- For that, I need to use PhotoAttachmentCell outside of stream chat SDK

## If possible, how can you achieve this currently?

Copy PhotoAttachmentCell, PhotoAssetLoader to my project.

## What would be the better way?

- Make the constructor of PhotoAttachmentCell public.

```
    public init(assetLoader: CustomPhotoAssetLoader, requestId: PHContentEditingInputRequestID? = nil, asset: PHAsset, onImageTap: @escaping (AddedAsset) -> Void, imageSelected: @escaping (String) -> Bool) {
        _assetLoader = ObservedObject(initialValue: assetLoader)
        self.requestId = requestId
        self.asset = asset
        self.onImageTap = onImageTap
        self.imageSelected = imageSelected
    }
```

## GetStream Environment
**GetStream Chat version: 4.58.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17
**Swift version:** 5.9
**Xcode version:** 15.3
**Device:** iPhone

**Comment by martinmitrevski** [comment]
Hi @masarusanjp,

We have merged your PR in our `develop` branch, it will be available in our next release.

Thanks again for your contribution!

**Comment by masarusanjp** [comment]
Thanks again and for including the fix in the next release. I'm looking forward to it!
