### ISSUE TITLE
Custom long press animation on messages

### ISSUE THREAD

**Issue by bobakemamian** [GetStream/stream-chat-swiftui#559]
## What are you trying to achieve?
The current stream implementation of the tap-and-hold functionality on a message feels unresponsive. I created a video to see the timing/frames of iMessage. See below for what is currently happening vs what we'd like to experience ideally:

**Stream**

- :11 to 1:08 - tap and hold - nothing happens
- 1:08 to 2:00 -  animation to display actions & reactions

**iMessage**

- :11 tap and hold
- :11 to :27 - very light back shadow
- :28 to :58 - enlarges 1px for every :01
- :59 to 1:10 - animation to display actions
- 1:10 to 2:00 - animation to display reactions

**Video**

https://github.com/user-attachments/assets/1a2fd3d9-b4e5-4793-9d6e-935bbebe077e

## If possible, how can you achieve this currently?
Is it possible to override the current animation?

## What would be the better way?
- :11 tap and hold
- :11 to :27 - very light back shadow
- :28 to :58 - enlarges 1px for every :01
- :59 to 1:10 - animation to display actions
- 1:10 to 2:00 - animation to display reactions

## GetStream Environment
**GetStream Chat version:** 4.59
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @bobakemamian,

We use a standard `onLongPressGesture` with a standard duration to invoke the popup.

If you need some specific behaviour or want to mimic the iMessage style animation, you can implement your own message container view (while reusing most of our logic). You can use the `makeMessageContainerView` in the `ViewFactory` for this. When you want to display the popup, you need to call the `onLongPress` closure from this method.

You can check our `MessageContainerView.swift` view for more details.

Hope that helps,
Martin
