### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#56]
## What are you trying to achieve?

I would like to drag and drop photos and files (on iPadOS and macOS) into `ChatChannelListView`, `ChatChannelScreen`, etc.

## If possible, how can you achieve this currently?

As far as I'm aware, you cannot inject attachments programmatically into the message composer without using the built-in attachment system (`AttachmentPicker`/`MessageComposerViewModel`) from the UI itself.

## What would be the better way?

Support the iOS feature of [Drag and Drop](https://developer.apple.com/documentation/uikit/drag_and_drop).

**Comment by martinmitrevski** [comment]
Hey @moubry, 

Thanks for the cool suggestion. Adding attachments is possible outside the attachment picker and the composer. 

You can do this from anywhere by creating a message with payload. More information on how to do this here: https://getstream.io/chat/docs/ios-swift/file_uploads/?language=swift. You can detect the drag and drop event and then upload the content using this API.

Then, you can hook into the custom attachments rendering by following this guide: https://getstream.io/chat/docs/sdk/ios/swiftui/components/message-composer/.

Let me know how this sound to you and whether you think there are blockers to implementing it. We might look into this in the future, but I can't promise anything at the moment.

Best,
Martin

**Comment by moubry** [comment]
Thanks for the quick response! I really appreciate it.

Can a draft message be placed into the message composer input view without sending it? I had assumed that `channelController.createNewMessage` would sent a network request to Stream, bypassing the attachment preview stage where users can write a message to go along with the attachment.

**Comment by martinmitrevski** [comment]
Hey @moubry,

There are two ideas on how to accomplish this:
- The first one, you can just create a custom view (either below the list or as an overlay), and let the user enter the text before the message is sent. You can do this with existing state of the SDK.
- the second idea would be to put it in the input view, as you've suggested. For this, you will need to create a `MessageComposerView` with injectable `MessageComposerViewModel` (not possible atm, but we can enable this for you). Then, when the drag&drop event happens, you could update the `addedCustomAttachments` (or `addedAssets` for videos & photos) of the view model, with your dropped entries. This will display them in the composer.

How does this sound to you?

**Comment by moubry** [comment]
Thanks so much! This kind of detail is exactly what I was looking for — above and beyond!

Our plan is to actually do idea #1 in the short term — we think that having our own custom view, that appears in a sheet, containing a custom TextField, instead of using the Stream composer, would be a great workaround for other reasons too — we’ll also be doing custom attachment types and could take advantage of a larger screen space with which to do composition of these special messages with custom attachment types.

Re: idea #2 — Being able to inject a custom `MessageComposerViewModel` seems broadly useful. This solution sounds good, because this idea of a draft is really only a concern of the composer view. Once I get the draft message in there, I can depend on the rest of the Stream UI for things like attachment previews, attaching items of disparate attachment types in the same message, etc.

**Comment by martinmitrevski** [comment]
Great, glad to hear that @moubry! 

We have allowed the possibility to inject the view model in the `MessageComposerView` and this is now available on `main`, in case you want to go into this direction.

Also, you can provide your own custom attachment preview with `makeCustomAttachmentPreviewView` as described here: https://getstream.io/chat/docs/sdk/ios/swiftui/components/message-composer/#previewing-in-the-message-composers-input-view. The height of the input of the composer can also be controlled with `makeComposerInputView`.

**Comment by martinmitrevski** [comment]
Hey @moubry,

Anything else you need with this issue or can we close it?

Thanks,
Martin

**Comment by moubry** [comment]
@martinmitrevski Sure! Thanks. I should be able to implement drag and drop myself now.
