### ISSUE TITLE
thread not marked as read until scroll of MessageList

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#577]
## What did you do?

open a thread from the ThreadList

## What did you expect to happen?

have the thread marked as read immediately

## What happened instead?

thread is not marked as read until the messagelist is scrolled slightly. if i exit the thread by hitting the back button in the navigation bar, it stays unread.

## Additional context

is there an option to have the thread marked as read as soon as it's opened? or is this a bug?

**Comment by martinmitrevski** [comment]
Hi @AndrewSB, 

Yes, that's the default behaviour. If you like to change it, you can provide a custom implementation of the thread view (via `makeMessageThreadDestination`), that will call mark read `onAppear`. You can still use the default SDK view in this case.

Hope that helps,
Martin
