### ISSUE TITLE
Custom reaction picker gets cut off for short messages

### ISSUE THREAD

**Issue by f3dm76** [GetStream/stream-chat-swiftui#579]
## What did you do?
I used `makeReactionsContentView` to add custom emoji picker

## What did you expect to happen?
I expected my custom picker to take get the place it needs

## What happened instead?
It got cut off for short messages

## GetStream Environment
GetStream Chat version: StreamChat 4.61.0, StreamChatSwiftUI 4.61.0
GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
iOS version: ios 18.0
Swift version: 5
Xcode version: 15.0.1
Device: sim iPhone 15 Pro Max

## Additional context
Code (GeometryReader to force it to take more space, still not working)
```
    func makeReactionsContentView(message: ChatMessage, contentRect: CGRect, onReactionTap: @escaping (MessageReactionType) -> Void) -> some View {
        GeometryReader { g in
            Text("Custom emoji picker")
        }
        .border(Color.red, width: 2)
    }
```

For these photos custom picker is just a Text, and I added red border to it. You can see how it's cut off for short messages.
![Simulator Screenshot - iPhone 15 Pro Max 18 0 - 2024-08-13 at 14 20 11](https://github.com/user-attachments/assets/bdcba4f2-72a3-46c4-a332-5dd2cc9e8a80)
![Simulator Screenshot - iPhone 15 Pro Max 18 0 - 2024-08-13 at 14 20 11](https://github.com/user-attachments/assets/1bdd4ac8-124b-4206-a0e0-945c1829376e)

**Comment by martinmitrevski** [comment]
Hi @f3dm76,

Everything here works as expected - the message bubble is not cut off and the proposed size from the geometry reader reflects that. You also have the `contentRect: CGRect` parameter that tells you how big this view should be, so you don't really need a geometry reader.

If you want to have a custom text instead of the reactions picker, then you probably need a custom implementation of the whole reactions overlay, because this view slot is not meant to be used like you intended. Another option is to check if the text fits into the content rect, and if not, explicitly set the size of your text view with a bigger width.

Hope that helps,
Martin

**Comment by f3dm76** [comment]
Hello, could you please advise how do I make a "custom implementation of the whole reactions overlay"? I thought makeReactionsContentView is exactly that.

In the end, I'd like a custom reaction picker. I want to use standard emojis.

**Comment by martinmitrevski** [comment]
If you just want to change the emojis themselves, you don't really need a custom view. You can just update the `availableReactions` property with your own icons: 
https://getstream.io/chat/docs/sdk/ios/swiftui/message-components/message-reactions/#customizing-the-message-reactions-view

**Comment by f3dm76** [comment]
I need to update the picker itself to make it display last 30 selected emojis in a scrollable line, with a button to show standard emoji keyboard and be able to pick any standard apple emoji. What you are suggesting looks like it'll require adding a huge enum and all the emojis in the world as pictures. Is there an option to use all standard emojis as reactions?

**Comment by f3dm76** [comment]
Hey @martinmitrevski, is it possible to send emojis (basically a string) as a reaction?

Here is how I'm trying to do it:
```
func makeReactionsContentView(message: ChatMessage, contentRect: CGRect, onReactionTap: @escaping (MessageReactionType) -> Void) -> some View {
        GeometryReader { g in
            HStack {
                ForEach(EmojiPicker.shared.lastUsedEmoji) { emoji in
                    Text(emoji)
                        .onTapGesture {
                            onReactionTap(MessageReactionType(stringLiteral: emoji))
                        }
                }
            }
        }
    }
```

I see the following error message:
```
2024-08-14 14:28:13.899 [ERROR] [io.getstream.logger] [RequestDecoder.swift:67] [decodeRequestResponse(data:response:error:)] > API request failed with status code: 400, code: 4 response:
{
  "details" : [

  ],
  "exception_fields" : {
    "reaction.type" : "reaction.type is not valid. Only alphanumeric, underscore, dash and dot characters are allowed"
  },
  "code" : 4,
  "StatusCode" : 400,
  "message" : "SendReaction failed with error: \"reaction.type is not valid. Only alphanumeric, underscore, dash and dot characters are allowed\"",
  "duration" : "0.00ms",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response"
})
```

**Comment by martinmitrevski** [comment]
I assume you are sending the emoji code, which contains special characters like +, which are not allowed. You can probably strip those when you send them to the backend, and reconstruct them (add back the stripped part, when you are about to display them).
