### ISSUE TITLE
Background task still not ended after expiration handlers were called (App being terminated)

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swiftui#588]
## What did you do?
Open a chat, close a chat. Send app to background

## What did you expect to happen?
No warnings or terminations.

## What happened instead?
The app gets terminated very often after i open a chat. 
I've did several tests in which i open my application do multiple things without opening chat and send to background and i have no system terminations.
Then  after some debugging i've noticed i'm getting multiple warnings regarding background tasks that are not completed.

```
Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x3008deb40>: taskID = 107, taskName = Called by x, from $s10StreamChat26IOSBackgroundTaskSchedulerCAA010BackgrounddE0A2aDP05beginD017expirationHandlerSbyycSg_tFTW, creationTime = 107640 (elapsed = 129). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.
Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x30077a540>: taskID = 90, taskName = Called by x, from $s10StreamChat26IOSBackgroundTaskSchedulerCAA010BackgrounddE0A2aDP05beginD017expirationHandlerSbyycSg_tFTW, creationTime = 107440 (elapsed = 329). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.
Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x30077bd00>: taskID = 91, taskName = Called by x, from $s10StreamChat26IOSBackgroundTaskSchedulerCAA010BackgrounddE0A2aDP05beginD017expirationHandlerSbyycSg_tFTW, creationTime = 107440 (elapsed = 329). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.
```

## GetStream Environment
**GetStream Chat version:** 4.62.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.6.1
**Swift version:** 5+
**Xcode version:** 15.3
**Device:** iPhone 11 Pro, iPhone 15

**Comment by martinmitrevski** [comment]
Hi @fceldeiro,

By default, we try to keep the WebSocket connection open for some time and we start background tasks. You can disable this behaviour by setting `staysConnectedInBackground` to false in the `ChatClientConfig`, which is part of the `ChatClient`.

Hope that helps,
Martin
