### ISSUE TITLE
`ChatChannelListItem` no longer loading provided avatar

### ISSUE THREAD

**Issue by ktreangen-at-ramsey** [GetStream/stream-chat-swiftui#602]
## What did you do?

Updated from version `4.60.0` to `4.62.0`

## What did you expect to happen?

That custom avatars provided through the following `ViewFactory` implementation would work as they do in `4.60.0`

```
  @MainActor
  func makeChannelListItem(
      channel: ChatChannel,
      channelName: String,
      avatar: UIImage,
      onlineIndicatorShown: Bool,
      disabled: Bool,
      selectedChannel: Binding<ChannelSelectionInfo?>,
      swipedChannelId: Binding<String?>,
      channelDestination: @escaping (ChannelSelectionInfo) -> ChatChannelView<CustomStreamChatChannelListFactory>,
      onItemTap: @escaping (ChatChannel) -> Void,
      trailingSwipeRightButtonTapped: @escaping (ChatChannel) -> Void,
      trailingSwipeLeftButtonTapped: @escaping (ChatChannel) -> Void,
      leadingSwipeButtonTapped: @escaping (ChatChannel) -> Void
  ) -> ChatChannelListItem {
      return ChatChannelListItem(
          channel: channel,
          channelName: channelName,
          avatar: <custom UIImage here>
          onlineIndicatorShown: false,
          onItemTap: onItemTap
      )
  }
```

## What happened instead?

Default / empty avatars are loaded within each `ChatChannelListItem` instead of the custom `avatar` that is passed through the `ChatChannelListItem` initializer.

## GetStream Environment
**GetStream Chat version:** 4.62.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 17.5
**Swift version:** 5
**Xcode version:** 15.4
**Device:** Simulator

## Additional context

This appears to have been introduced in `4.61.0` through the following change: https://github.com/GetStream/stream-chat-swiftui/commit/e4a405e9ffe112743c3f705aa5810047f41627ff#diff-8560b06fdfd635f730bc8b770188c74f87f3f61bf566bc2568ae78954d3a0422R49.

My organization does not use any sort of remote avatars and we want to build and show these locally within our iOS application itself. If there a way to still do this in `4.61.0`+ through `ChatChannelListItem`?

**Comment by laevandus** [comment]
Hi,

The best way for providing custom avatars is using a custom `ChannelHeaderLoader`.

Here is an example.
Configure your `StreamChat` instance like this:
```swift
let utils = Utils(
  channelHeaderLoader: CustomChannelHeaderLoader()
)
streamChat = StreamChat(chatClient: chatClient, utils: utils)
```
where 
```swift
class CustomChannelHeaderLoader: ChannelHeaderLoader {
  override func image(for channel: ChatChannel) -> UIImage {
    UIImage(resource: .STREAMMARK) // my custom image
  }
}
```
<img width="514" alt="Screenshot 2024-09-12 at 09 46 53" src="https://github.com/user-attachments/assets/5fd07d82-e3b0-4578-bc36-34457f7d11fe">

Please let me know if you need any additional information.

Best,
Toomas

**Comment by ktreangen-at-ramsey** [comment]
> Contributor

Hello @laevandus ,

I actually tried this previously but it turns out the `image(:)` `func` is not `open` and therefore we cannot `override` it.

```
public func image(for channel: ChatChannel) -> UIImage
```

![Screenshot 2024-09-12 at 8 39 08 AM](https://github.com/user-attachments/assets/f6218366-a655-43d2-bb99-60f5d9ba764b)

Regards,
Kurt
