### ISSUE TITLE
Social preview image not displaying on links

### ISSUE THREAD

**Issue by bobakemamian** [GetStream/stream-chat-swiftui#638]
## What did you do?
I pasted in a link example: http://topfloorclub.com/invitations and the social preview image is blank.

## What did you expect to happen?
I expected it to display the social preview image like this:

![CleanShot 2024-11-01 at 16 05 11@2x](https://github.com/user-attachments/assets/fa78bf8b-c068-4a50-bc5e-8329d46489ee)

## What happened instead?
It is displaying a blank black image:
![IMG_4404](https://github.com/user-attachments/assets/894c71e6-ef33-4674-8457-4cdc34a291cc)

## GetStream Environment
**GetStream Chat version:** 4.65
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 18.1
**Swift version:**
**Xcode version:**
**Device:** iPhone 16 Pro Max

**Comment by martinmitrevski** [comment]
Hi @bobakemamian,

Client-side we rely on the scraping done by the backend. If there's some issue with certain links, best to reach out to our support team - there's not much that can be done on iOS side here.

Best, Martin
