### ISSUE TITLE
How to search the DM channel?

### ISSUE THREAD

**Issue by spartan-tinhnguyen** [GetStream/stream-chat-swiftui#644]
## What are you trying to achieve?
I'm trying to implement a search feature for Direct Message (DM) channels, but the SDK currently does not support this functionality. Having this feature would improve the user experience by enabling quick access to specific DM channels.

## If possible, how can you achieve this currently?
Currently, I can not search DM channels with ChatChannelListView and searchType `.channels`
```
ChatChannelListView(
      viewFactory: DefaultViewFactory.shared,
      embedInNavigationView: false,
      searchType: .channels
    )
```

**Comment by nuno-vieira** [comment]
Hi @spartan-tinhnguyen,

At the moment, we do not support this, but we plan to support it in the future. Unfortunately, I do not have an ETA for this at the moment since this is dependent on the backend. 

Best,
Nuno

**Comment by spartan-tinhnguyen** [comment]
Hi @nuno-vieira 
I see the Android SDK supports this, can you check?

**Comment by nuno-vieira** [comment]
Hi @spartan-tinhnguyen,

So, after discussing it internally, it seems that Android is using a query which is not recommended and will cause performance issues at the moment.

As I said previously this needs to be improved on our side, but we do not have an ETA at the moment. I recommend you reach out support here: https://getstream.io/contact/support/

You will then be notified once we start working on this.

Best,
Nuno
