### ISSUE TITLE
Read only access to `MessageCachingUtils`

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#65]
## What are you trying to achieve?
Hello. We would like to have public read only access to `MessageCachingUtils`.
It would avoid us to repeat the same functionality on our side.

## If possible, how can you achieve this currently?
I am accessing `message.author` property which is lazy var and is not recommended to be use used from performance perspective.

## What would be the better way?
Better way would be to access `MessageCachingUtils` and have only read only access.

**Comment by martinmitrevski** [comment]
Hello @GeorgeVashakidze, 

We can expose additional variable that will return a cached display info of the author. Something like this:
```swift
extension ChatMessage {
    
    public var authorDisplayInfo: UserDisplayInfo {
        let cachingUtils = InjectedValues[\.utils].messageCachingUtils
        return cachingUtils.authorInfo(from: self)
    }
    
}
```
Will this solve your issue? 

We would like to keep the `MessageCachingUtils` private, since we want to have the flexibility to change it in the future.

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski yeah, this would solve the issue but would be also nice to have ability to get user info by Id. That would be awesome as well. Thanks a lot in advance

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, which id you mean? the message id or the user display info id?

**Comment by GeorgeVashakidze** [comment]
user id

**Comment by martinmitrevski** [comment]
@GeorgeVashakidze, this is now available on main:

```swift
extension ChatMessage {
    
    public var authorDisplayInfo: UserDisplayInfo {
        let cachingUtils = InjectedValues[\.utils].messageCachingUtils
        return cachingUtils.authorInfo(from: self)
    }
    
    public func userDisplayInfo(from id: String) -> UserDisplayInfo? {
        let cachingUtils = InjectedValues[\.utils].messageCachingUtils
        return cachingUtils.userDisplayInfo(with: id)
    }
    
}
```

**Comment by GeorgeVashakidze** [comment]
Thanks a lot
