### ISSUE TITLE
Palette colors are not fully applied to poll views

### ISSUE THREAD

**Issue by f3dm76** [GetStream/stream-chat-swiftui#657]
## What did you do?
I used SC in SwiftIUI with custom colors and mostly default views, and added poll functionality

## What did you expect to happen?
The custom colors I specified should have been applied to polls too

## What happened instead?
They were not applied fully. I added a PR fixing that https://github.com/GetStream/stream-chat-swiftui/pull/656

## GetStream Environment
**GetStream Chat version:** 4.66
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI 4.66
**iOS version:** 18.0
**Swift version:** 6.0
**Xcode version:** 16.0
**Device:** sim iphone 16 pro max

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
