### ISSUE TITLE
Reply Composer Animation Missing

### ISSUE THREAD

**Issue by kylecfoley** [GetStream/stream-chat-swiftui#66]
## What did you do?

Initiate reply to a message

## What did you expect to happen?

On older releases, when replying there was fade animation on the message composer's title "Reply to Message" and close (x) button during open and close. This appears to have been removed in a recent release and feels less smooth, especially on open. 

Old Behavior:

https://user-images.githubusercontent.com/13056226/168217693-741c04ca-bc15-4eef-9310-d51d8151e0e6.MOV

## What happened instead?

New behavior:

https://user-images.githubusercontent.com/13056226/168217978-bf5734ae-57f3-41b5-82d3-295255f4f72a.MOV

Reply title now collides with contents in chat. 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context

**Comment by martinmitrevski** [comment]
Hey @kylecfoley,

Thanks for reporting the issue. We have fixed this and the change is now available on our `main` branch.

Regards,
Martin

**Comment by kylecfoley** [comment]
Great, thanks!
