### ISSUE TITLE
ChatChannel in makeLeadingComposerView

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#67]
## What are you trying to achieve?

I’m trying to make a custom leading composer view that presents a custom sheet where the user can perform an action on the current channel.

However, the parameters for `makeLeadingComposerView` do not provide a way to know what the current channel is.

## If possible, how can you achieve this currently?

I’m not sure quite how I might accomplish this. I would need to track when the user navigates within the context of the current window.

## What would be the better way?

Ideally, the `ViewFactory` function `makeLeadingComposerView` would give me `channel: ChatChannel` (similar to `makeChannelHeaderViewModifier`) so that I know what the current context is.

**Comment by martinmitrevski** [comment]
Hey @moubry, 

Thanks for asking the question. One way to achieve this would be to inject `ChatChannelListViewModel` in your `ChatChannelListView`, and add a `onReceive` modifier in your root view where you would listen to the `selectedChannel` @Published property of the view model. 

Then, you could save this state in your own classes (either in your root view as a state, or as a property in your custom view factory, or any other state holder depending on your app architecture) and read it in the `makeLeadingComposerView`. Another option for passing the state downwards to the factory method, is to extend our DI with your custom classes, as described here: https://getstream.io/chat/docs/sdk/ios/swiftui/dependency-injection/#extending-the-di-with-custom-types.

Changing the factory method to include the channel, as you've suggested, would be a breaking change, which we might consider for a major version upgrade (v5), but that will not come soon.

Hope this helps,
Martin

**Comment by moubry** [comment]
Thanks for the quick response!
