### ISSUE TITLE
Catalyst: Windows Resizing Issue with ChatChannelView

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#68]
## What did you do?

Went through [the tutorial](https://getstream.io/tutorials/swiftui-chat/) to create a new app using the SwiftUI framework for Stream. Ran the project on My Mac — both Catalyst and Designed for iPad.

When you resize the window larger, everything goes well, but when you resize the window back down, the leading edge content (the chat messages) slides underneath the sidebar of the navigation view (channel list).

## What did you expect to happen?

I expected the messages within the channel to stay visible.

## What happened instead?

The messages on the left-hand side of the channel view get obscured by the channel list.

## GetStream Environment
**GetStream Chat version:** main
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.2 (Catalyst)
**Swift version:** 5.6
**Xcode version:** Version 13.3.1 (13E500a)
**Device:** Issue occurs on both Mac Studio (Catalyst) and Mac Studio (Designed for iPad)

## Additional context

As a work around, I attempted to implement my own custom `ChannelListView` with my own NavigationView, but the issue persisted, indicating that it's likely an issue local to the `ChatChannelView` or `MessageListView`?

## Video

https://user-images.githubusercontent.com/144283/168390385-ddf87c73-d460-481c-bf3b-7ff13d2e1caf.mov

**Comment by martinmitrevski** [comment]
Hey @moubry, 

Thanks for reporting this. Adding proper macOS support is planned in our roadmap, but we still officially don't support it at the moment.

In any case, we will analyse the issue and update you when we have more info.

Best,
Martin

**Comment by moubry** [comment]
Thanks! For what it’s worth, everything works very well on macOS so far.
This is really the only issue I’ve found. That and hitting the Return key
doesn’t send the message, but I should be able to figure that one out.

**Comment by martinmitrevski** [comment]
Hey @moubry,

We have fixed the macOS issue. The change is available on our `main` branch, and it will be included in our next release.

Thanks for your patience. 
Best,
Martin
