### ISSUE TITLE
Localization provider on Swift 6

### ISSUE THREAD

**Issue by andrej-jasso** [GetStream/stream-chat-swiftui#694]
## What did you do?
<img width="871" alt="Screenshot 2024-12-18 at 12 57 08" src="https://github.com/user-attachments/assets/96c1bc02-906a-4cab-8c3a-738872f900f9" />

## What did you expect to happen?
I wanted to be able to switch localization provider like it is documented in the readme but I can't do so on an Swift 6 project.

## GetStream Environment
**GetStream Chat version:** Newst GetstreamSwiftUI as of now 4.68.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 18.1
**Swift version:** 6.0
**Xcode version:** 16.1
**Device:** SE 3rd gen simulator

**Comment by testableapple** [comment]
Hi @andrej-jasso, which version of StreamChatSwiftUI do you use?

**Comment by andrej-jasso** [comment]
> Hi @andrej-jasso, which version of StreamChatSwiftUI do you use?

1.2.2

**Comment by andrej-jasso** [comment]
![Screenshot 2024-12-18 at 13 13 46](https://github.com/user-attachments/assets/a7714e23-27e3-4a96-a8e5-f7bd01cab553)
This is the workaround, but it's not ideal to have to use preconcurrency

**Comment by andrej-jasso** [comment]
<img width="490" alt="Screenshot 2024-12-18 at 13 20 09" src="https://github.com/user-attachments/assets/0220e5cd-1221-415f-b731-46938d1f6739" />
Sorry typo. I think I looked at the wrong dependency. This si the number

**Comment by testableapple** [comment]
@andrej-jasso, unfortunately, we have not fully migrated to Swift 6, so at the moment, using the `@preconcurrency` annotation is the only option.
