### ISSUE TITLE
'SystemMessageView' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#71]
It looks like SystemMessageView is intended to be public, but cannot be used because it’s missing a public initializer. (I have no idea why the designers of Swift decided that memberwise initializers must be internal.)

**Comment by martinmitrevski** [comment]
Hey @moubry,

Thanks for reporting this. Yes, that's correct. 

The public init method is now available on our `main` branch, and it will also be included in our next release.

Best, 
Martin

**Comment by moubry** [comment]
[Looks good.](https://github.com/GetStream/stream-chat-swiftui/commit/b881dcdf1c795a4d7c08cac3cd4945e67f447520) Thank you!
