### ISSUE TITLE
'AttachmentPickerTypeView' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#72]
i guess the access level of `pickerTypeState` is the culprit.

**Comment by martinmitrevski** [comment]
Hey @zrxq, 

Thanks for reporting this. We have made the `AttachmentPickerTypeView` init method public now.

The change is available on our `main` branch and it will be included in our next release.

Best,
Martin

**Comment by zrxq** [comment]
Hey @martinmitrevski, 

Thanks for the response! What about other factory-instantiated components, for example `SendMessageButton` and `SlowModeView`? Right now It's somewhat difficult to customize, for example, the message composer without having half of the code copied into my project, mostly because of the access situation.

**Comment by martinmitrevski** [comment]
Hey @zrxq,

You can always take the default implementation of a view by calling DefaultViewFactory.shared.theNameOfTheMethod. For example for the trailing composer view, you can call `DefaultViewFactory.share.makeTrailingComposerView` and this will return the default view shown on the trailing side of the composer.

In any case, there's no need to copy anything from the existing implementation, you just need to modify the endpoint you need via its corresponding factory method.

Can you please share your use-case? What do you want to customize and why do you need access to our internal views?

Thanks,
Martin

**Comment by zrxq** [comment]
Well, I'm trying to customise the appearance so it matches a design I have, preferably pixel-perfect. The thing is, there's a bunch of places in Stream Chat SwiftUI that have the stuff hardcoded, e.g. the composer view paddings. Or, another example, `ColorPalette.composerPlaceholderColor` is not actually used in the composer UITextView (`subtitleText` is). I'm on a somewhat tight time budget, so I'm a bit hesitant to replace the entire component's code with my own, which leads to this situation, where I want to reuse as much existing code as possible while ditching the parts (often, containers for other components) that are not customisable enough to be used as is.

**Comment by martinmitrevski** [comment]
@zrxq, thanks for the feedback, much appreciated. 
About the composer, here are few tips that might help you with the customizations:
- in regards to paddings, you can use the `makeComposerViewModifier` to adjust paddings / background to the main composer view.
- for the smaller components, the technique I've mentioned above should work - loading the default view first and then applying some custom modifier. For example, for the trailing view, you can do something like this:
```swift
public func makeTrailingComposerView(
        enabled: Bool,
        cooldownDuration: Int,
        onTap: @escaping () -> Void
    ) -> some View {
     let defaultView = DefaultViewFactory.shared. makeTrailingComposerView(enabled: enabled, cooldownDuration: cooldownDuration, onTap: onTap)
   defaultView.modifier(YourCustomModifier())
   return defaultView
}
```
- some config is also available via the `ComposerConfig`, such as the initial height of the text input and the font.

You are right about the `composerPlaceholderColor`, it's a bug in the SDK that we will fix.

If there's anything else that we can do with smoother integration of our SDK to your project, please let us know.

Best,
Martin

**Comment by zrxq** [comment]
Hey Martin,

Thank you for the pointers! 

I don't think I can use `makeComposerViewModifier` to reduce padding for the composer input view introduced in `MessageComposerView`, but, anyway, I worked around the issue. 

Thanks again for the detailed response!

Regards,
Zor
