### ISSUE TITLE
Place Date Indicator in Message List

### ISSUE THREAD

**Issue by kylecfoley** [GetStream/stream-chat-swiftui#73]
## What are you trying to achieve?

Place Date Indicator in message list.

## If possible, how can you achieve this currently?

It is available in Swift SDK but not SwiftUI SDK.

```
/// Defines where the date indicator in the message list is placed.
public enum DateIndicatorPlacement {
  case none
  case overlay
  case messageList // Not supported yet.
}
```

Thanks!

**Comment by martinmitrevski** [comment]
Thanks @kylecfoley for the report. 

This is already in our roadmap, and it should be coming some time this quarter.

Best,
Martin

**Comment by kylecfoley** [comment]
Perfect, thanks @martinmitrevski 💯

**Comment by martinmitrevski** [comment]
Hey @kylecfoley, 

We now have this feature available on our `main` branch.

To use it:

```swift
let utils = Utils(messageListConfig: MessageListConfig(dateIndicatorPlacement: .messageList))
let streamChat = StreamChat(chatClient: chatClient, utils: utils)
```

If you want to replace the separating date indicator view, you need to implement the `makeMessageListDateIndicator` method. You can control the size of this view view with the `overlayDateLabelSize` in the `MessageDisplayOptions`.

```swift
public func makeMessageListDateIndicator(date: Date) -> some View {
    DateIndicatorView(date: date)
}
```

Looking forward to your feedback.

**Comment by kylecfoley** [comment]
Amazing, thanks @martinmitrevski !
