### ISSUE TITLE
makeLoadingView not called

### ISSUE THREAD

**Issue by Subtextaps** [GetStream/stream-chat-swiftui#74]
What did you do?
Updated the package dependency to StreamChatSwiftUI 4.15.0

What did you expect to happen?
The method to be called as it was before updating the SDK

What happened instead?
Nothing. The method is implemented in a ViewFactory instance and was called correctly under the previous package

GetStream Environment
**GetStream Chat version: 4.15.0
**GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
**iOS version: 15.2
**Swift version: 5
**Xcode version: 13.2
**Device: iPhone 13 Pro Max (Xcode Simulator 13.2)

**Comment by martinmitrevski** [comment]
Hey @Subtextaps,

Thanks for reporting this. One question: do you have offline mode enabled? Since if you do, the changes are immediately loaded from DB for an existing user and there's no loading screen in place.

This is the behaviour we also have in 4.14.0, since we haven't made any changes in the loading view logic in the latest 4.15.0 release.

To verify this, could you please try with a different simulator to see if you get the loading screen the first time?

If it's still an issue, please share some sample code for troubleshooting.

Regards,
Martin

**Comment by Subtextaps** [comment]
Hi @martinmitrevski,

Thanks for the feedback.

We've tried different simulators and also a physical device with breakpoints set in Xcode. But makeLoadingView is still not being called. 

I'm not familiar with the details of your offline mode yet. How do I check if it's enabled?

**Comment by martinmitrevski** [comment]
@Subtextaps the offline mode is configured when you initialize the chat client's config. This is the line that invokes it:
```swift
var config = ChatClientConfig(apiKey: .init(apiKeyString))
config.isLocalStorageEnabled = true
```
Also, sometimes I have to delete derived data to get the latest view factory changes. Maybe you can try this as well?
If that doesn't solve it, could you please try again with the previous version to see if it's really a regression in the current one?

**Comment by Subtextaps** [comment]
@martinmitrevski

Thanks for the details.
 
 I've tried running a new instance of the ChatClient with isLocalStorageEnabled = false
makeLoadingView is still not called.

I'll try out your other suggestions and report back.

**Comment by martinmitrevski** [comment]
Hey @Subtextaps,

Any news here? Did you manage to make it work with the suggestions?

Thanks,
Martin

**Comment by Subtextaps** [comment]
Hi @martinmitrevski,

I also tried deleting derived data but that didn't help either. I haven't had time to go back to the previous version yet but will try that too when I get the time.

Thanks for the help so far. Really appreciated!

Thomas

**Comment by martinmitrevski** [comment]
Closing this one due to inactivity. Let us know if additional help is needed.
