### ISSUE TITLE
Is it possible to intercept scroll position changes?

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#75]
Hi, 

I need to somehow know when the message list scroll view has the content offset changed (to update my customized UI – I have a shadow that is supposed to disappear when there's no more content to scroll). Do you think that's possible at all in the current implementation? I mean, without resorting to enumerating the underlying UIKit subviews and observing properties.

**Comment by martinmitrevski** [comment]
Hey @zrxq,

Here's one idea: 
- Create a subclass of `ChatChannelViewModel` and override the `handleMessageAppear` method, with additional check, sth like this:
```swift
@Published var shouldShowShadow = true

override func handleMessageAppear(index: Int) {
    if index == messages.count - 1 {
            shouldShowShadow = false
    } else if index < messages.count - 10 {
           shouldShowShadow = true
    }
    super.handleMessageAppear(index: index)
}
```
Then, you can inject this view model in the `ChatChannelView` - specifically in the `makeChannelDestination` method in the view factory.

Do you think this approach might help?

**Comment by martinmitrevski** [comment]
Any update here @zrxq? Do you think the approach above could be useful to you?
If not, is there anything else we can help you with regarding this issue?

**Comment by zrxq** [comment]
Hey Martin,

Sorry, at the end of the day the particular feature got canned 🤷‍♀️

In any case, thank you for helping and providing ideas!
