### ISSUE TITLE
Attachments ignore MessageListConfig.messagePaddings

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#77]
## What did you do?

```
        let mlc = MessageListConfig(messagePaddings: MessagePaddings(horizontal: 40) )
        let utils = Utils(messageListConfig: mlc)
         streamChat = StreamChat(chatClient: chatClient, appearance: appearance, utils: utils)
```

## What did you expect to happen?

All messages paddings affected.

## What happened instead?

Attachments are not affected.

![Simulator Screen Shot - iPhone 13 - 2022-05-25 at 17 50 08](https://user-images.githubusercontent.com/820120/170292242-49c70b17-6179-46ab-9ab8-347d2b0b9360.png)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @zrxq,

Thanks for reporting this. The issue is fixed now and available on `main`. 

It will be also included in the release next week.

Regards,
Martin

**Comment by zrxq** [comment]
@martinmitrevski Thank you!
