### ISSUE TITLE
Long boring messages break scroll to bottom functionality

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#78]
## What did you do?

Launched the demo app, copied and pasted a paragraph from a random Wikipedia article, scrolled up, maybe tapped on the input field to make the keyboard visible, tapped "scroll to bottom" button.

## What did you expect to happen?

Most recent message is visible.

## What happened instead?

It doesn't scroll to the correct location.

![RocketSim_Recording_iPhone_13_mini_2022-05-26_20 04 59](https://user-images.githubusercontent.com/820120/170539519-7b6526e3-ca8d-45b5-b682-3676ea44a316.gif)

## GetStream Environment
**GetStream Chat version:** 4.15 I think
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13
**Device:** Sim

**Comment by martinmitrevski** [comment]
Hi @zrxq,

Thanks for reporting the issue.

We will analyze it and let you know when we have an update.

Regards,
Martin

**Comment by grandsir** [comment]
@martinmitrevski Any hopes on this?

**Comment by martinmitrevski** [comment]
it's lower priority for now, can't tell when we will tackle it.

**Comment by laevandus** [comment]
Hi, I have been looking into this issue and although I can see what happened on the screen recording, I am struggling to find ways how to reproduce this case. Seems like keyboard was dismissed while the scrolling was in progress which made ScrollView to lose the scroll location. 
If we could figure out steps (or create a channel in the demo app) where it would reproduce, then that could give us more hints what exactly happened and why the keyboard was dismissed. Until then it is difficult proceed with it. Maybe, it is fixed indirectly by some other changes, not sure. Please reopen if you happen to find a way to reproduce this again.
