### ISSUE TITLE
Replying to a message from the menu is broken

### ISSUE THREAD

**Issue by ed-smokefree** [GetStream/stream-chat-swiftui#81]
## What did you do?
Hold down on a message, from the menu tap 'Reply'.

## What did you expect to happen?
It should have displayed the reply interface (like it does when you swipe a message to reply).

## What happened instead?
It shows a blank space. If you swipe to reply a message after this has happened then that doesn't work either, unless you go back to the message list and revisit the screen (as shown in the attached video).

## GetStream Environment
**GetStream Chat version:** 4.15.0 (master branch)
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** iOS 15.5
**Swift version:** Swift 5
**Xcode version:** Version 13.4 (13F17a)
**Device:** Simulator (iPhone 13 Pro)

## Additional context
Video here: https://www.dropbox.com/s/yviszpnk5s2avvl/Screen%20Recording%202022-05-30%20at%2012.15.33.mov?dl=0

**Comment by martinmitrevski** [comment]
Hey @ed-smokefree,

Thanks a lot for reporting this. It was indeed a regression in one of our latest commits. 

In any case, we have fixed the issue now and the fix is available on `main`. 

Best,
Martin

**Comment by ed-smokefree** [comment]
Hi @martinmitrevski 

Thanks for your quick reply and resolution, I can confirm that it's now working!

All the best,
Ed
