### ISSUE TITLE
The initial height when editing a message is incorrect

### ISSUE THREAD

**Issue by ed-smokefree** [GetStream/stream-chat-swiftui#82]
## What did you do?
Hold down on a message, from the menu tap 'Edit message'.

## What did you expect to happen?
The height of the message would accommodate 3 lines as it does when writing a message.

## What happened instead?
The initial height is smaller than expected, displaying 1 line of text and requiring scrolling (as shown in the attached video). If you change a character then the height updates to what it should be.

## GetStream Environment
**GetStream Chat version:** 4.15.0 (master branch)
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** iOS 15.5
**Swift version:** Swift 5
**Xcode version:** Version 13.4 (13F17a)
**Device:** Simulator (iPhone 13 Pro)

## Additional context
Video here: https://www.dropbox.com/s/p85k454gz14t59h/edit_message_layout.mov?dl=0

**Comment by martinmitrevski** [comment]
Hey @ed-smokefree,

Thanks for reporting this. We will analyse the issue and let you know as soon as we have an update.

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @ed-smokefree,

This one is also fixed now. The fix is available on `main` and will go into our next release.

Best,
Martin
