### ISSUE TITLE
Leaving a group doesn't take you back to the channel list

### ISSUE THREAD

**Issue by ed-smokefree** [GetStream/stream-chat-swiftui#83]
## What did you do?
Open a group, tap the settings, choose 'leave group' and confirm.

## What did you expect to happen?
Upon leaving the group it should send you back to the channel list (as it does in the stream-chat-swift app).

## What happened instead?
You remain viewing the conversation and can still send messages, making it seem like you haven't left the group. You can also view the group settings again and keep attempting to leave the group which is confusing. Manually navigating back to the channel list resolves the issue.

## GetStream Environment
**GetStream Chat version:** 4.15.0 (master branch)
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** iOS 15.5
**Swift version:** Swift 5
**Xcode version:** Version 13.4 (13F17a)
**Device:** Simulator (iPhone 13 Pro)

## Additional context
Video here: https://www.dropbox.com/s/x2zcb74vvpj3nzb/leave_group.mov?dl=0

**Comment by martinmitrevski** [comment]
Hey @ed-smokefree,

Thanks again for reporting the issues. This one is also fixed now and available on `main`.

Best,
Martin
