### ISSUE TITLE
Searching channels, then cancelling and selecting a channel crashes

### ISSUE THREAD

**Issue by ed-smokefree** [GetStream/stream-chat-swiftui#84]
## What did you do?
Search for a channel, then cancel, then select a channel from the list and the app crashes.

## What did you expect to happen?
The app would open the channel without crashing.

## What happened instead?
The app crashed `Swift/ContiguousArrayBuffer.swift:575: Fatal error: Index out of range`.

## GetStream Environment
**GetStream Chat version:** 4.15.0 (master branch)
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** iOS 15.5
**Swift version:** Swift 5
**Xcode version:** Version 13.4 (13F17a)
**Device:** Simulator (iPhone 13 Pro)

## Additional context
Video here: https://www.dropbox.com/s/4xui1nt4o30sht1/crash.mov?dl=0
Crash report here: https://www.dropbox.com/s/n0pfga2xu24dd70/SwiftUIChatDemo-2022-05-30-151603.ips?dl=0

**Comment by martinmitrevski** [comment]
Hey @ed-smokefree,

Thanks for reporting the issue. I wasn't able to reproduce it, but the crash report you've attached helped in finding the root cause.

I've provided a fix on the `main` branch. Can you please test again if you experience the crash?

**Comment by ed-smokefree** [comment]
Thanks @martinmitrevski that has fixed it.

I am impressed with the SDK and how fast you've been at addressing issues.

**Comment by martinmitrevski** [comment]
Awesome, glad to hear that @ed-smokefree!
