### ISSUE TITLE
Update to Use Latest Stream SDK Version

### ISSUE THREAD

**Issue by davefoxy** [GetStream/stream-chat-swiftui#85]
## What are you trying to achieve?

A fix was made in the Stream SDK repo recently which is required in our application. It was merged recently here: https://github.com/GetStream/stream-chat-swift/pull/2028. It would be great if StreamSwiftUI could update its dependency to bring this in.

## GetStream Environment
**GetStream Chat frameworks:** StreamChatSwiftUI (master branch)
**iOS version:** All
**Swift version:** All
**Xcode version:** All
**Device:** All

**Comment by martinmitrevski** [comment]
Hey @davefoxy, 

Thanks for reporting this. We change the dependency after the Stream SDK is released, which is planned to happen this Wednesday.

If you need it sooner, please let me know and I'll create a branch for you to use it in the meantime.

Best,
Martin

**Comment by davefoxy** [comment]
@martinmitrevski Thanks for your reply. Yes, if this is possible, that'd be great 🙏

**Comment by martinmitrevski** [comment]
Hey @davefoxy, I've created a new branch called `stream-chat-develop` that uses the StreamChat SDK from develop. You can use this one in the next few days, until we release both SDKs.

I'll leave this issue open to ping you when you can switch back to `main` (or the release version).

**Comment by davefoxy** [comment]
Thanks @martinmitrevski !
Works well 🙇

**Comment by martinmitrevski** [comment]
Hey @davefoxy,

We have finally released StreamChat, so now the SwiftUI SDK uses the latest version (4.16.0), both on our `main` branch and its own 4.16.0 release.

Sorry for the delay,
Martin
