### ISSUE TITLE
Open 1-1 chat window directly, Instead of showing list of channels.

### ISSUE THREAD

**Issue by zeeshansuleman** [GetStream/stream-chat-swiftui#87]
## What are you trying to achieve?
I am trying to open the chat window between two members, I have created a channel specifying the two members. Now instead of open the chat listing i want to open 1-1 window directly.

## GetStream Environment
ios
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hey @zeeshansuleman,

Thanks for asking the question. This is possible, you can find how to do this in our documentation, by following this link: https://getstream.io/chat/docs/sdk/ios/swiftui/components/chat-channel/#directly-showing-channel-view.

Hope this helps.
Martin

**Comment by martinmitrevski** [comment]
Hey @zeeshansuleman, 

I'm assuming you are using this method:
```swift
let channelController = try chatClient.channelController(
            createDirectMessageChannelWith: selectedUserIds,
            name: nil,
            imageURL: nil,
            extraData: [:]
)
```
After you call `synchronize` (which means the controller is synced to the backend), you can still load the channel ID. You can then persist this ID in your backend.
```swift
channelController?.synchronize { [weak self] error in
        let channelID = self?.channelController?.channel?.cid
}
```
Another, less efficient alternative is to call the method `createDirectMessageChannelWith` every time. When the channel with those members exists, it will be reused, not re-created.

Hope this helps,
Martin

**Comment by zeeshansuleman** [comment]
@martinmitrevski Sure. I will check this and close this thread once done. Thanks for your help.

**Comment by martinmitrevski** [comment]
@zeeshansuleman if you are using the `ChatChannelView` and want to have navigation bar, you would need to wrap it in a `NavigationView` (if your previous view doesn't have one, or you used .fullScreen instead of push with `NavigationLink`).

**Comment by zeeshansuleman** [comment]
@martinmitrevski thanks for the help. It resolved my issue.

**Comment by zeeshansuleman** [comment]
@martinmitrevski by using chatchannelView the first time then opening the one-to-one chat from the chat listing it does not dismiss. Is there any reason? I am using below code to open one to one chat.
ChatChannelView(
                        viewFactory: CustomChatViewFactory(presentationMode: _presentationMode),
                        channelController: controller
                    )

**Comment by martinmitrevski** [comment]
Hey @zeeshansuleman,

Can you please provide more details? A video from the issue and more example code will help.

Thanks,
Martin

**Comment by zeeshansuleman** [comment]
https://user-images.githubusercontent.com/12757747/181693906-a76c9ceb-010e-45a3-8d87-f5850341a940.mp4

### One to One Chat

For Opening direct One to One chat we are using following code

**View**

ChatChannelView(
                        viewFactory: CustomChatViewFactory.shared,
                        channelController: controller
                    )

and controller which is used in ChatChannelView

private var controller: ChatChannelController {
        let controller = chatClient.channelController(
            for: chatViewModel.channelId!,
            messageOrdering: .topToBottom
        )
        return controller
    }

**ViewModel**

We are creating direct channel for opening the One to One chat by following method

func createChannel(skillrId: String, seekrId: String, receiverName: String?){
        let channelController = try? chatClient.channelController(createDirectMessageChannelWith: [skillrId, seekrId], type: .messaging, isCurrentUserMember: true, name: receiverName, extraData: [:])
        channelController?.synchronize { [weak self] (err) in
            self?.channelId = channelController?.channel?.cid
            if let error = err {
                logger.error("There is an error: \(error)", category: .userContext)
                return
            }
            self?.navigateToChat = true
        }
    }

### Chat Channels List
For showing the chat channel list, we are getting the Token and connect the user with stream and then channels shows by using following code

ChatChannelListView(viewFactory: CustomChatViewFactory.shared, title: "Messages")

**Comment by martinmitrevski** [comment]
Hey @zeeshansuleman,

I've tried re-creating your example with the following setup and it works correctly:
- one tab view with two items, both containing `NavigationView`s
- one of them is the `ChatChannelListView` from our SDK 
- the second one is a view with a button, that triggers the 1-1 chat, sth like this:
```swift
NavigationView {
            VStack {
                Button {
                    createChannel()
                } label: {
                    Text("Tap me")
                }
                
                NavigationLink(isActive: $navigateToChat) {
                    ChatChannelView(viewFactory: DefaultViewFactory.shared, channelController: controller)
                } label: {
                    EmptyView()
                }
            }
        }
```
Few questions here to help troubleshooting: 
- what's your setup for the view that displays the 1-1 channel, is it similar to the one above?
- is there something in the logs when you press the channel from the channel list?
- can you provide more details about the `navigateToChat` variable? Is it @Published? In general, sharing the `NavigationLink` that pushes the 1:1 view will help.
- the `channelController` in the `createChannel` method should be kept as a reference, with your setup it is immediately deallocated.

Looking forward to more details.

**Comment by zeeshansuleman** [comment]
@martinmitrevski I will try these and will let you know. I have another observation that opening the on-one chat view from the channel list and sending any message, This same issue can be observed in another flow written below.
- open one-on chat from the channel list.
- send any message by making the text field the first responder and opening the keyboard.
- pop the one-one chat view and then click on any channel to open the one-one chat view. At this time it also does not show up.

**Comment by zeeshansuleman** [comment]
@martinmitrevski i have tried the solution you provided but it did not work as well. Below is the code which I am currently using to push the on-one chat view.
```
.navigate(to: OneToOneChatView(skillrId: $skillrId, skillrName: $skillrName, chatViewModel: chatViewModel), when: $navigateToChat)
        .onChange(of: chatViewModel.navigateToChat) { isNavigateToChat in
            if isNavigateToChat{
                navigateToChat.toggle()
            }
        }
```

**Comment by martinmitrevski** [comment]
@zeeshansuleman I think the problem might be here: 
```swift
.onChange(of: chatViewModel.navigateToChat) { isNavigateToChat in
            if isNavigateToChat{
                navigateToChat.toggle()
            }
 }        
```
Why do you toggle the state only when `isNavigateToChat` is true? It seems that it's not reset to false when popping the screen. 
Also, is there a reason for using 2 different booleans for tracking the navigation state? `chatViewModel.navigateToChat` should be enough, so I think you don't even need this `onChange` modifier. The navigation link will reset it to false when it's popped. Sth like this:
```swift
.navigate(to: OneToOneChatView(skillrId: $skillrId, skillrName: $skillrName, chatViewModel: chatViewModel), when: $viewModel.navigateToChat)
```
Last thing to check, this `.navigate(to:` is not from the standard SwiftUI SDK. If it's custom implementation, it might also be causing issues.

**Comment by zeeshansuleman** [comment]
@martinmitrevski Now, I am directly navigating to ChatChannelView and using one @Published var for navigating but facing same issue. 

```
NavigationLink(isActive: $chatViewModel.navigateToChat) {
                if let channelController = chatViewModel.channelController{
                    ChatChannelView(viewFactory: CustomChatViewFactory.shared, channelController: channelController)
                }else{
                    EmptyView()
                }
            } label: {
                EmptyView()
            }
```

**Comment by martinmitrevski** [comment]
@zeeshansuleman is there any error logged when you press the channel?

We can also jump on a quick call on Monday to check it together, if you think it's related to the SDK.

**Comment by zeeshansuleman** [comment]
@martinmitrevski  No error loggesd. Is it possible to call today?

**Comment by martinmitrevski** [comment]
@zeeshansuleman I've sent you an email on Friday, not sure if you've received it (maybe check spam). Anyway, I'm available this morning for a call.

**Comment by zeeshansuleman** [comment]
@martinmitrevski please share the slot for the call. I am available.

**Comment by martinmitrevski** [comment]
@zeeshansuleman Video call link: https://meet.google.com/bzu-uyvp-doe

**Comment by martinmitrevski** [comment]
@zeeshansuleman our demo app can be found here: https://github.com/GetStream/stream-chat-swiftui/tree/main/DemoAppSwiftUI.

**Comment by zeeshansuleman** [comment]
@martinmitrevski Also tried making the single connect call with stream, The only concerning point is that despite an active stream token I am getting this error during quring the channel list.

```
{
  "code" : 2,
  "message" : "QueryChannels failed with error: \"stream-authService-type missing or invalid\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "StatusCode" : 401,
  "duration" : ""
}
```

**Comment by martinmitrevski** [comment]
@zeeshansuleman is this shown always or only on app start? If you try to open the channel list while you're still not authenticated (or SwiftUI does this when it renders the tab), this error will be shown, so it's best to prevent display of this view while still loading the token. Is the navigation issue solved now or is it still happening?

**Comment by zeeshansuleman** [comment]
@martinmitrevski this shows when i query channel list, not on stream connection. Also I am not able to test the navigation issue because of this as its not getting navigating and I am thinking the issue is might be due to this error.

**Comment by martinmitrevski** [comment]
hey @zeeshansuleman,

Can you try logging all the http requests, by adding this on app start (e.g. AppDelegate):
```swift
LogConfig.level = .debug
LogConfig.subsystems = .httpRequests
```
This will log all the http requests. You can then see if the token is correctly passed in the headers or it is empty.

**Comment by zeeshansuleman** [comment]
@martinmitrevski getting this now.

```
{ URL: https://chat.stream-io-api.com/channels?api_key=2z92sjhq92tx&payload=%7B%22watch%22:true,%22member_limit%22:30,%22filter_conditions%22:%7B%22members%22:%7B%22$in%22:%5B%227082f2a4-4333-4c94-a955-3cb99740bbeb%22%5D%7D%7D,%22message_limit%22:25,%22limit%22:20%7D } { Status Code: 401, Headers {
    "Content-Length" =     (
        198
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Mon, 01 Aug 2022 14:18:20 GMT"
    );
    Server =     (
        "stream-edge"
    );
    "Www-Authenticate" =     (
        "Bearer realm=\"QueryChannels failed with error: \\\"stream-authService-type missing or invalid\\\"\""
    );
} }, data:
{
  "code" : 2,
  "message" : "QueryChannels failed with error: \"stream-authService-type missing or invalid\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "StatusCode" : 401,
  "duration" : ""
})
```

**Comment by martinmitrevski** [comment]
@zeeshansuleman let's have another look in 30 minutes (17h GMT+2):  Video call link: https://meet.google.com/eiy-ypxg-gap

**Comment by zeeshansuleman** [comment]
@martinmitrevski I have managed to do it with stateobject but with a minor issue, The channel count is more than zero but the channel list view is not getting updated to reflect the channels. we can have a call tomorrow on this.

**Comment by martinmitrevski** [comment]
@zeeshansuleman cool, glad to hear this. Ok, let's have a quick call in my afternoon (16:30 pm GMT+2), to check the other issue you have. I've already sent you an invite:  Video call link: https://meet.google.com/hpg-yqaj-qji.

**Comment by martinmitrevski** [comment]
@zeeshansuleman As discussed, we're closing this issue. If you need additional support, please get in touch with our support team first: https://getstream.io/contact/support/.
