### ISSUE TITLE
Mixed media attachments have incorrect bubble 

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#88]
## What did you do?

Launched the demo app, attached 2 photos and a video, sent.

## What did you expect to happen?

The entire block having rounded top-left, bottom-left and top-right edges

## What happened instead?

The non-rounded edge in the middle of the block.

![Simulator Screen Shot - iPhone 12 Pro - 2022-05-31 at 16 51 07](https://user-images.githubusercontent.com/820120/171190442-6ecedd32-d0a0-4112-b88c-d75c28bf3109.png)
![Simulator Screen Shot - iPhone 12 Pro - 2022-05-31 at 16 51 23](https://user-images.githubusercontent.com/820120/171190448-c79cfdd2-0ff8-403a-b6cd-8266b7374bb6.png)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @zrxq,

Thanks for reporting this. We will analyze it and get back to you with an update.

Regards,
Martin

**Comment by martinmitrevski** [comment]
Hey @zrxq,

This is now fixed and available on `main`.

Thanks again for reporting,
Martin
