### ISSUE TITLE
Cyda

### ISSUE THREAD

**Issue by Jarenbeaver** [GetStream/stream-chat-swiftui#9]
## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
- [ FILE ] **iOS version:**
- [ FILE ] **Swift version:**
- [ FILE ] **Xcode version:**
- [ 1 ] **Device:**

- [ FILE ] ## Additional context

**Comment by Jarenbeaver** [comment]
Cyda command to create a project and Microsoft

**Comment by martinmitrevski** [comment]
Hey @Jarenbeaver,

Could you please provide some details about the issue you are having with the SDK?

**Comment by martinmitrevski** [comment]
Closing since no valid issue was reported.
