### ISSUE TITLE
User Mentions Not Being Sent

### ISSUE THREAD

**Issue by davefoxy** [GetStream/stream-chat-swiftui#96]
## What did you do?

I've mentioned a user in a Stream message but it doesn't appear that the library is parsing or sending them in `ChatChannelController`'s `createNewChannel` method.

You can see [here in `MessageComposerViewModel`](https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerViewModel.swift#L227) that the `mentionedUserIds` property is missing and so the default value of an empty array is being used. This is the codepath I'm seeing when entering text in the composer and tapping the regular send button.

In fact, only the `text`, `attachments` and `quotedMessageId` parameters are being sent.

This issue also seems to exist [when replying to messages here](https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannel/Composer/MessageComposerViewModel.swift#L213).

## What did you expect to happen?

I'd expect the `mentionedUserIds` value to be passed in as expected. Our backend is monitoring messages sent and cannot pick up on any user mentions without this.

## What happened instead?

No mentions are being passed.

## GetStream Environment
**GetStream Chat version:** `main` branch
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** Any
**Swift version:** Any
**Xcode version:** Any
**Device:** Any

**Comment by martinmitrevski** [comment]
Hey @davefoxy,

Thanks for reporting this. We have this already planned in our roadmap and it will be added in the SDK soon.

Best, 
Martin

**Comment by davefoxy** [comment]
Thanks @martinmitrevski. Can you give any idea of an ETA please? It's rather an urgent fix for us right now 🙏 🙇

**Comment by martinmitrevski** [comment]
@davefoxy, ok, in that case we will re-prioritize and look into this today. Hopefully by the end of the day or early next week should be available.

**Comment by davefoxy** [comment]
Thank you @martinmitrevski ! Much appreciated.

**Comment by martinmitrevski** [comment]
Hey @davefoxy,

This is now available both on the `main` branch and on `stream-chat-develop` (if you are still using it).

Best,
Martin

**Comment by davefoxy** [comment]
Thanks very much @martinmitrevski !
